### ISSUE TITLE
[BUG] individual2 icon not used from entity.

### ISSUE THREAD

**Issue by mariojungwirth** [flixlix/power-flow-card-plus#109]
For individual1 the icon is used 
For individual2 not. 

I use the same entity (only for test) 

Power-Flow-Card-Plus
![image](https://user-images.githubusercontent.com/5375476/233269295-09a62614-3c61-43cb-929c-9841f5895973.png)

Power-Flow-Card-Plus configuration
![image](https://user-images.githubusercontent.com/5375476/233269458-d023f1eb-d9ba-4324-84af-e552542b7b91.png)

Entity Values:
![image](https://user-images.githubusercontent.com/5375476/233269566-ca396c75-fc62-4f72-866a-f7bb4d37276f.png)

**Comment by flixlix** [comment]
Does the issue persist after reinstalling the new beta and clearing browser cache?

**Comment by mariojungwirth** [comment]
I have reinstalled the card. Clear the cache. 
It works! Thanks.!
