### ISSUE TITLE
[Feature Request] Proportional Grid Feed-In

### ISSUE THREAD

**Issue by melvanderwal** [flixlix/power-flow-card-plus#119]
Y'know how the outer ring of the Home entity displays coloured sections which indicate how much power is coming from the grid vs solar vs battery? Having that for the grid entity with solar vs battery power would be righteous. It would require having different line colours for battery to grid and solar to grid. 

Thanks very much for this card, it is excellent. Concisely informative cards like this are the best.

**Comment by flixlix** [comment]
Thank you for your suggestion, I appreciate it 👍

Can you explain in a little more detail what behavior you would expect?
Do you want the outer circle to show how much the solar panels are exporting compared to the battery?
Why would the battery be exporting to the grid? Does that not defeat the purpose of a home battery?
What should be shown, when nothing is exporting to the grid (which in my case is 90% of the time)?

**Comment by melvanderwal** [comment]
Thank you for responding and considering this.

The behaviour is as you describe - the outer circle displaying how much of the export is from solar and how much is from solar. When importing from the grid, the existing blue circle would be good.

> Why would the battery be exporting to the grid? Does that not defeat the purpose of a home battery?

My 16 kWh battery is large enough that I can discharge it to about 45% in the evening and it will power my house until solar is generating the next day.  My electricity plan is at variable, wholesale grid prices which continually fluctuate.  When the price is high, I feed electricity into the grid from my battery. People who have peak / off-peak feed-in tariffs also do the same thing.

![image](https://user-images.githubusercontent.com/25993713/233876578-42e4d6e7-195c-4e43-88be-62bff46dea36.png)

In this image from a few days ago, you can see:
- [yellow/brown fill] Solar generation during the day
- [purple fill] Battery discharge to the house in the morning, almost no discharge during the day when solar is generating, big discharge to the grid when prices are high from 5 pm to about 6:45, then normal discharge to the house during the evening.
- [white line] The feed-in price is nearly nothing during the day, then quite high in the evening.
- [purple dashed line] I don't have a SoC % axis labeled, but the battery was nearly depleted in the morning, charged to 90% at about 11:30 am (charge rate slows above 90%), fully charged at 1 pm, discharges to the grid from 5 pm to about 6:45 (when it reaches 45%), and then gets used for house consumption overnight.

On really hot days people are using their air conditioning, and prices sometimes get high near the end of the solar generation period but while solar is still generating. In those cases I'm exporting from both solar and battery.

**Comment by flixlix** [comment]
I'll add this to the to-do list but don't expect me to implement this anytime soon, since this doesn't apply to most peoples setups. Feel free to implement this yourself and submit a PR

**Comment by melvanderwal** [comment]
That sounds good, thanks for looking at it.
