### ISSUE TITLE
Incompatibility with browser_mod pop up card

### ISSUE THREAD

**Issue by tigers75** [flixlix/power-flow-card-plus#122]
I don’t know if we can call this strictly a bug, but I noticed that clicking/tapping on entities to show the more-info is not compatible with the browser_mod pop-up card: the regular pop-up is shown instead of the substitute card from browser_mod. I used it so when I click on solar production it shows a more informative window about the state of the whole photovoltaic entities, for the battery, for details on entities that are active in the house.
I think it has to do with the method used to display the more-info. I was wondering if someone found a workaround.

**Comment by flixlix** [comment]
Indeed this is not currently possible, since the card is not using the typical tap action, with navigation, call-service etc... This would be an enhancement

**Comment by flixlix** [comment]
Added to the To-Do List in the README
