### ISSUE TITLE
[BUG] Zero tolerance not working?

### ISSUE THREAD

**Issue by xsoriginal** [flixlix/power-flow-card-plus#123]
Hi there, 
![Screenshot 2023-04-23 143453](https://user-images.githubusercontent.com/76071605/233842906-b1c8fec3-f2a4-4dc2-9d3c-e6a30b76d069.png)
I'm trying to set the zero tolerance for my grid import to not show below 100W but it seems to still show regardless of how I set the value.

**Comment by flixlix** [comment]
Which version of the card do you have installed?

**Comment by xsoriginal** [comment]
0.0.9.6On 23 Apr 2023, at 14:39, Luca Félix ***@***.***> wrote:﻿
Which version of the card do you have installed?

**Comment by flixlix** [comment]
I'm sorry but this feature is only available in the beta (version 0.1beta) for now...
I accidentally added this configuration option to the main readme too early.
Can you try this option. using the 0.1beta version and see if the issue persists?

**Comment by xsoriginal** [comment]
Ah brilliant, thanks. All working as expected on 0.1b. Thanks for putting this card together, it’s truly awesome!On 23 Apr 2023, at 14:55, Luca Félix ***@***.***> wrote:﻿
I'm sorry but this feature is only available in the beta (version 0.1beta) for now...
I accidentally added this configuration option to the main readme too early.
Can you try this option. using the 0.1beta version and see if the issue persists?

**Comment by shiner66** [comment]
I'm running 0.1b, but I can't get the tolerance to work, how so?
