### ISSUE TITLE
[BUG] curved lines not connecting correctly to circles

### ISSUE THREAD

**Issue by tigers75** [flixlix/power-flow-card-plus#125]
**Describe the bug**
Curved Lines are not connecting to the circles. This is barely noticeable on mobile, but pretty clear on desktop.
Please note: I'm using the latest beta version, but the bug looks the same in non beta.
**To Reproduce**
Create a card that has curved lines
**Expected behavior**
The lines should touch the circles when connecting
**Screenshots**
![image](https://user-images.githubusercontent.com/37505492/234509794-9ccba89e-53d3-4e7e-9bba-f4b2ec92c386.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (less pronounced but still there on Android and iOS)
 - Browser: any

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
This is also the case in the official energy distribution card, so it's not a bug specific to this card. I already tried correcting this issue but the fix falls apart when resizing the window. I'll continue trying to fix this bug

**Comment by tigers75** [comment]
You are right. I never noticed it because the energy dashboard (first picture) is much more squeezed and it's less noticeable.
In the mobile view, where the screen size makes the 2 almost identical the gap is the same.
I don't think I can help in any way beside testing...
![image](https://user-images.githubusercontent.com/37505492/234577945-8547ec06-e033-453e-9aee-e3f56a10f068.png)
![image](https://user-images.githubusercontent.com/37505492/234578033-f99e20cf-7cd4-459b-a692-3fc76fc6a5ad.png)

**Comment by flixlix** [comment]
Fixed this issue in a new PR, will be available in the next version 0.1.1
![Bildschirmfoto 2023-05-07 um 18 06 39](https://user-images.githubusercontent.com/61006057/236689081-784efc38-9d44-46d4-8159-2ca79a3fb99d.png)
![Bildschirmfoto 2023-05-07 um 18 09 04](https://user-images.githubusercontent.com/61006057/236689117-318c5e4e-aa22-4733-bd35-79e9753c2b05.png)
