### ISSUE TITLE
[FEATURE REQUEST] Set icon/name from entity for the grid 

### ISSUE THREAD

**Issue by mariojungwirth** [flixlix/power-flow-card-plus#128]
Hello again, 
Could you also use the icon or name from the entity for the grid? 
Thanks

**Comment by flixlix** [comment]
This is already possible, read the readme

**Comment by flixlix** [comment]
I'll maybe add this as an option

**Comment by flixlix** [comment]
Just created a new PR to add this function to all fields, including `grid`, `solar`, `battery` (just the label for now), `non-fossil` and `home`.
#135 Will not be available in the version 0.1, but later
