### ISSUE TITLE
[FEATURE REQUEST] Get power direction from different sensor

### ISSUE THREAD

**Issue by elboletaire** [flixlix/power-flow-card-plus#130]
**Is your feature request related to a problem? Please describe.**
My inverter does not have a current in/out power used by the battery, instead, I have a "current power used by the battery" and a "battery direction", which shows me if the battery is currently charging, discharging or in standby.

**Describe the solution you'd like**
Be able to use that sensor direction to properly draw graphs (I need it for the battery ~~but I can image it being necessary in other entities~~ and the grid energy). I'd like to have a real time graph showing the current usage of my solar network, but since my battery sensor works this way, I get buggy graphs when the battery is charging:

![imatge](https://user-images.githubusercontent.com/153305/235342045-47848b78-79b9-40a1-b593-f4410311f8bb.png)
This is the actual real load of the network, not 2.6KW as it may look from the previous image:
![imatge](https://user-images.githubusercontent.com/153305/235342077-2ea8c474-c30f-4522-925a-c7520177efdd.png)

**Describe alternatives you've considered**
Changing how the sensors work, but it may cause me issues in other widgets or parts of the application I'm not aware rn.

**Additional context**
Here's what I'm trying to reproduce:
![imatge](https://user-images.githubusercontent.com/153305/235342139-5873eda6-c489-4959-9ef9-6540b843eb97.png)
But, of course, using your plugin looks badass compared to this.

**Comment by flixlix** [comment]
I recommend creating a template sensor for this case using a factor that gets multiplied with the state. This factor shall be 1 when the switch is on and -1 when the switch is off. I can't make sure to cover all of the special cases for sensor HA configurations. The separated vs. combined sensors could also be a template sensor, but I decided this is a more common use case. Thank you for your suggestion

**Comment by elboletaire** [comment]
Thanks, I actually was not aware of the templates feature in home assistant and they clearly can work for me.
