### ISSUE TITLE
[OTHER] beta UI giving error

### ISSUE THREAD

**Issue by wshankles** [flixlix/power-flow-card-plus#133]
I know the UI is in beta but just wanted to give a heads up I'm getting "Visual editor is not supported for this configuration:
s.entries is not a function".

**Comment by flixlix** [comment]
This is a known issue and should only occur when you have card mod installed or a component that has card mod as a dependency. I submitted a PR to card mod but the maintainer hasn't reviewed it yet. Please try removing this, clearing your browser cache and trying again.

**Comment by flixlix** [comment]
I created a fork of Card Mod with the changes from my PR. Feel free to install that version and give feedback on wether or not it works :)

https://github.com/flixlix/lovelace-card-mod/
