### ISSUE TITLE
[OTHER] The card shows total/accumulated values

### ISSUE THREAD

**Issue by andrewhack** [flixlix/power-flow-card-plus#134]
Hi,
Probably I am missing something but the card shows the total/accumulated values of the sensors. 
In HA Energy Dashboard the sensors could be customized and in my case the state class is total_increasing but still I can see daily values.
Is this possible with Power Flow card+

**Comment by flixlix** [comment]
This card aims to display **Power** values, not **Energy** and as such you should feed it with power entities that show your consumption **right now**.
[Power and Energy are two different things.](https://www.diffen.com/difference/Energy_vs_Power)
