### ISSUE TITLE
[OTHER] secondary_info Showing energy more accurate

### ISSUE THREAD

**Issue by flyzet-prog** [flixlix/power-flow-card-plus#138]
Hello there. 
I am just trying to showing secondary_info entity over house icon, it's show up correctly. But I need to showing it up more accurate let's say 3 decimals.
entity: sensor.house counting energy in kW/h.
Any suggestions would be much appreciated. 
<img width="965" alt="Screenshot 2023-05-03 at 15 40 55" src="https://user-images.githubusercontent.com/73076482/235920151-cdc18030-6cbe-47cd-b4a8-cb3073355199.png">

<img width="543" alt="Screenshot 2023-05-03 at 15 41 47" src="https://user-images.githubusercontent.com/73076482/235920180-9b9dc1e7-f67a-4c6b-a987-75557aa2e634.png">

**Comment by flixlix** [comment]
Before I answer your question, you set the `unit_of_measurement` to kW/h for energy, that is not correct. Use `kWh`.
In case you want more customizability for that secondary info field, try using a template instead of the entity
