### ISSUE TITLE
[FEATURE REQUEST] Clickable Secondary Info not only for Battery

### ISSUE THREAD

**Issue by langchr86** [flixlix/power-flow-card-plus#139]
I noted that we since 0.1 can display secondary info in every circle. I would like to be able to click on all those secondary info similar as the SOC of the battery.

Thanks for your excellent work on this fork of the original power-flow-card.

**Comment by flixlix** [comment]
I figured this would be asked eventually 😅
I'll try and add this functionality 👍

**Comment by flixlix** [comment]
Created a PR that fixes this, will be available in the version 0.1.1 🙂
