### ISSUE TITLE
[BUG] - Unexpected Behavior `override_state` `subtract_individual`

### ISSUE THREAD

**Issue by langchr86** [flixlix/power-flow-card-plus#140]
**Describe the bug**
Not sure if this is interpreted by everyone as a bug. But for me it would be better to be able to use a specific entity for the home circle and then also allow to substract the 2 individual entities.

**To Reproduce**

When I use the following config, I see the value for the configured entity but the values of the individual entities are not substracted.

~~~~~~
  home:
    subtract_individual: true
    override_state: true
    entity: sensor.xxx
~~~~~~

**Expected behavior**

If `subtract_individual` and `override_state` are both `true` I would expect a similar behavior as if `override_state` is `false`. Right now `subtract_individual` has no impact when `override_state` is `true`.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 112.0.5615.138

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
Opened a new PR #141.
Should fit this issue.
Available in the next version.
Feel free to reopen in case the next version doesn't fix this
