### ISSUE TITLE
Battery flow inverted

### ISSUE THREAD

**Issue by jdalesjo** [flixlix/power-flow-card-plus#143]
Using the huawei_solar integration. The battery charge/discharge entity is reversed compared to the power-flow-card-plus. (charging is a positive value and discharging a negative). There are no separate entities for charge and discharge. Could you add an "invert value" switch to the battery config?

**Comment by flixlix** [comment]
This is already possible, please use:

```yaml
inverted_entities: battery
```

In the main card config

**Comment by jdalesjo** [comment]
Outstanding, thank you. Couldn't see that config in the documentation. Must have missed it. 👍 
Got correct values on the card now.
