### ISSUE TITLE
[FEATURE REQUEST] CPU usage tweak

### ISSUE THREAD

**Issue by kongjudas** [flixlix/power-flow-card-plus#144]
**Is your feature request related to a problem? Please describe.**
The card utilize a huge amount of resources and my fan is running wild when the card is exposed in Lovelace.

**Describe the solution you'd like**
Animation config? I am not a coder, so I don't know if it helps to reduce the bullet size or tweak the card from the end user's side, but it's worth a try to ask.

**Describe alternatives you've considered**
Use the non-plus version
<img width="416" alt="Skjermbilde 2023-05-04 kl  14 02 27" src="https://user-images.githubusercontent.com/55403016/236198162-e9e2259a-cdde-449c-b80f-a1a39297b8a5.png">

**Comment by flixlix** [comment]
Which Hardware are you using? I have a 2021 MacbookPro M2Pro 14'' and the safari usage doesn't even go over 5%.

**Comment by kongjudas** [comment]
> Which Hardware are you using? I have a 2021 MacbookPro M2Pro 14'' and the safari usage doesn't even go over 30%.
Not the latest, but using more than one core is still a massive consumption.

2019 Macbook Pro
2015 iMac
Both act the same way.

**Comment by flixlix** [comment]
What is your suggestion to fix this issue? Do you want no animation? Or something else?

**Comment by kongjudas** [comment]
As I wrote, I'm not a coder. But from what I can see, the bullets are vector sized (right?).They fluctuate from 10 to 11 px as they move along. How about a fixed custom size?

**Comment by flixlix** [comment]
I've thought about this and unfortunately, because of the way this card is built, there's not much I can do to improve your CPU usage. I'll add this to my to-do list in case in the future I have some ideas on how to improve its performance. Thank you for your suggestion anyway

**Comment by mvanlijden** [comment]
Would love to see this improved!
I run my dashboard on a Raspberry Pi 4B, which should be more than enough to run a dashboard. Performance however is terrible with this card alone needing about 40-50% of the CPU usage. Together with other card (also other issues) this fills up the CPU to the point of failure and a unresponsive screen.

**Comment by lefa88** [comment]
I have the same problem. My iPad gets hot when showing this card, and even though I have it connected to charger, the battery level occasionally drops below 100%. My iPhone also loses a lot of battery power by having this card shown.

I did some tests, and noticed, that by disabling the dots the cpu usage (and heat) problem disappears. The issue seems to be related to the animation of the dots.

It is sad that this is the case, I really like this card as it is, and wouldn't want to disable the dots! Please look into this, I suspect it affects all users more or less.

**Comment by Tommixoft** [comment]
Anything that uses more than 1% of cpu power should be considered as a TOTAL FAIL. I run servers with 5 websites with simple cpu and still rarely get 5-10% usage. And when author say 

>  and the safari usage doesn't even go over 30%.

sounds strange to me. Im not mac user, i see mac as usual for apple-show usage in stupid way, author of topic shows usage that is more than 100% :D how it's even posisble to use something for more than 100% ? 
This should be labeled not as **enhancement**, but as a **bug**. Such simple animation should not be any problem for even crappiest cpu.
