### ISSUE TITLE
[BUG] Grid Show in W but the value are in kW

### ISSUE THREAD

**Issue by australian-117** [flixlix/power-flow-card-plus#146]
Hello, Great Project

The Guid view shows in W but the values are in kW. doesn't happen with all values.

<img width="364" alt="Captura de ecrã 2023-05-04, às 18 58 23" src="https://user-images.githubusercontent.com/61412651/236289981-a4461a52-132f-4061-a8a8-934087c733a5.png">

Maybe I got something configured wrong, tried 

<img width="976" alt="Captura de ecrã 2023-05-04, às 19 02 46" src="https://user-images.githubusercontent.com/61412651/236290197-40df7289-90b9-4fb5-831e-6dcec42ff2ca.png">

**Comment by flixlix** [comment]
Hey there,
while I do recommend you setup a template sensor to convert those values to `W`, you can override the unit, by using

```yaml
unit_of_measurement: "kW"
```

I also noticed that your configuration is using energy sensors, in which case this scenario is not officially supported by this card, so be careful and expect things to sometimes not work

**Comment by elboletaire** [comment]
I find it kinda weird that it was showing the values as expected in the previous version but now we need to specify the unit_of_measurement by entity 🤔

**Comment by flixlix** [comment]
It seems like you are using an old version of the card, because the `one_way` option is not being applied. Can you try downloading version 0.1 and clearing the cache afterwards

**Comment by elboletaire** [comment]
I have it updated.... I just did not remove settings from the previous version. And the problem persists with values that are kWh, which appear as W (but it did show kW in the previous version, as shown in the screenshot above).

![imatge](https://user-images.githubusercontent.com/153305/236431799-7a19ab0e-e4e6-48ab-a0db-403da2a523ec.png)

Now I only see kW on the current consumption, which is in W (and when it exceeds 1000 W, ofc):

![imatge](https://user-images.githubusercontent.com/153305/236431965-38ce4957-0d44-43fb-baef-bb988f498e88.png)

But all the other charts are shown with W. Also, I tried using the visual editor to set the unit of measurement, which adds it to `secondary_info`, but still doesn't seem to be doing anything:
![imatge](https://user-images.githubusercontent.com/153305/236432608-1500bd79-c58c-4f81-9291-10a223f2f492.png)

**Comment by flixlix** [comment]
Energy sensors (unit -> `kWh`) are not supported.

**Comment by elboletaire** [comment]
So... as I was saying, kinda weird it was working as many of us expect in the previous version but not in the current one. I guess I'll stick to the 0.9.9.6 version 🤷🏼

**Comment by flixlix** [comment]
And like I said: This is a **POWER** Flow card, not Energy. If you want to use energy sensors with this, feel free, but don't expect it to work.
https://www.diffen.com/difference/Energy_vs_Power

**Comment by elboletaire** [comment]
There's no need to be rude buddy. Speaking about software, this is considered a regression, because it was working in a way where more use cases were considered than are now.

If you don't want to fix it, just tag it as "won't fix", but considering all calculations work as expected and this is just a minor detail about units, MAYBE you could consider adding a feature to allow other units.

**Comment by flixlix** [comment]
I'm sorry, I didn't mean to come across as rude.

Although this card doesn't support energy, a lot of people have been using it in that way, so I feel obligated to allow that usage, this #152 gives you that opportunity. Will be available in the next version
