### ISSUE TITLE
[BUG] showing W not Kw

### ISSUE THREAD

**Issue by rossbate** [flixlix/power-flow-card-plus#149]
**Describe the bug**
Card is displaying W instead of Kw after W threshold is reached

**To Reproduce**
1. Open Conpanion App
2. view card

**Expected behavior**
To see Kw displayed and not W after the W threshold is reached

**Screenshots**
Added
![Screenshot_20230505_081518_Home Assistant](https://user-images.githubusercontent.com/39503487/236398351-db9aceba-e3b1-476f-ad65-ff5a246fe26c.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Samsung s21 ultra]
 - OS: [android 13 ]
 - Browser [stock]

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
Please post the relevant code

**Comment by rossbate** [comment]
![Screenshot_20230505_091538_Home Assistant](https://user-images.githubusercontent.com/39503487/236408859-0cd5b432-5178-4b80-bbf0-87edd69833ca.jpg)
It was working as should before updating card
![Screenshot_20230505_091546_Home Assistant](https://user-images.githubusercontent.com/39503487/236408864-d8bbaad8-29ef-48b7-9b95-e4c5707b102f.jpg)

**Comment by flixlix** [comment]
Your threshold is set to `1000`. That threshold was not reached in the card screenshot you provided

**Comment by rossbate** [comment]
That should of been Kw, it was show Kw just before I updated the card now it shows W, have cleared cache but not restated HA

**Comment by flixlix** [comment]
No, it doesn't show `kW`, because your states are all below `1000`. If you want to always have a unit of `kW`, set the threshold to `0`.

**Comment by rossbate** [comment]
I'm sorry if I'm not making it clear but in the initial screenshot all those values should be Kw., for instance it it 4kw from the grid but it is showing 4W, 3Kw into the battery but showing 3W and 1Kw from the battery but it is showing 1W, as I said nothing has changed except I upgraded the card to new release. I will try a restart of HA

**Comment by flixlix** [comment]
Going by the entity_ids, your sensors are energy sensors and not power sensors. You should only use this card with power sensors. If your sensor reports the states in kilowatt unit, make sure you have `unit_of_measurement: kWh` for the entity (not the card, but the entity attribute) setup

**Comment by rossbate** [comment]
[
![image](https://user-images.githubusercontent.com/39503487/236417660-0745245a-3004-43d1-b8ad-bad7c8dc689e.png)
](url)
The sensors have been working fine, always showed W under 1000w, then showed Kw over 1000w, but since the update this morning the card is showing W instead of Kw. This screenshot is of the battery sensors showing in Kw and their unit of measudement is Kwh.
I have restarted HA but still showing W

**Comment by flixlix** [comment]
Once again, you have energy sensors with the unit of `kWh`, which is not supported with this card.
I understand that it worked before with energy, but now it doesn't. I can't help you further with this, since energy is not supported. The checks in the new version were reversed, meaning, only if the `unit_of_measurement` is `kW` (**not `kWh`), does it get interpreted as `1000W`.
Use power sensors for this card or expect breaking changes

**Comment by rossbate** [comment]
It worked before the update, i will roll back.
Thanks for your support

**Comment by flixlix** [comment]
Although this card doesn't support energy, a lot of people have been using it in that way, so I feel obligated to allow that usage, this #152 gives you that opportunity. Will be available in the next version
