### ISSUE TITLE
KWH showing as watts

### ISSUE THREAD

**Issue by willhaggan** [flixlix/power-flow-card-plus#151]
H, Just noticed the card now shows the grid consumption in watts, whereas i have an entity of KWH, (unit_of_measurement: kWh) this was previously showing as expected but now for example 9.66 KW will show as 10w.

Regards
Will

**Comment by flixlix** [comment]
Although this card doesn't support energy, a lot of people have been using it in that way, so I feel obligated to allow that usage, this #152 gives you that opportunity. Will be available in the next version
