### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by milandzuris** [flixlix/power-flow-card-plus#158]
Visual editor is not supported for this configuration:
s.entries is not a function
You can still edit your config in YAML.
How fix this?
![image](https://user-images.githubusercontent.com/42905545/236697168-2d3c54cf-70cd-422b-a22d-2f7fc5483235.png)

**Comment by flixlix** [comment]
This issue is caused by card-mod. Like this in the README:

> ⚠️ Version 0.1 introduced the UI Editor. This Editor is currently incompatible with Card Mod. I created a PR to fix this issue, but it hasn't been merged yet. Here is the [PR #277](https://github.com/thomasloven/lovelace-card-mod/pull/277). If you want to use the UI Editor, please remove Card Mod and any Plugins that use Card Mod for this card **(.... for now)**.

**Comment by flixlix** [comment]
I created a fork of Card Mod with the changes from my PR. Feel free to install that version and give feedback on wether or not it works :)

https://github.com/flixlix/lovelace-card-mod/
