### ISSUE TITLE
[BUG] unit_of_measurement inactive when override_state is true

### ISSUE THREAD

**Issue by getget1980** [flixlix/power-flow-card-plus#167]
unit_of_measurement is inactive when override_state is true (at least in home circle)

**To Reproduce**

entities:
  home:
    color_icon: true
    entity: sensor.solarman_power_consumption
    unit_of_measurement: "kW"
    name: Maison
    override_state: true

sensor.solarman_power_consumption uses kW as unit and displays W

**Expected behavior**
Should display kW instead of W

**Screenshots**
With override set to true :
[https://i.imgur.com/XqvZH2O.png](https://i.imgur.com/XqvZH2O.png)

With override set to false :
[https://i.imgur.com/M0icale.png](https://i.imgur.com/M0icale.png)

**Desktop (please complete the following information):**
Windows, Mac,

**Smartphone (please complete the following information):**
iOS

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
`unit_of_measurement` is unfortunately not a valid configuration option for the `home` circle

**Comment by getget1980** [comment]
In fact it's not related to unit_of_measurement at all after testing.
Even if the value is natively in kW it displays it in W (without conversion) when override_state is true (and it's not the same behaviour when override_state is false)

My value sensor.solarman_power_consumption is in kW and it's not taken into account with override_state false

![image](https://github.com/flixlix/power-flow-card-plus/assets/29312002/59800c0f-ef05-4eac-a0c6-b18072ef2436)
