### ISSUE TITLE
Circle transparent background 

### ISSUE THREAD

**Issue by rcenik** [flixlix/power-flow-card-plus#168]
Could you make the circles have transparent backgrounds or have them match the theme? It looks a little out of place with different themes.

<img width="1640" alt="Screenshot 2023-05-09 at 7 50 28 PM" src="https://github.com/flixlix/power-flow-card-plus/assets/64944957/227997dd-c12b-472d-a50d-2b0edbd8bbd0">

**Comment by SalvatoreITA** [comment]
I also agree with the same request, thanks

**Comment by flixlix** [comment]
I added this background in version 0.1.1 to hide the lines behind the circles, but I hadn't thought of this use case. I'll try to figure out a different way to do this

**Comment by flixlix** [comment]
Fixed this 🥳 #169 
Will be available in the version 0.1.2

**Comment by SalvatoreITA** [comment]
Thank you 1000 for your efficiency in solving the problems!

**Comment by flixlix** [comment]
Released version 0.1.2! 🥳

**Comment by SalvatoreITA** [comment]
I just installed the update, restarted Home Assistant, cleared the cache but nothing the black background remains[
![66](https://github.com/flixlix/power-flow-card-plus/assets/74460788/e6f9a44e-98f4-4580-8476-b7e94ee0ff7d)
](url)

**Comment by flixlix** [comment]
I'm so sorry, it seems I uploaded the wrong js file 😅
Should be the correct file now, can you try redownloading it?
In case that doesn't work, you can use this file:
[power-flow-card-plus.js.zip](https://github.com/flixlix/power-flow-card-plus/files/11470606/power-flow-card-plus.js.zip)
Sorry once again

**Comment by SalvatoreITA** [comment]
Ok now it works!  Thank you 😁
![Screenshot_2023-05-13-23-21-23-743-edit_io homeassistant companion android](https://github.com/flixlix/power-flow-card-plus/assets/74460788/143ed49e-316e-4735-a7c6-53cd3f03e970)

**Comment by rcenik** [comment]
> Released version 0.1.2! 🥳

Thank you for the quick update. Looks great!!

<img width="1661" alt="Screenshot 2023-05-13 at 12 05 59 PM" src="https://github.com/flixlix/power-flow-card-plus/assets/64944957/a432c859-5f33-410f-b77c-60e6acb18024">
