### ISSUE TITLE
[FEATURE REQUEST] grid to battery and opposite 

### ISSUE THREAD

**Issue by e10kstarfire** [flixlix/power-flow-card-plus#171]
In the UK we have tariffs where it is beneficial to charge the battery directly from the grid, and also to discharge the battery directly to the grid.

Could you please add this feature so we can add entities for battery to grid & grid to battery and see the relevant flowing dots.

**Comment by flixlix** [comment]
This should already be possible...
When your battery is discharging more than your house is consuming, it should flow to the grid

**Comment by e10kstarfire** [comment]
Sorry, I have only just spotted this behavior now, you are correct  :-)
