### ISSUE TITLE
w_decimals is also used for the secondary info

### ISSUE THREAD

**Issue by seidler2547** [flixlix/power-flow-card-plus#172]
Hi, many thanks for this card.

I try to use the secondary info for the kWh produced/consumed. This works but I have to give it the explicit unit of measurement, even though my secondary info entities have them correctly set and the w_decimals is also applied to the secondary info. Would it be possible to make those independently configurable?

**Comment by flixlix** [comment]
It is very difficult to satisfy every possible scenario / use case for the `secondary_info` property. Can you try achieving this with the template option instead?
