### ISSUE TITLE
[BUG] When override_state is true in home, unit is not equal to sensor's unit

### ISSUE THREAD

**Issue by getget1980** [flixlix/power-flow-card-plus#173]
**Describe the bug**
When override_state is true in home, the unit is always W, even if the sensor unit is kW (without conversion) 

**To Reproduce**
1. Create a sensor in kW
2. Add this sensor to home entity
3. Set override_state: true

**Expected behavior**
Home power should be displayed in kW (or x1000 and displayed in W)

**Screenshots**

<img width="961" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/29312002/acd29098-3c07-4c6c-8c2e-0a91a63fe3c5">
"Maison" Should display kW not w

<img width="1048" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/29312002/7bfdb709-5383-4742-8778-72d77367bac7">

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
Your sensor has a unit of `KW` instead of `kW`. Can you try changing it to the correct unit `kW`?

**Comment by getget1980** [comment]
I’ll check this but I have to check the esphome code for the inverter canbus I’ll keep you on touch :)

**Comment by flixlix** [comment]
Fixed in #174, available in version 0.1.2 🥳

**Comment by getget1980** [comment]
Thanks :)

My inverter integration has an issue opened for the typo :)
