### ISSUE TITLE
[FEATURE REQUEST] more dynamic card height

### ISSUE THREAD

**Issue by Tommatheussen** [flixlix/power-flow-card-plus#176]
**Is your feature request related to a problem? Please describe.**
I'm trying to set up a full solar/battery dashboard, and I'm currently using the grid layout (from https://github.com/thomasloven/lovelace-layout-card).
When setting a row height to 50% or similar, I can get the card itself to that height, but the graph inside the card basically overlaps the next card (See screenshot).

<img width="564" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/13683094/c3d7ed77-2d43-4e45-ac9e-878af52e8d48">

**Describe the solution you'd like**
Being able to use the CSS grid to setup my dashboard :) 

**Describe alternatives you've considered**

**Additional context**

**Comment by flixlix** [comment]
This would be extremely difficult to achieve using the current layout, especially when individual devices are defined.
In addition to that, I don't think this adds to the UX in any way and is an unsupported use case, so for those reasons, unfortunately I will close this issue. Feel free to try to implement this yourself and submit a PR, but I think it's not within the current scope of this card.

**Comment by flixlix** [comment]
This feature is available in the last version! 🥳
https://github.com/flixlix/power-flow-card-plus/releases/tag/v0.1.6
