### ISSUE TITLE
Card doesnt load in webos device

### ISSUE THREAD

**Issue by sabbie-github** [flixlix/power-flow-card-plus#178]
Great card, working fine in pc Web browser, ios tablet, android devices, but won't load in lg Web os television.
Any chance to fix this - great card to show off HA solar integrations on the big screen, if it loads.
Thanks!
![20230515_172657](https://github.com/flixlix/power-flow-card-plus/assets/108624802/0cbc70f6-fcb3-4aa0-9a9c-02cb5fcf5b74)

**Comment by dbius** [comment]
Updated to 1.0.3 and the card is gone with exactly same error, on pc (chrome browser) and android mobile phone, too (companion app and chrome browser). Tried to revert to 1.0.2 but didn't help. Installed through HACS as always.

**Comment by flixlix** [comment]
Do you have Card Mod installed?

**Comment by dbius** [comment]
Yes

**Comment by flixlix** [comment]
Does uninstalling card mod fix the issue?
FIY: I didn't do any changes in regards to this issue in the new version, because I don't know yet what is causing this issue

**Comment by dbius** [comment]
Uninstalled card-mod, fully restarted HA didn't solve this. The card still missing with this error.

**Comment by flixlix** [comment]
Do you have access to the console of your browser, are there any errors there?

**Comment by dbius** [comment]
`browser_mod.js:407 BROWSER_MOD 2.2.1 IS INSTALLED    BrowserID: 599dae8c-aee6291b
load_resource.ts:32     GET http://homeassistant.local:8123/hacsfiles/power-flow-card-plus/null?hacstag=618081815013 net::ERR_ABORTED 404 (Not Found)
(névtelen) @ load_resource.ts:32
r @ load_resource.ts:6
s @ load_resource.ts:37
(névtelen) @ load-resources.ts:30
s @ load-resources.ts:12
(névtelen) @ ha-panel-lovelace.ts:235
Promise.then (aszinkron)
value @ ha-panel-lovelace.ts:233
value @ ha-panel-lovelace.ts:153
_$AE @ reactive-element.ts:1378
performUpdate @ reactive-element.ts:1345
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (aszinkron)
requestUpdate @ reactive-element.ts:1210
u @ reactive-element.ts:948
g @ reactive-element.ts:931
k @ lit-element.ts:115
r @ ha-panel-lovelace.ts:66
E @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hass-router-page.ts:296
value @ hass-router-page.ts:316
_currentLoadProm.l.then._currentLoadProm @ hass-router-page.ts:216
Promise.then (aszinkron)
value @ hass-router-page.ts:207
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (aszinkron)
requestUpdate @ reactive-element.ts:1210
u @ reactive-element.ts:948
g @ reactive-element.ts:931
r @ hass-router-page.ts:50
r @ partial-panel-resolver.ts:44
E @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
v @ lit-html.ts:1122
$ @ lit-html.ts:1531
_$AI @ lit-html.ts:1375
G @ lit-html.ts:2172
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (aszinkron)
requestUpdate @ reactive-element.ts:1210
u @ reactive-element.ts:948
g @ reactive-element.ts:931
k @ lit-element.ts:115
c @ home-assistant-main.ts:52
E @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
v @ lit-html.ts:1122
$ @ lit-html.ts:1531
_$AI @ lit-html.ts:1375
G @ lit-html.ts:2172
update @ lit-element.ts:165
value @ home-assistant.ts:32
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (aszinkron)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
value @ hass-base-mixin.ts:52
_updateHass @ context-mixin.ts:95
(névtelen) @ connection-mixin.ts:241
s @ store.js:19
(névtelen) @ collection.js:25
Promise.then (aszinkron)
c @ collection.js:25
d @ collection.js:27
(névtelen) @ collection.js:52
subscribe @ collection.js:95
T @ services.js:37
(névtelen) @ core.ts:119
Promise.then (aszinkron)
(névtelen) @ core.ts:113
(névtelen) @ core--AdzVoB_i-0.js:1
(névtelen) @ core--AdzVoB_i-0.js:1
DevTools failed to load source map: Could not load content for `

`load_resource.ts:13 Uncaught (in promise) http://homeassistant.local:8123/hacsfiles/power-flow-card-plus/null?hacstag=618081815013
n.onerror @ load_resource.ts:13
error (aszinkron)
(névtelen) @ load_resource.ts:13
r @ load_resource.ts:6
s @ load_resource.ts:37
(névtelen) @ load-resources.ts:30
s @ load-resources.ts:12
(névtelen) @ ha-panel-lovelace.ts:235
Promise.then (aszinkron)
value @ ha-panel-lovelace.ts:233
value @ ha-panel-lovelace.ts:153
_$AE @ reactive-element.ts:1378
performUpdate @ reactive-element.ts:1345
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (aszinkron)
requestUpdate @ reactive-element.ts:1210
u @ reactive-element.ts:948
g @ reactive-element.ts:931
k @ lit-element.ts:115
r @ ha-panel-lovelace.ts:66
E @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hass-router-page.ts:296
value @ hass-router-page.ts:316
_currentLoadProm.l.then._currentLoadProm @ hass-router-page.ts:216
Promise.then (aszinkron)
value @ hass-router-page.ts:207
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (aszinkron)
requestUpdate @ reactive-element.ts:1210
u @ reactive-element.ts:948
g @ reactive-element.ts:931
r @ hass-router-page.ts:50
r @ partial-panel-resolver.ts:44
E @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
v @ lit-html.ts:1122
$ @ lit-html.ts:1531
_$AI @ lit-html.ts:1375
G @ lit-html.ts:2172
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (aszinkron)
requestUpdate @ reactive-element.ts:1210
u @ reactive-element.ts:948
g @ reactive-element.ts:931
k @ lit-element.ts:115
c @ home-assistant-main.ts:52
E @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
v @ lit-html.ts:1122
$ @ lit-html.ts:1531
_$AI @ lit-html.ts:1375
G @ lit-html.ts:2172
update @ lit-element.ts:165
value @ home-assistant.ts:32
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (aszinkron)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
value @ hass-base-mixin.ts:52
_updateHass @ context-mixin.ts:95
(névtelen) @ connection-mixin.ts:241
s @ store.js:19
(névtelen) @ collection.js:25
Promise.then (aszinkron)
c @ collection.js:25
d @ collection.js:27
(névtelen) @ collection.js:52
subscribe @ collection.js:95
T @ services.js:37
(névtelen) @ core.ts:119
Promise.then (aszinkron)
(névtelen) @ core.ts:113
(névtelen) @ core--AdzVoB_i-0.js:1
(névtelen) @ core--AdzVoB_i-0.js:1
`

**Comment by dbius** [comment]
maybe the problem is not relatedt these?

you call it power-flow-card-plus.js 
but it is energy-flow-card-plus.js resource.

Tried to rename the resource in lovelace to energy-flow-card-plus.js

and the card name from custom:power-flow-card-plus
and the card showed up, but its not showing any energy flow nowhere despite the entities clicking on them show the values.

**Comment by flixlix** [comment]
These are two different cards. There is one Power Flow Card Plus & one Energy Flow Card Plus.

Can you verify you have Power Flow Card Plus installed?

**Comment by dbius** [comment]
I had only power-flow-card-plus installed. Removed, reinstalled, now it showed up again! TY!

**Comment by flixlix** [comment]
I'm glad I was able to help 🥳
