### ISSUE TITLE
[FEATURE REQUEST] Add button to swap consumption/production (for combined entity)

### ISSUE THREAD

**Issue by Minecrafter5K** [flixlix/power-flow-card-plus#189]
**Is your feature request related to a problem? Please describe.**
My Home Assistant integration for the current battery power outputs positive values for production and negative values for consumption, therefore the consumption/production values from _Power Flow Card Plus_ are the wrong way round.

**Describe the solution you'd like**
Add a button to swap the Production/Consumption values (for the Combined Entity).

**Describe alternatives you've considered**
Theoretically I could create a new sensor which would multiply the battery power with -1, but I think this solution is better :)

**Additional context**
![image](https://github.com/flixlix/power-flow-card-plus/assets/64906194/d02bd306-b44e-467d-942d-fe9efe6e585b)
Home power is ignored (it works if power from solar is available) and the battery is outputting power (not inputting).

**Comment by Minecrafter5K** [comment]
Oh, I just read this feature is already implemented. But I think it should still be added to the configuration GUI :D

**Comment by flixlix** [comment]
![Bildschirmfoto 2023-05-22 um 20 37 10](https://github.com/flixlix/power-flow-card-plus/assets/61006057/06289f8f-a126-482c-9f17-71ff4e68e360)

It is configurable via the UI in the `Inverted Entities` section.
Maybe it would make more sense to have them be in each section separately... I'll see how I'm going to implement this, but for now I'll close this issue :)

**Comment by flixlix** [comment]
Added this functionality in the new version 0.1.3 https://github.com/flixlix/power-flow-card-plus/releases/tag/v0.1.3 🥳
