### ISSUE TITLE
DC-DC option for RVs and "offgrid" solar systems?

### ISSUE THREAD

**Issue by AnotherStupidFuckingAccount** [flixlix/power-flow-card-plus#19]
I'm offgrid with this system, so I need a DC-DC input please! A generator input is a good idea also. Maybe a built-in trigger system for house batteries being low, generator triggers on, etc.

**Comment by flixlix** [comment]
I'm sorry but I'm not sure what this feature request really means. This card only serves UI (Frontend).
Can you please clarify, what it is exactly that you would like?

**Comment by flixlix** [comment]
I'll close the issue for now since I'm not sure what this FR entails. Feel free to reopen it
