### ISSUE TITLE
[BUG] Using a blank space as name moves the circle and lines are not properly aligned

### ISSUE THREAD

**Issue by JacoboSanchez** [flixlix/power-flow-card-plus#192]
**Describe the bug**
When using a blank space in the name configuration (to try to not display anything) the name disappears but the circle moves down to the location where the name was generating a gap between the lines and the circle

**To Reproduce**
Steps to reproduce the behavior: See screenshots

**Expected behavior**
An option to not show circle names or at least the possibility to use a blank space that it is printed in the flow to keep the lines aligned

**Screenshots**
With name
![imagen](https://github.com/flixlix/power-flow-card-plus/assets/11249890/1645682d-8dce-453c-a48c-96b0f0c3a25c)
Using space in name
![imagen](https://github.com/flixlix/power-flow-card-plus/assets/11249890/1106a9e9-094e-466d-94d6-82265ef45e1f)

**Comment by flixlix** [comment]
Fixed in #193 🥳
I just released version 0.1.3, so unfortunately you'll have to wait for 0.1.4.
If you don't want to wait, you can install this manually in the meantime
[power-flow-card-plus.js.zip](https://github.com/flixlix/power-flow-card-plus/files/11537562/power-flow-card-plus.js.zip)

**Comment by JacoboSanchez** [comment]
Amazing, thanks for the quick (more than that) response, will try it until the new version is released
