### ISSUE TITLE
More Individual Entities

### ISSUE THREAD

**Issue by felipebraz** [flixlix/power-flow-card-plus#194]
This card is just awesome, but do you know what could make it perfect? More individual entities, one example is this beautiful custom draw I made:

![image](https://github.com/flixlix/power-flow-card-plus/assets/14303499/29558845-a9e8-4bc6-9c53-4093be5bac1c)

The main structure is the same, but I would be able to add more Individual entities and just maybe entities under it too.

Thanks!

**Comment by flixlix** [comment]
I like the overall idea, but technically speaking this would be extremely difficult, because, by default, cards in HA have limited with and this can't be overridden (only using custom grid layout)

**Comment by felipebraz** [comment]
Custom grid is no a problem LoL... HA is made to be customized, what is HA without a lot of customizations?!
But I understand your point of view, I even tried to understand the code and how it works. I'm more a backend JS developer and the logic it self is fine, the front and design is another chapter to me... I may tried to do it my self but let's say the Paint drawing was nicer.
Well, I hope it works someday! Congrats for the real nice job you done here!

**Comment by felipebraz** [comment]
Just to exemplify this is my current under development home screeen (really customized):

![image](https://github.com/flixlix/power-flow-card-plus/assets/14303499/a2d4bc80-9fda-4b8e-905d-d168ef8d19a3)

**Comment by flixlix** [comment]
Thank you for the kind words!
I know it can be achieved, by installing custom layout, but most people do not have it and the card with multiple entities will look very crooked. Feel free to implement this yourself and submit a PR. Another idea for an implementation would be to always show the entity which is consuming / producing the most...
Closing this issue for now as not planned
