### ISSUE TITLE
Secondary info is not displayed after click on it in Home [BUG]

### ISSUE THREAD

**Issue by Scoperius** [flixlix/power-flow-card-plus#195]
**Describe the bug**
You cannot access the details for secondary info in Home. 

**To Reproduce**
1. Click on secondary info on Home circle
2. You receive the details for base sensor instead of secondary sensor

**Expected behavior**
I would like to see the details for secondary sensor 

latest version of all items

**Comment by flixlix** [comment]
Thank you for submitting this issue. It is indeed a bug that I hadn't noticed.

I fixed the bug and it will be available in the version 0.1.4 of this card :)

Closing this issue for now
