### ISSUE TITLE
Flow 'dots' do not work

### ISSUE THREAD

**Issue by finalbillybong** [flixlix/power-flow-card-plus#197]
Since the last update the flow dots are not working for me on Firefox Desktop, Safari Desktop and now iOS HA app too. I have cleared the cache on Firefox and Safari and the issue remains. 

What info can I provide for you?

![Capture](https://github.com/flixlix/power-flow-card-plus/assets/24855560/1764acd5-ba91-44ab-9a37-309eb321a270)
![IMG_0655](https://github.com/flixlix/power-flow-card-plus/assets/24855560/c6eedb41-3b26-448c-a519-35b47626761c)

**Comment by flixlix** [comment]
Do you have any errors showing up in the console?

Try using:

```yaml
use_new_flow_rate_model: true
```

If this doesn't work, what version is showing up in the console?

**Comment by finalbillybong** [comment]
`use_new_flow_rate_model: true`
Worked to fix the issue, thanks.

**Comment by SGDAT** [comment]
> `use_new_flow_rate_model: true` Worked to fix the issue, thanks.

This also worked for me. I dont have any dots without it with new update.
