### ISSUE TITLE
Secondary info for Non-Fossil does not inherit the Non-Fossil color [BUG]

### ISSUE THREAD

**Issue by Scoperius** [flixlix/power-flow-card-plus#200]
**Describe the bug**
Secondary info text for Non-Fossil does not inherit the Non-Fossil user color settings, the initial dark green is used instead. (Secondary info -> Color Value is On) 

**Expected behavior**
Colors should be the same if Color Value is on and Customized color is set.   

**Screenshots**

See example: Non-Fossil is under name "Export" in the screenshot

![obrazek](https://github.com/flixlix/power-flow-card-plus/assets/86469550/1f1c3796-101b-4699-a5b3-cbd30dcfe6c9)

**Comment by flixlix** [comment]
Fixed this bug in #201 
Will be available in version 0.1.4 🥳
