### ISSUE TITLE
no flow

### ISSUE THREAD

**Issue by vincenzopolito** [flixlix/power-flow-card-plus#204]
Hello beautiful card, it works, but I don't know why I don't see the flow balls moving.. why?
this is my configuration

![Schermata 2023-05-25 alle 19 30 05](https://github.com/flixlix/power-flow-card-plus/assets/114338668/db6acd41-baa1-4d99-b95f-ad5234faeb97)
![Schermata 2023-05-25 alle 19 30 13](https://github.com/flixlix/power-flow-card-plus/assets/114338668/bc3f758b-8b95-4b0f-aafe-19da39e9a22a)

**Comment by flixlix** [comment]
Thank you, glad you like the appearance!
The current version of the old flow rate model is unfortunately broken, so you'll have to use:
```yaml
use_new_flow_rate_model: true
```
for now.
The version 0.1.4 should come out in the near future, fixing this issue
