### ISSUE TITLE
[FEATURE REQUEST] secondary info for battery

### ISSUE THREAD

**Issue by blubbel42** [flixlix/power-flow-card-plus#205]
**Is your feature request related to a problem? Please describe.**
I do not have a charge percentage for my battery. Instead I use the battery-voltage. I can't see this in the card.

**Describe the solution you'd like**
please make the use of voltage (via secondary_info perhaps) instead of charge-percent possible

**Describe alternatives you've considered**
I tried using the percentage, but the % at the end keeps confusing me, and also the decimals are cut-off, which are critical for voltage

**Additional context**
Selfmade batterysystem without % at the moment, we plan to implement, but this takes some work and will have to wait. I assume there are other people with similar problems. Can't be the only who build their own.

**Comment by flixlix** [comment]
Would it be enough to add an option to change the unit of measurement of the state of charge?

**Comment by blubbel42** [comment]
absolutely. then it would not be confusing anymore. Thanks

**Comment by flixlix** [comment]
Added both these options in the PR #208 🥳
Will be available in version 0.1.4
