### ISSUE TITLE
[BUG] Secondary info in home not displaying

### ISSUE THREAD

**Issue by kaspall** [flixlix/power-flow-card-plus#220]
<img width="460" alt="Screenshot 2023-05-29 at 17 49 01" src="https://github.com/flixlix/power-flow-card-plus/assets/123463360/904a07ef-1756-4d2e-98bc-202e254d8ef8">
<img width="463" alt="Screenshot 2023-05-29 at 17 49 09" src="https://github.com/flixlix/power-flow-card-plus/assets/123463360/b98e6576-cfd9-4d14-a59d-8d65d2dd2c7b">

It was working in the previous version of the card, but not displaying the the current version.
Also, the secondary info of the grid does not allow negative values, it would be nice if this was allowed or at least give the user the option.

**Comment by flixlix** [comment]
Sorry for the inconvenience.
Should be fixed in v0.1.4.hotfix02 😅
