### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Coastersteve** [flixlix/power-flow-card-plus#221]
The animation line between Solar and Battery is no longer there in the very latest version. The Battery bubble shows whether its charging or discharging but the ball that should go between solar and battery doesn’t happen when charging. The ball is there for discharging to the house though. 

Running version 0.1.4 Hotfix 1.

**Comment by flixlix** [comment]
Sorry for the inconvenience.
I changed almost all lines from the main file to restructure it, so these bugs may occur in this version.
Should be fixed in v0.1.4.hotfix03 though 😊
