### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Hummelchen01** [flixlix/power-flow-card-plus#225]
Hello, 

With Power Flow Card Plus v0.1.4.1 the unit is now showing wrong.

![Screenshot 2023-05-30 091217](https://github.com/flixlix/power-flow-card-plus/assets/37904485/b63b10ec-26ce-48a6-9e00-88fb99912e47)

**Comment by flixlix** [comment]
Fixed in #228. Unit White Space was also missing
