### ISSUE TITLE
Card not inverting state on IOS devices.  [BUG]

### ISSUE THREAD

**Issue by shayes83** [flixlix/power-flow-card-plus#230]
**Describe the bug**
It appears after the latest update that the card shows my home consumption as Production(solar) + Home Consumption.  I changed the invert_state: true and the correct power calcs show on my desktops, but all IOS devices show this error.  so in other words on my IOS devices, the solar is added to my home's power consumption and therefore showing nothing being dumped back to the grid.

IOS is latest 16.somthing

CODE:

type: custom:power-flow-card-plus
entities:
  grid:
    entity: sensor.net_power_calc
    icon: mdi:transmission-tower
    color_icon: true
    color: '#80b8ff'
    scan_interval: 00:00:01s
    display_zero: false
    invert_state: true
  solar:
    scan_interval: 00:00:01s
    entity: sensor.envoy_202243194833_current_power_production
    display_zero: false
  home: {}
w_decimals: 0
kw_decimals: 2
min_flow_rate: 1
max_flow_rate: 5
watt_threshold: 10
clickable_entities: true
title: Hayes Power System Monitor
use_new_flow_rate_model: true

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X ] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [ X] I have the latest version of the card installed.

- [X ] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
This seems to be a cache issue.
AFAIK there's no way to clear the cache on iPhone apart from deleting and reinstalling the HA app.
Can you try opening this view in a dashboard that you've never used for HA?

**Comment by shayes83** [comment]
I was able to open HA on a IOS device that did not previously have it installed, and it appears to be correct.  So for my other devices the fix is to uninstall and reinstall?

**Comment by shayes83** [comment]
OK, so if you go through settings and general and then manage Iphone Storage, you can offload the app and the reload it all from the same screen and it takes no time at all.  Should just be noted that this would be a necessary step for multiple IOS instances of HASS that are all running from the same SBC such as an ODROID....

Again, great card!
