### ISSUE TITLE
Secondary info for Home does not use Unit of measurement [BUG]

### ISSUE THREAD

**Issue by Scoperius** [flixlix/power-flow-card-plus#233]
**Describe the bug**
Secondary info for Home does not use proper Unit of Measurement, there is "W" instead of the one set in the setup.  

Version: 1.41

**Comment by flixlix** [comment]
Fixed in #238 
Will be available in the next version

**Comment by Scoperius** [comment]
Nice, thanks... Petr Lustyktel: 775436197 | Čisovice 251, 25204 | Česká republika -------- Původní zpráva --------Od: Luca Félix ***@***.***>Datum: st 31. kvě 2023 13:43Komu: flixlix/power-flow-card-plus ***@***.***>Kopie: Scoperius ***@***.***>, Author ***@***.***>Předmět: Re: [flixlix/power-flow-card-plus] Secondary info for Home does not use Unit of measurement [BUG] (Issue #233)
Fixed in #238
Will be available in the next version

**Comment by Scoperius** [comment]
Nice, thanks.

![Screenshot_20230601_173742.jpg](https://github.com/flixlix/power-flow-card-plus/assets/86469550/9c6b812b-1182-4040-9b65-db4cbe1307aa)
