### ISSUE TITLE
Unit of measurement incorrect

### ISSUE THREAD

**Issue by wiedwo** [flixlix/power-flow-card-plus#240]
**Describe the bug**
In the Home-Tab defined a secondary info as "SolarNet Autarkiegrad" (=sensor.solarnet_relative_autonomy) with unit_of_measurement: %, but the graph shows W ?
Also verfied yaml code, also '%' specified.

Works well in version

**Screenshots**
![grafik](https://github.com/flixlix/power-flow-card-plus/assets/129332930/80dca27d-a7c5-4d12-ae44-3fb00b25ca9e)

and the corresponding yaml-code:
 home:
    color_value: true
    secondary_info:
      entity: sensor.solarnet_relative_autonomy
      icon: mdi:recycle-variant
      display_zero: true
      unit_of_measurement: '%'
      color_value: true
      unit_white_space: false
    subtract_individual: false
    name: Zuhause
    override_state: false

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
Already fixed in #238, will be available in the next version
