### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ben00793** [flixlix/power-flow-card-plus#243]
**Describe the bug**
1. Home power circle shows incorrect colors when there is energy import from the grid.
1.Non fossil percentage doesn't show up.

**To Reproduce**
type: custom:power-flow-card-plus
entities:
  battery:
    entity: sensor.battery_power
    state_of_charge: sensor.battery_state_of_charge
    color_circle: true
    color_value: false
    display_zero_tolerance: 0
    display_state: one_way
    invert_state: true
    color:
      consumption:
        - 255
        - 145
        - 0
      production:
        - 0
        - 204
        - 0
  grid:
    entity: sensor.grid_power
    display_state: one_way_no_zero
    color_circle: true
    color:
      consumption:
        - 255
        - 0
        - 0
      production:
        - 102
        - 255
        - 255
  solar:
    entity: sensor.pv_power
    display_zero_state: true
    color_value: false
    color_icon: false
    secondary_info:
      entity: sensor.temperature
      unit_of_measurement: °C
    icon: mdi:solar-power-variant
    color:
      - 255
      - 255
      - 0
  home:
    entity: sensor.load_power
    override_state: false
    subtract_individual: true
    secondary_info: {}
  fossil_fuel_percentage:
    entity: sensor.co2_signal_co2_intensity
    state_type: percentage
    display_zero: true
    color_value: false
    unit_white_space: false
    secondary_info:
      display_zero: false
      unit_of_measurement: W
      unit_white_space: true
      display_zero_tolerance: 200
    display_zero_state: false
    display_zero_tolerance: 0
  individual1: {}
clickable_entities: true
display_zero_lines: false
use_new_flow_rate_model: true
w_decimals: 0
max_flow_rate: 5
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000
inverted_entities: battery
dashboard_link: /energy
kw_decimals: 2
min_flow_rate: 1
dashboard_link_label: Energy Dashboard

**Expected behavior**
There should be still the colors from either the solar or the battery present in the circle.
Non fossil should show the percentage.

**Screenshots**
![Screenshot_20230601-081314_Chrome](https://github.com/flixlix/power-flow-card-plus/assets/132856308/c32a42a9-99ba-41fa-82cc-cdbc2b80f415)

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [ x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x ] I have the latest version of the card installed.

- [ x] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
Both issues should be fixed now and will be available in the next version :)

In case the issues persist after the next version, feel free to open this issue again

**Comment by flixlix** [comment]
Just released v0.1.5 :)
