### ISSUE TITLE
[BUG] Home circle does not show the correct secondary info

### ISSUE THREAD

**Issue by schiffko** [flixlix/power-flow-card-plus#249]
**Describe the bug**
The home circle, does not show the correct secondary info. It shows the secondary info of the production circle.

**To Reproduce**
1. Set different values for Home and Solar secondary info.
2. The Solar info will be shown in Home AND Solar circle.

**Screenshots**
![Bildschirmfoto 2023-06-02 um 08 11 50](https://github.com/flixlix/power-flow-card-plus/assets/14902009/7530c6c0-32b0-441f-bb24-dd440b579389)

![Bildschirmfoto 2023-06-02 um 08 12 38](https://github.com/flixlix/power-flow-card-plus/assets/14902009/211b0b5c-8e57-4b02-bcaa-3b13def95666)

![Bildschirmfoto 2023-06-02 um 08 12 49](https://github.com/flixlix/power-flow-card-plus/assets/14902009/a84bbf8b-1f1c-47e8-aac0-53e21f291aa9)

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1
 - Browser: Safari
 - Version: v0.1.5

**Additional context**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
What version of the card gets shown in your browser console?
Can you send the code of your card combined with the state of each entity?

**Comment by flixlix** [comment]
Closing for now due to inactivity.
Seems like you are using an old version that had this bug

**Comment by flixlix** [comment]
This was indeed a bug, fixed in #256 
Available in v0.1.5.1

**Comment by schiffko** [comment]
Thank you. Sorry i was ooo the last weeks. Really great job, now it works.
