### ISSUE TITLE
Flow Formula suggestion

### ISSUE THREAD

**Issue by shadow7412** [flixlix/power-flow-card-plus#25]
At the moment it takes the current maximum and minimum currents. I think if we had the ability to set our own max and minimum values (either instead of or in addition to the real ones) we'd get a more realistic animation.

Eg, If I set my maximum to 5kw, then even if the total system is only seeing 300W the animation would be slow, because we have the hardcoded maximum. Also, hardcoding 0W to minimum would mean that everything should animate consistently relative to that range.

If that was acceptable behaviour, I could see the value of 0 being used instead of the calculated minimum and a config-driven value for maximum working quite well.

**Comment by flixlix** [comment]
I like this suggestion, but I am currently focusing on other additional features, so it will take some time.
@shadow7412 would you be willing / capable to submit a PR for this feature?

**Comment by shadow7412** [comment]
See #34

**Comment by flixlix** [comment]
merged #34 
Thank you for your support!

**Comment by shadow7412** [comment]
I think we might need more work on this... the difference between 25W and 1kW seems indistinguishable...

**Comment by flixlix** [comment]
Yes I noticed this right after merging. I didn't have this issue while testing, because I set `max_expected_flow_w` to `10`, so then it makes no difference... I'm currently working on other features though, so I don't have much time for this

**Comment by flixlix** [comment]
I'm currently working on another flow rate formula, I'll see when I can finish it. For now I'll close this issue. Thank you anyways for your PR 👍
