### ISSUE TITLE
Line is still drawn using combined entity and Display Zero Tolerance with internal negative values and Display Zero Lines turned off [BUG]

### ISSUE THREAD

**Issue by Darcody** [flixlix/power-flow-card-plus#260]
**Describe the bug**
I am using a _combined entity_ for my grid values. Positive values are consumption, negative values are production. Due to some noise in the data it flickers a few watt when around zero. Using the _Display Zero Tolerance_ it filters out that noise and shows correctly the zero value. _Display Zero Lines_ is turned off. And for the positive (consumption) values no line is drawn. But when the internal values are negative (production) the line is still drawn while the value is correctly shown as zero in the circle.

**To Reproduce**
***Grid***
- Use a _combined enitity_ with positive values for consumption and negative values for production
- Set _Display Zero Tolerance_ to i.e. 10. 
- Turn off _Display Zero Lines_ under _Advanced Options_
While internal values are between 0 and 10 no line is drawn ✔ and the value for consumption is shown as zero ✔
While internal values are above 10 a line is drawn ✔ and the value for consumption is shown ✔
While internal values are between -10 and 0 a line is drawn ❌, but the value for production is shown as zero ✔
While internal values are below -10 a line is drawn ✔ and the value for production is shown (As positiv value) ✔

**Expected behavior**
Don't show a line when the value is between 0 and -10 while using a combined entity and the _Display Zero Tolerance_ set to 10.

**Screenshots**
![image](https://github.com/flixlix/power-flow-card-plus/assets/12135817/dc3a0b66-4f94-404d-bab4-eb5ab1d5144e)
Hint: **Netzeinspeisung** is using the same entity as the grid _combined enitity_

**Desktop (please complete the following information):**
 - OS: Win 10 and Win 11
 - Browser [chrome]
 - Version [latest]

**Smartphone (please complete the following information):**
 - Device: [Pixel 7]
 - OS: [Android 13]
 - Browser [Home Assistent App, Chrome]
 - Version [latest]

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by Darcody** [comment]
UPDATE: This also applies when using separate entities.

**Comment by flixlix** [comment]
Can you check if this file solves the issue?

The Console **MUST** log the following:
![Console Version 0.1.5 - 260](https://github.com/flixlix/power-flow-card-plus/assets/61006057/9fffaa1c-b7e7-4a92-8bf0-46a0d8c76c19)

Otherwise, you don't have the file is not being used. Check the instructions in the readme for a manual install and clear the cache of your browser.

[power-flow-card-plus.js.zip](https://github.com/flixlix/power-flow-card-plus/files/11680059/power-flow-card-plus.js.zip)

Would love to get some feedback, so I now if the issue is fixed and can push the changes to the next version

**Comment by Darcody** [comment]
This change seems to work:
![image](https://github.com/flixlix/power-flow-card-plus/assets/12135817/dee18a50-3256-4dbc-afe3-7f9a82c1a267)

![image](https://github.com/flixlix/power-flow-card-plus/assets/12135817/3008fc81-716c-4890-9b7f-5e5e4636e501)

Thank you very much for your effort!

**Comment by flixlix** [comment]
Thank you very much! Glad to see it worked!

Just released the new version, which fixes this issue.

https://github.com/flixlix/power-flow-card-plus/releases/tag/v0.1.5.2
