### ISSUE TITLE
[OTHER] Wrong font-weight in title

### ISSUE THREAD

**Issue by jzielke84** [flixlix/power-flow-card-plus#272]
Hi,

just a small suggestion for a design change: the font-weight in all cards normally is 600 for the title, not 400. You can verify this by looking at other stock-cards. This makes the power-flow card go along better with the general ui appearance.

Julian

**Comment by flixlix** [comment]
![Bildschirmfoto 2023-06-08 um 17 34 14](https://github.com/flixlix/power-flow-card-plus/assets/61006057/e230a537-17a1-416f-9112-d48fb4fd9bc5)
Where do you see this occurring? In my case both cards have 400 font-weight

**Comment by jzielke84** [comment]
Here using the Metro Blue theme:
![image](https://github.com/flixlix/power-flow-card-plus/assets/13448042/6662c214-296a-48a2-aeed-d444f8743fc9)

So this seems to be a theme issue, not a card issue. Sorry for the false report. I'll close it.
