### ISSUE TITLE
Amazon Fire tablet Custom element doesn't exist

### ISSUE THREAD

**Issue by syberx** [flixlix/power-flow-card-plus#274]
hi, on my pc all okay but on my fire device i can not load the card [Custom element doesn't exist]

**Comment by flixlix** [comment]
This sounds like a cache issue. 
I have two Fire Tablet HD10s and have no issue.
Which browser are you using? Are there any errors printed in the console?

**Comment by flixlix** [comment]
Closing this issue for now since I assume the issue will be fixed with clearing the cache.
Feel free to reopen the issue in case it persists after clearing the cache

**Comment by syberx** [comment]
Hello, of course I cleared the cache. It keeps happening. I also re-logged in. The energy card from HA works. the flow Plus does not. I've searched a bit and it seems to be due to an older web view or something.. But that can't be updated. A Firetab 7 inch is about 3 years old. It works everywhere else.

**Comment by flixlix** [comment]
Do you have any browser console errors?
What browser are you using?

Other than that, I don't think I can help you any further, since the card works on two of my fire tablets....

**Comment by syberx** [comment]
fully kios browser. I have update amazon webview with a .apk now working
