### ISSUE TITLE
[FEATURE REQUEST] Invert entity values

### ISSUE THREAD

**Issue by terafin** [flixlix/power-flow-card-plus#276]
**Is your feature request related to a problem? Please describe.**
My solar entity is set up to be a negative (for math purposes) value, but it looks like this card expects solar to be positive. 

**Describe the solution you'd like**
Is it possible to add a setting (maybe for each?) to invert the entity value?

**Describe alternatives you've considered**
I've worked around this by creating template entities, but... would be nice to not :)

**Comment by terafin** [comment]
Thank you!

**Comment by flixlix** [comment]
I didn't do I before because I thought it wouldn't be needed...
Added the option to invert the state for solar! 🥳
