### ISSUE TITLE
"subtract_individual" does not play nice with "override_state"

### ISSUE THREAD

**Issue by dr3amr** [flixlix/power-flow-card-plus#287]
"subtract_individual" does not play nice with "override_state". when both are enabled, consumption of individual is substracted from actual value of sensor.house_power.

ex:
  home:
    entity: sensor.house_power
    subtract_individual: true
    override_state: true

sensor.house_power = 500 W 
if ( override_state: true & subtract_individual: true & individual_consumption = 5 W) => Graph Home Load = 495 W which is false

In above scenario:
if ( override_state: true & subtract_individual: true & individual_consumption = 5 W) => House load = 500 W 
if ( override_state: true & subtract_individual: false & individual_consumption = 5 W) => House load = 505 W

**Comment by flixlix** [comment]
> if ( override_state: true & subtract_individual: true & individual_consumption = 5 W) => Graph Home Load = 495 W

No, it is true. The idea of `subtract_individual` is to show the home power without the individual devices.
If you want to get the home power with the individual devices, you need to remove that setting

**Comment by dr3amr** [comment]
I do not agree 
subtract_individual: false should add the value to the house load, 
subtract_individual: true should remove this value leaving the house load calculated or in case override_state: true the exact value of the sensor, not substracted ... 
The individual is not calculated in the value of the sensor for house load (sensor.house_power) to be substracted from.

**Comment by dr3amr** [comment]
I created a new house load sensor adding the individual sensor value also, this way when subtract_individual: true, house load is without the individual, but not substracted from house load value.
