### ISSUE TITLE
secondary info not showing data in kw + kw_decimals

### ISSUE THREAD

**Issue by dr3amr** [flixlix/power-flow-card-plus#288]
I have a power-flow-card-plus that shows values only in KW for day (same as the energy dashboard).
Bellow details show 0kW for the secondary sensor.solar_self_use_day even though the value of the sensor is already in kWh. If changing the unit to "kW", the value changes but with value is without decimals 5.51 on sensor would be displayed as 6 not taking account of kw_decimals value.

kw_decimals: 1
watt_threshold: 0
  solar:
    entity: sensor.on_off_grid_day
    secondary_info:
      entity: sensor.solar_self_use_day
      display_zero: true

**Comment by flixlix** [comment]
This is expected if you are overriding the unit of measurement. Please configure the `decimals` option if you want to change the number of decimals

**Comment by dr3amr** [comment]
kw_decimals set to any value, secondary info value is same without decimals. If we are rushing to close issues before properly understanding them...means this is just lack o proper willing to support...

**Comment by flixlix** [comment]
I just don't think you are reading what I wrote.
I said that if you want to set the decimals for the secondary info, use the decimals option in secondary info

**Comment by dr3amr** [comment]
decimals option only available for individual not for secundary info. It does nothing when added to secondary as per bellow:

  solar:
    entity: sensor.on_off_grid_day
    secondary_info:
      entity: sensor.solar_self_use_day
      unit_of_measurement: kW
      decimals: 1
      display_zero: true

**Comment by flixlix** [comment]
Fixed this issue in version 0.1.6.1 🥳
Thank you for submitting the issue

**Comment by dr3amr** [comment]
Please add the new attribute also to Readme.md => Secondary info

**Comment by flixlix** [comment]
Added to the Readme :)
