### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NemesisXB** [flixlix/power-flow-card-plus#293]
**Describe the bug**
The values displayed on the Power Flow Plus GUI don't match the actual value from the enitity.

**To Reproduce**
Don't really know. just set it up with an entity on the Home

**Expected behavior**
Expect the shown value to match the entity value

**Screenshots**
image showing Home doing 983W.
![image](https://github.com/flixlix/power-flow-card-plus/assets/485436/c38319f7-4cdf-4a7d-b003-2e695aad7f01)

clicking on Home icon, loads the Entity page. Here it shows 1070W
![image](https://github.com/flixlix/power-flow-card-plus/assets/485436/4c219e0b-c4e1-4720-8645-50f95e61d477)

**Desktop (please complete the following information):**
 - Any

**Smartphone (please complete the following information):**
- Any

**Additional context**
None

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
That is because the home circle is calculated by the card by default using the different sources.
Use `override_state: true` in the home object to override the number that appears in the circle

**Comment by NemesisXB** [comment]
> That is because the home circle is calculated by the card by default using the different sources. Use `override_state: true` in the home object to override the number that appears in the circle

Thanks. Came back to update that I found it.
