### ISSUE TITLE
[feature request] Add second dashboard_link

### ISSUE THREAD

**Issue by alexeiw123** [flixlix/power-flow-card-plus#297]
Now that we can customise the default dashboard link, I realised it would be handy to use that space to add a second link that is right justified.

My left button links to a custom energy graphs page, I'd still like to be able to link to the default HA Energy Dashboard as well.

![image](https://github.com/flixlix/power-flow-card-plus/assets/77809797/de4c2d08-37bd-4229-aa92-78bd5572cbb7)

**Comment by flixlix** [comment]
Added this feature in version 0.1.6.2 🥳
