### ISSUE TITLE
[BUG] Limited to 2 decimals for kW

### ISSUE THREAD

**Issue by cedricdelecole** [flixlix/power-flow-card-plus#300]
**Describe the bug**
I think it is a bug, but if not feel free to move it somewhere else.
I set the kW to 3 decimals, but it only shows 2 maximum ...

**To Reproduce**
1. go to Edit the "power-flow-card-plus"
2. go to change W_decimals or kW decimals to 3
3. It limits to 2 decimals

**Expected behavior**
Expected to see 3 decimals, at least for the kW value in the circle

**Screenshots**

<img width="976" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/135960043/a73a471e-7f07-454e-9233-d8e8f693506d">

**Browser Console Errors**
If applicable, add Errors from the browser console.

**Desktop (please complete the following information):**
 - macOS
 - Browser : Safari

**Smartphone (please complete the following information):**

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [ x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x ] I have the latest version of the card installed.

- [x ] I have cleared my browser cache **after** installing, updating and configuring the card.

- [ x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
The bug was caused by Home Assistant Locale overriding the number of decimals.
Fixed in version 0.1.6.1 🥳
