### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NemesisXB** [flixlix/power-flow-card-plus#306]
**Describe the bug**
When using the new transparency setting for 0 lines, the line from grid to battery does not seem to go opaque even when there is flow as indicated by the flow dot:
![image](https://github.com/flixlix/power-flow-card-plus/assets/485436/6e7a0bc4-c6d6-40f7-afeb-76dd9db91c60)

**To Reproduce**
I have display zero lines set to transparent with opacity 90. Not sure if it only happens when the flow rate is very small.

**Expected behavior**
The line should go opaque any time there is flow on it.

**Screenshots**

**Browser Console Errors**
App, browser any

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser - EDGE

**Smartphone (please complete the following information):**
 - Device: Samsung S23+
 - OS: Android 13
 - Companion App: Latest

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by NemesisXB** [comment]
Some more info, when not setting a Solar entity, not even the dot appears.
![image](https://github.com/flixlix/power-flow-card-plus/assets/485436/aabf4712-fdfc-4f22-9d5a-975756e45a6a)

**Comment by flixlix** [comment]
hello and sorry for the late reply, I've been very busy in the past few weeks 😅

Fortunately I was able to fix both bugs you mentioned. The changes are implemented in #311.

These changes will be applied in the next version of this card!
