### ISSUE TITLE
Freezing under the latest HA 2023.7.0(1) in ios app [BUG]

### ISSUE THREAD

**Issue by Kratax** [flixlix/power-flow-card-plus#310]
**Describe the bug**
When opening dashboard with power flow card plus card, the app is freezing on iphone (using native HA app for ios)

**To Reproduce**
1. Go to any dashboard with power flow card on ios
2. Scroll and after couple of seconds the page freezes, ony reopening the app helps

working well on safari though

**Expected behavior**
no freezing

 - OS: latest ios, latest HA app

I have tried clearing cache as well (in HA app)

**Comment by Kratax** [comment]
https://github.com/flixlix/power-flow-card-plus/assets/25452697/539f07aa-b2a3-494a-bfeb-1ddd44a96634

**Comment by themex85** [comment]
I have the same issue. I also think it is caused by the Power Card Plus integration. 

Home Assistant 2023.7.1
Power Flow Card Plus v0.1.6.1
iOS 16.5.1
Home Assistant Companion App 2023.4
Safari Browser

**Comment by flixlix** [comment]
Hmm...

I wonder if this is related to #178, doesn't seem like it though...

It is extremely difficult for me to try and debug this, since I don't own any IOS Devices and this is working in my MacBook

**Comment by N3rdix** [comment]
No issue on my side, so it can't be a general issue. Are you sure this is caused by the Power Flow Card itself? I am curious how it behaves if you put the card on a blank page...

Home Assistant 2023.7.3
Power Flow Card Plus v0.1.7
iOS 16.6
Home Assistant Companion App 2023.4

**Comment by Kratax** [comment]
Seems to be solved in the latest version of HA and at the end was related to history charts, ie I would close this.
