### ISSUE TITLE
Exclude Battery Usage from Home

### ISSUE THREAD

**Issue by AshGSmith** [flixlix/power-flow-card-plus#314]
Problem:
When my home battery storage is charging the Power Flow Card shows my home usage including the power going into the battery as well the power going into the battery, so it skews the figures (screenshot attached of an example.
![IMG_2095](https://github.com/flixlix/power-flow-card-plus/assets/68118872/8ce90e0d-b297-40cf-ae09-42c72a3a1ed9)

Proposed Solution:
Add a toggle into the Home area to "Exclude Battery Import" which excludes any power going into the battery from the Home usage. Similar to the "Subtract Individual" option but ensuring it only excludes it if the battery is charging, not discharging.

Alternative Solution:
Allow the selection of an entity that provides the Home usage value rather than relying on a calculation based on other entity values.

**Comment by e10kstarfire** [comment]
"Allow the selection of an entity that provides the Home usage value rather than relying on a calculation based on other entity values."

Try using override_state true

**Comment by AshGSmith** [comment]
> "Allow the selection of an entity that provides the Home usage value rather than relying on a calculation based on other entity values."
> 
> Try using override_state true

That did the trick, I didn’t notice that one, thanks!
