### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by maatx** [flixlix/power-flow-card-plus#315]
After the last update, the solar to battery line no longer appears but has been replaced by the grid to battery line. Obviously the grid marks zero and the battery is regularly charged from solar. No configuration changes were made before or after the upgrade.

![Screenshot 2023-07-10 alle 09 20 33](https://github.com/flixlix/power-flow-card-plus/assets/4578794/f501d3ca-88f1-4317-9e58-99b776e0f6c7)

**Comment by iJAY86** [comment]
I'm having the same issue.![IMG_20230710_093656.jpg](https://github.com/flixlix/power-flow-card-plus/assets/23543483/e4bdc544-8759-4639-a723-49e8e00b7433)

**Comment by dg1yds** [comment]
Same issue since update to 0.1.6.2
<img width="507" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/17652957/1bec32e7-e818-4b17-ae1e-cda962f85771">

**Comment by maatx** [comment]
> [power-flow-card-plus.js.zip](https://github.com/flixlix/power-flow-card-plus/files/12002729/power-flow-card-plus.js.zip)
> 
> Can you please check if this solves the issue?

Now everything seems to be ok

**Comment by flixlix** [comment]
Great! I'll push the changes and release a fix
