### ISSUE TITLE
[FEATURE REQUEST] Capability to show more than two individual devices

### ISSUE THREAD

**Issue by MikaelHoogen** [flixlix/power-flow-card-plus#316]
I would like the capability to show more than two individual devices.

**Comment by flixlix** [comment]
Hey,
this feature has been requested multiple times and currently I'm not planning on adding it.
See #261 for more info.

**Comment by MikaelHoogen** [comment]
> Hey, this feature has been requested multiple times and currently I'm not planning on adding it. See #261 for more info.

Okey. I have an idea that you can configure more than two devices. But the card only shows two at the time. You can set the priority order of the devices.
