### ISSUE TITLE
[BUG] Battery appears charging from grid

### ISSUE THREAD

**Issue by Agimgrue** [flixlix/power-flow-card-plus#317]
Battery appears charging from grid with the line balls moving from grid to battery, when actually power comes from PV Excedents.

![image](https://github.com/flixlix/power-flow-card-plus/assets/92628531/8d81e04b-453e-49a7-b855-cda766ebebeb)

Red row is wrong. Green should be the correct

**Comment by flixlix** [comment]
Which version of the card do you have?
This was a bug with version 0.1.6.2, but should be solved in 0.1.6.2.1

**Comment by Agimgrue** [comment]
Yeah, solved with last update! Thanks!

**Comment by flixlix** [comment]
Glad I was able to help 😀
