### ISSUE TITLE
[BUG] - Non Fossil showing as "NaN"

### ISSUE THREAD

**Issue by Vinisz** [flixlix/power-flow-card-plus#324]
Hi,

All of a sudden, the "non-fossil" shows as "NaN"
I verified if it was still pointing to the correct entity and it it is (also the entity itself and the "normal" energy dashboard are showing data.

Current issue (with power-flow-card-plus):

 
![image](https://github.com/flixlix/power-flow-card-plus/assets/49644964/c4467c87-177b-4b83-b789-12b52deef9db)

Expected (picture from "build-in" energy dashboard)

![image](https://github.com/flixlix/power-flow-card-plus/assets/49644964/076ee3a0-1637-4e71-ad1a-ac41e0cb3cf6)

**Comment by flixlix** [comment]
Can you send the code you are using as well as the state of the fossil entity?

**Comment by Vinisz** [comment]
It was solved somehow (no idea what caused this)Please close the issueOp 20 jul. 2023 om 01:44 heeft Luca Félix ***@***.***> het volgende geschreven:﻿
Can you send the code you are using as well as the state of the fossil entity?
