### ISSUE TITLE
[BUG] Display state of grid doesn't work

### ISSUE THREAD

**Issue by leejoow** [flixlix/power-flow-card-plus#330]
**Describe the bug**
Configuration of display_state of grid entity is not working correctly
If configured in the UI as **One Way (Show Zero)** the YAML contains **one_way_no_zero** (I would expect **one_way**)

**To Reproduce**
Create an instance of the coard and configure the display state to one_way or one_way_no_zero.

**Expected behavior**
If configured as one_way to show only the net grid and display nothing if 0
If configured as one_way_no_zero to show only the net grid usage

**Screenshots**
Configuration one_way:
![image](https://github.com/flixlix/power-flow-card-plus/assets/23429929/db4bb70d-3be6-4813-9777-abc21bd972d0)

Configuration one_way_no_zero (while there is net usage):
![image](https://github.com/flixlix/power-flow-card-plus/assets/23429929/547baf17-0fac-40aa-bc56-2c5dd9afec10)

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
Fixed in version [0.1.7](https://github.com/flixlix/power-flow-card-plus/releases/tag/v0.1.7)! 🥳
