### ISSUE TITLE
[BUG] Grid Outage label does not update

### ISSUE THREAD

**Issue by NemesisXB** [flixlix/power-flow-card-plus#338]
**Describe the bug**
Grid outage label does not update.

**To Reproduce**
1. Configure power outage for grid
2. On grid outage

**Expected behavior**
Grid label should change on outage

**Screenshots**
Config:
![image](https://github.com/flixlix/power-flow-card-plus/assets/485436/2b9e0d59-0a32-4de3-bc9e-6d3f7a7b704e)
On power outage - Label is not updated:
![image](https://github.com/flixlix/power-flow-card-plus/assets/485436/99333705-bd0a-4001-b02e-285f0bbe4fa7)

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
In case you are referring to the name i.e. "Grid" below the grid circle, no this isn't supposed to change in case of an outage. What changes is the state that is shown. In case you have no generator entity selected, the [Label for Alert] will be used. In case that is not defined, the string "Power Outage" will be used.

Note:
The card will only recognize an Outage in case the state of your entity (Left field in the editor) matches the [State of Alert], in case this is not defined, default is "on", meaning if your main entity has a state of on, the card will recognize that as a power outage.

This is the default behavior in case of an outage:
![Grid Circle in Power Outage](https://github.com/flixlix/power-flow-card-plus/assets/61006057/6153605e-d935-4848-9c4a-cd854c1e8804)

**Comment by NemesisXB** [comment]
Yeah, that was what I meant. I Understand now. Thanks.
