### ISSUE TITLE
[BUG] Clicking on the grid entity when generator showing still open grid detail page

### ISSUE THREAD

**Issue by NemesisXB** [flixlix/power-flow-card-plus#339]
**Describe the bug**
Clicking on the grid entity always loads the grid detail page even when the generator is the current running supply.

**To Reproduce**
1. Set a grid as well as a generator entity for the grid.
2. When grid fails, click the grid entity (which should now be the generator entity)
3. Grid entity detail is always displayed and not the generator entity when it is active

**Expected behavior**
When the grid data is shown in the grid circle, clicking it should open the grid data detail page. When the generator is shown in the grid circle, clicking it should show the generator detail page.

**Screenshots**
Clicking the grid item loads the grid entity detail page even though the generator is the currently active entity:
![image](https://github.com/flixlix/power-flow-card-plus/assets/485436/b1282f41-3c49-4aca-bd1f-1c22e4ac1bc0)

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
I implemented this on purpose this way, but I changed it nonetheless. Will be available in the next version
