### ISSUE TITLE
[OTHER] Use this card in a html page

### ISSUE THREAD

**Issue by mariojungwirth** [flixlix/power-flow-card-plus#341]
Is there a way to use this "card" in a normal HTML page as well, so that the data comes via Ajax/Json request?

**Comment by flixlix** [comment]
Hmm... Unfortunately this card is really made for HA...
But there's nothing stopping you from copying these HTML lines: 

https://github.com/flixlix/power-flow-card-plus/blob/25f67084a500c1a7d6de49ec16630ce0f721bca1/src/power-flow-card-plus.ts#L1028-L1880

and the style file:

https://github.com/flixlix/power-flow-card-plus/blob/25f67084a500c1a7d6de49ec16630ce0f721bca1/src/style.ts#L1-L415

into your own project. You would though need to implement the data fetching and such all inside that project...

I would love to do that for your, but unfortunately my time is currently very limited, but feel free to ask me for help 😊
