### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by Snehotice** [flixlix/power-flow-card-plus#345]
Hello
 I have two PV sources at home. I would need the second power plant to be counted through the electricity meter. see video: https://youtu.be/p1YV5_pxzmo  . Is this possible? Thank you.

**Comment by flixlix** [comment]
The only way of doing this currently is by creating a template sensor that adds the two values

**Comment by Snehotice** [comment]
I would like to ask you for adwice. How do I create a template sensor that
adds the two values ?

po 31. 7. 2023 v 10:27 odesílatel Luca Félix ***@***.***>
napsal:

**Comment by flixlix** [comment]
While you can do this as a template, it is easier to do in the UI:

Go to Settings -> Devices -> Choose the "Helpers" Tab -> Add a new Helper -> Select this one

![](https://github.com/flixlix/power-flow-card-plus/assets/61006057/79230fbc-6881-475c-a200-429ca0a50de7)

**Comment by Snehotice** [comment]
Thank you very much.

po 31. 7. 2023 v 19:10 odesílatel Luca Félix ***@***.***>
napsal:
