### ISSUE TITLE
[BUG] Points moving despite W being displayed as "0"

### ISSUE THREAD

**Issue by cpohli** [flixlix/power-flow-card-plus#348]
**Describe the bug**
Despite setting the "display_zero_tolerance: 30" in my grid and fossil rings, the accourding lines and moving points are display as active when using power below 30W.

**To Reproduce**
- Configure a "display_zero_tolerance: xx" in grid and/or fossil.

**Expected behavior**
When i use "display_zero_tolerance: xx" i expect the lines and moving points to be inactive - even when there is a powerflow below the xx set in "display_zero_tolerance: xx".

**Screenshots**
<img width="513" alt="SCR-20230803-mxnv" src="https://github.com/flixlix/power-flow-card-plus/assets/32699124/0155e67b-93bd-4b4f-91d3-210a84ed5bd9">

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by daelsc** [comment]
I came here to report the same issue.  It also manifests itself with very small loads, so having a "display point zero tolerance" would be super.  I don't need to see that my EV is using 2watts.

<img width="508" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/7574162/d45c65c7-9cf2-4e66-9d8f-347edec4b996">
