### ISSUE TITLE
[FEATURE REQUEST] Add Energy Today

### ISSUE THREAD

**Issue by TonyM1958** [flixlix/power-flow-card-plus#349]
Saw this example of a power flow and thought having power and energy today on the same card was really useful. I know there are separate power flow card plus and energy flow card plus but having a snap shot of today's energy in the blank space around the power flow card plus elements would be really neat and useful.

![Screenshot_20230806-074338_Facebook](https://github.com/flixlix/power-flow-card-plus/assets/63789168/60ba38cc-5a26-445b-a04f-7222c4116dea)

**Comment by flixlix** [comment]
What I would recommend you do is create a Utility Meter Sensor that shows the days' energy value and use it in the `secondary_info` field, that way I feel like this FR would be fulfilled

**Comment by TonyM1958** [comment]
Thanks - I tried this - with mixed results.

It work OK for solar and for house load where I have energy meter.

For grid - there are both import and export power sensors but only 1 secondary sensor. I have a template that produces the difference between import and export each day in kWh so added this. However, the secondary info only displays +ve values. -ve values are displayed as zero.

For battery, I have a similar sensor that shows the difference between charge and discharge energy in a day. However, there is no secondary info for Battery.

So, a solution for solar and house but not for grid or battery elements?
