### ISSUE TITLE
[BUG] Battery exporting to grid, numbers are wrong :-(

### ISSUE THREAD

**Issue by neildsb** [flixlix/power-flow-card-plus#351]
I may have missed something during the last update 

but my card is a little odd again while the sun is shining and battery exporting

![image](https://github.com/flixlix/power-flow-card-plus/assets/91122872/55854750-2dba-4d19-a16c-3efbe6fbf831)

0.1.7

Home Assistant 2023.8.1
Supervisor 2023.08.1
Operating System 10.4
Frontend 20230802.0 - latest

type: custom:power-flow-card-plus
entities:
  battery:
    entity: sensor.apf_battery_entity
    state_of_charge: sensor.powerwall_charge
    invert_state: true
    name: Tesseract
  grid:
    entity: sensor.apf_grid_entity
    name: Octopus
    invert_state: true
  solar:
    entity: sensor.apf_generation_entity
    display_zero_state: false
  fossil_fuel_percentage:
    entity: sensor.grid_fossil_fuel_percentage
    icon: mdi:pine-tree
    color_icon: false
    display_zero: true
    name: Non Fossil
    state_type: power
  individual1:
    entity: sensor.tesla_charging
    icon: mdi:car-electric
    color: '#80b8ff'
    name: Cars
    color_icon: false
  individual2:
    entity: sensor.heat_pump_immersion_combined
    icon: mdi:heat-pump-outline
    color: '#ffe880'
    name: Heat Pump
    color_icon: false
clickable_entities: true
display_zero_lines:
  mode: hide
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 0.75
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000
inverted_entities: battery, grid

**Comment by affer** [comment]
<img width="452" alt="Screenshot 2023-08-30 at 07 47 40" src="https://github.com/flixlix/power-flow-card-plus/assets/3717164/50754023-d5a6-4da3-aebd-d752f18f4f71">
I see the same - when exporting and panels are producing, i get no usage in house.
