### ISSUE TITLE
[FEATURE REQUEST] more than two individual sources

### ISSUE THREAD

**Issue by nicolap75** [flixlix/power-flow-card-plus#356]
Hi, really great work, is it maybe possible in future releases to have the possibility to add more individual sources?

Thank you very much and thank you for your contribution to the community.
N.

**Comment by flixlix** [comment]
Thank you for the kind words, unfortunately this feature has been requested multiple times here, but is not currently planned due to  not enough space and too much code complexity. Still any PRs implementing this feature are welcome. Sorry for the inconvenience.
