### ISSUE TITLE
[FEATURE REQUEST] Option to automatically calculate the grid power

### ISSUE THREAD

**Issue by JokerGermany** [flixlix/power-flow-card-plus#357]
**Is your feature request related to a problem? Please describe.**
I think many people don't have an grid sensor, would be cool if there would be an option to calculate the grid sensor.

**Describe the solution you'd like**
e.g. when when you entered only Home and Solar, it only shows the home power when you have solar power and not the whole home power:
![grafik](https://github.com/flixlix/power-flow-card-plus/assets/30293477/8cbe1a21-3bef-43b8-badb-31933e6b13c3)
Would be great if in this case it would automatically subtract solar from home and show it as grid.

**Describe alternatives you've considered**
Template Sensor, but i hate template sensors in text editor...

**Comment by flixlix** [comment]
Hey,
this is already possible using a template sensor.
Since it is more common to know the grid consumption than the home consumption, I am not planning on adding this functionality anytime soon.
