### ISSUE TITLE
[SUPPORT] Unusually high CPU usage

### ISSUE THREAD

**Issue by amit-nz** [flixlix/power-flow-card-plus#358]
Hi There

Have been using this card for a while now and really loving it. Unfortunately, I am finding that in the past few months (dates are fuzzy sorry!) having this card added visible is making whatever device it runs on have high CPU usage. On my iPhone for example, if I have this card visible the scrolling in the app becomes choppy. If I just leave it visible for a minute or so, the CPU usage is high enough to cause the back of the phone to heat up. Similarly, Activity Monitor on MacOS shows very high CPU usage for the HASS App as highest (despite having other poorly optimised apps like the Microsoft suite, Firefox etc open simultaneously).

I have verified it is the card that is causing the high CPU usage, as when I move it to a hidden dashboard the CPU usage on my device(s) returns to normal levels.

I used the firefox Profiler to view tab CPU usage. I found that when I had the HASS tab open, between 40-50% of my CPU usage was due to this one tab. I profiled it and got this:

![image](https://github.com/flixlix/power-flow-card-plus/assets/12567648/f6bd4459-208c-4d69-bc3f-badb21d11343)

My server platform is HASS OS VM (version 2023.8.1) running on Proxmox. My client side is Win 11 Pro machines running FireFox and an iPhone 12 Pro Max running 16.6 with the HASS App v 2023.4 (all versions latest at the time of this post). 

Please let me know if I can provide any further diagnostic information on figuring out why the CPU usage is so high. 

My card code:

```title: Solar & Battery Energy Flows
type: custom:power-flow-card-plus
use_new_flow_rate_model: true
clickable_entities: true
watt_threshold: 1000
entities:
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    icon: mdi:pine-tree
    color_icon: true
    display_zero: true
    name: Renewables
    state_type: power
  grid:
    entity: sensor.power_meter_active_power
    display_state: two_way
    color_circle: true
  solar:
    entity: sensor.input_power
    color_icon: false
    use_metadata: false
    display_zero_state: true
  battery:
    entity:
      consumption: sensor.battery_discharging_power
      production: sensor.battery_charging_power
    state_of_charge: sensor.battery_state_of_capacity
    display_state: one_way
    color_circle: true
  home:
    color_icon: true
  individual1:
    display_zero: true
    entity: sensor.hotwater_power
    icon: mdi:water-boiler
    color: '#80b8ff'
    name: HWC
    color_icon: false
  individual2:
    entity: sensor.aircon_power
    name: A/C
    color_icon: true
    display_zero: true
    color: '#ff8080'
    icon: mdi:air-conditioner
display_zero_lines:
  mode: show
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189

**Comment by flixlix** [comment]
I also notice this sometimes.
This issue is related to this: #144
I had not had the chance to check what exactly is causing this performance issue...

**Comment by flixlix** [comment]
After a lot of debugging, I can say that the increased CPU Usage is due to the dots animations (This is even the case in the original `energy-distribution` card). Unfortunately there is nothing I can do about that, because I am using the built-in svg animations.
Sorry for the inconvenience
