### ISSUE TITLE
[FEATURE REQUEST] Battery should manage `inject_power` values

### ISSUE THREAD

**Issue by mmattel** [flixlix/power-flow-card-plus#360]
**Is your feature request related to a problem? Please describe.**
Charging/discharging a battery is not equal with injected power to the grid from the battery

**Describe the solution you'd like**
The battery is the source of how the energy flows **into** the grid.
It can inject energy to the grid which reduces charge.
In can consume energy from solar to be charged.
It passes energy that is not used for charging to injection.

The battery should have an optional flow state
(optinal creating a 2nd battery, mutual exclusive):

* If the flow state is not configured, nothing changes to the current behaviour, so no breaking change
* If the flow state is configured, the situation is the following
  * `inject_power` is the only value that adds power to home eg. 100 [W] and can only be >= 0
  (formerly this was defined by `battery_flow` which can be +/-)
  (dots from battery to home if inject > 0)
  * `battery_flow` defines the charge (-)/discharge (+) direction **and** value eg. +/- 30 [W]
  (charge from solar, discharge to inject, maybe with a delta powering electronics, we dont care)
    * charging the battery can therefore only happen when solar is > 0
  * if `battery_flow` is charging (-)
    (dots from solar to battery)
  * if solar has values > charging the battery (consider the charging battery sign)
  this adds power to home but as part of `inject_energy`
  (means the flow diagram shows dots from solar to home too for indication)
```
  battery:
    entity: sensor.solmate_inject_power            [W]
    state_of_charge: sensor.solmate_battery_state  %
    state_of_flow: sensor.solmate_battery_flow     [+/- W]
```

**Describe alternatives you've considered**
You cant cheat physics.
Note that a split setup does not help, it is an incompatible concept.

**Comment by flixlix** [comment]
Hey,
I'm sorry but I don't think I understood the issue you are describing.
I myself am using this card with a battery and never felt the need to add a second entity (I didn't get what it is for).
For now I'm closing this issue, since I don't see anything wrong with the current setup, but feel free to reopen in case you think I missed something...
