### ISSUE TITLE
[FEATURE REQUEST] Grid of three phases

### ISSUE THREAD

**Issue by mmattel** [flixlix/power-flow-card-plus#361]
**Is your feature request related to a problem? Please describe.**
When you have a grid with 3 phases and your solar is connected to only one phase, you cannot see the energy flow properly as (P1 + P2 + P3) can be bigger than solar input compared only using Px where solar is connected to. A sum(Px) compared to Px will most likely seldom show an energy backflow compared to solar power input. You will also add solar to the most used phase, expecting not to have a 3-phase solar...

**Describe the solution you'd like**
The grid should have beside the phase where solar is connected to also additional bubbles that represent the other phases. These phases dont need to be necessarily be connected to the main phase, but they should be taken as source to calculate the total consumed home power, maybe as own total bubble.
This of course opens the question which source-drain bubble is connected with whom, but this could be made with config parameters.

**Describe alternatives you've considered**
Open the switchbox and look the wiring. Usually you have more than one phase. A good netmeter shows you each line values.

**Comment by flixlix** [comment]
Hey there,
although not perfect I would suggest creating one card for each phase.
I am not planning on adding three phase support (other than adding all three phases) atm to this card.
I am very sorry for the inconvenience
