### ISSUE TITLE
[FEATURE REQUEST] Line thickness as power indicator

### ISSUE THREAD

**Issue by soeffi** [flixlix/power-flow-card-plus#363]
**Is your feature request related to a problem? Please describe.**
This is a very nice card, and I do like it a lot!

Still, recognizing the power flow by visual indication with moving dots takes some time (seconds) of observing the dots flow speeds. I'd like to have a visual indication that is interpreted "on the first glance" (< 1 sec).

**Describe the solution you'd like**
Use line thickness (stroke width) between circles as additional indicator.

Pushing this even further: To indicate minimal power flow below a certain threshold: use dotted / dashed line instead of solid line.

**Comment by flixlix** [comment]
Hey, 
Thank you for your feature request.
I am not currently planning on adding any options to change the style of the line.
Currently I'm working on making this card more stable.
Still, if you want to, feel free to implement this yourself and submit a PR

**Comment by shycats** [comment]
Oh I just saw this request which is similar to mine, sorry for the duplicate. Even if it's different from the original energy distribution card, this is a very nice feature to have (like hiding the lines below a specific power threshold, it was not in the original card, but helps a lot with user experience). I understand that there are other priorities, but maybe for the future? When I have some free time to investigate how these cards are programmed, I may try to implement it myself.
