### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by matomatusov** [flixlix/power-flow-card-plus#370]
Hi,
after today's update, it is not possible to click to open the entity.

![Energy Flow Card Plus](https://github.com/flixlix/power-flow-card-plus/assets/129114957/6084cd69-ceb0-44f4-bfb9-06babd463920)

**Comment by flixlix** [comment]
Fixed.
Sorry for the inconvenience.
Will be available in the next release

**Comment by matomatusov** [comment]
Thanks for the fix.

**Comment by matomatusov** [comment]
Hi, why the same Entity is opening? They are two different entities.

![Energy Flow Card Plus](https://github.com/flixlix/power-flow-card-plus/assets/129114957/e4766b72-ebc0-4a27-8366-60ae0885f6d2)
