### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mbaldwin99** [flixlix/power-flow-card-plus#373]
**Describe the bug**
Since update v0.1.8, the line joining Grid and Battery is not visible/active, even though it should show when battery is charging from grid. Also the full grid kW is showing in the Home icon (ie the kW going to battery is being added to home consumption). This possibly explains the lack of line from Grid to Battery, as it is seeing all Grid going to Home; however the Battery icon is correctly showing the amount of kW going in to the battery. Clearer in screenshot!
Note this error does not appear on Android phone, which renders same data correctly while browser doesn't.

**To Reproduce**
1, Set battery to charge
2. Add some Home consumption
3. View in Chromebook Chrome browser - the total Grid output appears in Home, and there is no active line Grid to Battery

**Expected behavior**
1. The line between Grid and Battery should be active
2. The line between Grid and Home should be active.
4. The kW being used by Home should be shown, not the combined Battery and Home kW

**Screenshots**

**Browser Console Errors**
If applicable, add Errors from the browser console.

**Desktop (please complete the following information):**
 - OS: Chromebook
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21 Plus
 - OS: Android 13

![Screenshot 2023-09-10 00 47 58](https://github.com/flixlix/power-flow-card-plus/assets/106286061/d3b0d732-50be-4e41-a04f-1cf5f6130f75)

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [ X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [ X] I have the latest version of the card installed.

- [ X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [ X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by mbaldwin99** [comment]
Sorry, bug *does* appear on Android too, I just hadn't refreshed it, after which same bug appeared.

**Comment by flixlix** [comment]
Fixed, will be available in the next version
