### ISSUE TITLE
[BUG] Grid colors changed after update

### ISSUE THREAD

**Issue by SalvatoreITA** [flixlix/power-flow-card-plus#374]
Hi, why after the last update I see the writing highlighted in white photos and no longer with the previous colors?

Version: 0.1.8:
![Screenshot_2023-09-11-17-38-05-485-edit_com android chrome](https://github.com/flixlix/power-flow-card-plus/assets/74460788/0f479cc7-14c9-48c0-9e9a-34d2c0c72a56)

Version: 0.1.7:
![Screenshot_2023-09-11-17-38-20-766-edit_io homeassistant companion android](https://github.com/flixlix/power-flow-card-plus/assets/74460788/7da626f3-d62c-43a8-bbab-65e5cbc0865b)

How can I restore the previous colors?

**Comment by flixlix** [comment]
Fixed in version 0.1.8.1 👍
