### ISSUE TITLE
Hi, why the same Entity is opening? They are two different entities.

### ISSUE THREAD

**Issue by matomatusov** [flixlix/power-flow-card-plus#379]
Hi, why the same Entity is opening? They are two different entities.

![Energy Flow Card Plus](https://github.com/flixlix/power-flow-card-plus/assets/129114957/e4766b72-ebc0-4a27-8366-60ae0885f6d2)

_Originally posted by @matomatusov in https://github.com/flixlix/power-flow-card-plus/issues/370#issuecomment-1718296351_

**Comment by flixlix** [comment]
Fixed in #380 
Will be available in the next version
