### ISSUE TITLE
Strange dot behavior in impractical edge case

### ISSUE THREAD

**Issue by Raini20** [flixlix/power-flow-card-plus#382]
**Describe the bug**
When grid input and output are set separately as the same entity, dots from PV and battery appear 

**To Reproduce**
1. Add card to dashboard
2. Set separated grid entities as the same entity
![image](https://github.com/flixlix/power-flow-card-plus/assets/68600283/6f0e1014-c735-4f79-8f94-e9f06b886fa0)

**Expected behavior**
I don't know, maybe a error sign or lock in HA that prevents selecting the same one.

**Screenshots**
Dot speed depends on power, but doesn't really make sense here. 
![image](https://github.com/flixlix/power-flow-card-plus/assets/68600283/2f75de2b-8fc4-4464-9df8-d7f97952a059)

**Additional context**
I don't need this to function properly. I don't even know why I tried, but I think it's an interesting bug.

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
Hey there,
The reason this bug is happening is that since this card is displaying power, it is impossible to be taking from the grid and exporting to it at the same time.
You probably already know this but in your use case the grid combined entity would make more sense.
