### ISSUE TITLE
graphics settings not accessible

### ISSUE THREAD

**Issue by Moussman79** [flixlix/power-flow-card-plus#384]
Bonjour les paramètres ne sont plus accessibles par l'interface graphique depuis la mise à jour de septembre 2023.

**Comment by flixlix** [comment]
From the Readme:

> ⚠️ Version 0.1 introduced the UI Editor. This Editor is currently incompatible with Card Mod. I created a PR to fix this issue, but it hasn't been merged yet. Here is the https://github.com/thomasloven/lovelace-card-mod/pull/277. Since it hasn't been merged yet, I also released a fork with the changes from the PR. Installing this Version of Card Mod you can use this card in conjunction with Card Mod. [Here is my fork](https://github.com/flixlix/lovelace-card-mod)
