### ISSUE TITLE
[FEATURE REQUEST] Adding a reverse order of battery flow

### ISSUE THREAD

**Issue by Dehumanizer77** [flixlix/power-flow-card-plus#386]
I have a Solax X3 G4 inverter which does only have one entity for the current battery charge/discharge, however the values are reversed from what power flow card plus expects (i.e. negative when the battery is discharging and positive when it's beeing charged). Would it be possible to add an option to reverse the values so that it will be displayed correctly in such case?

I might be able to do it myself and send a pull request, but I'm not sure when will I have time for this. That should be a very easy fix so if you would be able to get to it sooner than me, that would be great :-)

**Comment by flixlix** [comment]
![image](https://github.com/flixlix/power-flow-card-plus/assets/61006057/c2948713-f2c3-42d7-8090-884fd4d848c3)
This is already possible

**Comment by flixlix** [comment]
No problem, you're good :)
