### ISSUE TITLE
[SUPPORT] Disable battery circle

### ISSUE THREAD

**Issue by lacalamine64** [flixlix/power-flow-card-plus#389]
Hey there, great work with your cards @flixlix! They're awesome!

I have no battery in my home so I would like to hide the battery circle completely. Is that possible?

Regards

**Comment by flixlix** [comment]
Hey there! TYSM 🥳

You should be able to hide the battery circle by just deselecting an entity in the Battery Field.

Hope this helps!

**Comment by lacalamine64** [comment]
Hi and thanks for the fast reply.

I hadn't any entities selected in the first place.

There are also no entities selected on my Energy-Dashboard.

But I got it to disappear after selecting entities for battery, saving, removing them and saving again.

I have the same issue with energy-flow-card-plus but there the trick didn't work.
