### ISSUE TITLE
[FEATURE REQUEST] Variable width of lines and dots depending on power

### ISSUE THREAD

**Issue by shycats** [flixlix/power-flow-card-plus#390]
**Is your feature request related to a problem? Please describe.**
I think representing power with just the dot speed is not very easy to read when there are many lines.

**Describe the solution you'd like**
It would be much clearer to read if the width of the lines (and maybe dots) is also changing, so thicker lines and bigger dots means higher power, similar to how a Sankey diagram works.

**Describe alternatives you've considered**
If there is a way to change the color of the dot separately from the line, there is no need to adjust the size of the dot, as it could be visible on top of the line even if the line is thicker, although not sure how it would look aesthetically.

**Additional context**
This is a screenshot from another card that has this feature, although I modified it to also show the dots (https://github.com/reptilex/tesla-style-solar-power-card)
![image](https://github.com/flixlix/power-flow-card-plus/assets/16405677/92c22169-a29f-47da-b0c6-bbc3263a8ddb)

**Comment by flixlix** [comment]
Since changing the width of the lines would make the overall design not fit with the original energy distribution card, this feature unfortunately falls outside of the scope of this card.
