### ISSUE TITLE
[SUPPORT]  Home power always shows zero but graph displays correctly

### ISSUE THREAD

**Issue by Ron-ski** [flixlix/power-flow-card-plus#394]
I'm using v0.1.8.1, but I think its always shown zero, odd thing is if I click the icon the graph displays correctly, as does the value for the house load - can be seen bottom left of the below picture.

![image](https://github.com/flixlix/power-flow-card-plus/assets/84545500/6227fcd6-b9bc-4641-a256-94737b0f8ec2)

Any idea's please or any further info you need?

**Comment by Yorkie71** [comment]
You might want to check the [Home object configuration](https://www.warmup.co.uk/underfloor-heating/products/thermostats/4ie-smart-wifi-thermostat) as the description states that by default the values are not shown from the entity unless clicked and by default, the value is calculated by the other entities so you may want to check those. There is an option for an "override state" but you may want to get the calculated value working as it tends to be more accurate. HTH.

**Comment by Ron-ski** [comment]
@Yorkie71 Thank you for the reply.

I presume your link should point to https://github.com/flixlix/power-flow-card-plus#home-configuration instead of a rather nice looking thermostat.

You're suggestions got me thinking, and I realised the battery power flow was the wrong way around - this can be seen in the picture above. There is an option to invert state for the battery, and that did the trick.

Thanks

**Comment by Yorkie71** [comment]
@Ron-ski Oh yes. Sorry about the incorrect link. You're presumption was correct.

A clipboard error on my part. I have been searching for an UFH thermostat which would replace the one I have and which I can hook into HA. That could have been awkward! Glad you got it sorted.

**Comment by Ron-ski** [comment]
@Yorkie71 Yes it could have been, I've done the same myself in the past, I'm sure a lot of people have. Mainly posted the link for others in case they come across this thread in the future. Thanks.

**Comment by sNiXx** [comment]
> You're suggestions got me thinking, and I realised the battery power flow was the wrong way around - this can be seen in the picture above. There is an option to invert state for the battery, and that did the trick.

I stumbled over the same thing and I am wondering if it could be helpful to rename the fields @flixlix?
- consumption -> discharge
- production -> charge
