### ISSUE TITLE
[FEATURE REQUEST] Hide Lines

### ISSUE THREAD

**Issue by MattiaFontanaErrepinet** [flixlix/power-flow-card-plus#395]
**Is your feature request related to a problem? Please describe.**
You can add a way to hide some lines if the value is 0

**Describe the solution you'd like**
If the value is 0 it is hidden or becomes grey

**Describe alternatives you've considered**

**Additional context**

**Comment by flixlix** [comment]
This is already possible with the display_zero_lines object.
