### ISSUE TITLE
[FEATURE REQUEST] Second external source with sum ball.

### ISSUE THREAD

**Issue by Thomansky** [flixlix/power-flow-card-plus#398]
Hello! First of all, a big thumbs up for this cool project. It works really well, and I've been using it for quite some time now. However, I have a request or a feature that I miss. Could you please add the option to select a second production source? Then, you could calculate the sum of both sources with a toggle switch below. This would be especially useful when, for example, using a solar panel system in combination with a generator. I've attached a screenshot below to illustrate what I have in mind.
![IMG_1540](https://github.com/flixlix/power-flow-card-plus/assets/73141171/677b37cc-ee53-49b2-955a-b8e89b06bae1)

**Comment by flixlix** [comment]
Hey there, I would love to implement this feature, but I expect a lot of time effort to do so and I can't currently justify it. (especially difficult with the lines connecting the dots).
For that reason I will close this and all further issues relating to this as not planned
