### ISSUE TITLE
[FEATURE REQUEST] Concept other than `HOME`

### ISSUE THREAD

**Issue by magiva** [flixlix/power-flow-card-plus#399]
**Is your feature request related to a problem? Please describe.**
do we have to have a concept of home ?
i want to monitor solar production in my greenhouse with battery consumption etc

**Describe the solution you'd like**
i want to be able to monitor solar production of things without a home concept, eg greenhouse, farm etc

**Describe alternatives you've considered**
i tried renaming home to greenhouse but name is not a property or is not recognised, it stays as 'home'

**Additional context**

**Comment by flixlix** [comment]
You can simply change the name and the icon on home, should be easy, weird that it doesn't work on your end.
Can you send me the code you tried using?

**Comment by magiva** [comment]
i think it came down to refresh, id saved it as not working and then shift refreshed the browser for something else and this refreshed as it should.
