### ISSUE TITLE
Battery Level for individual

### ISSUE THREAD

**Issue by splitbrain** [flixlix/power-flow-card-plus#40]
Like many others probably, I've added my electric car as one of the individual entries. It would be great if I could add a second entity for the current battery level. The percentage could be shown above the icon, just like for solar batteries.

**Comment by flixlix** [comment]
This was added in one of the last versions. You can use the `secondary_info` option for this use case.

**Comment by flixlix** [comment]
Check https://github.com/flixlix/power-flow-card-plus#secondary-info-configuration for more information
