### ISSUE TITLE
Another source as generator.

### ISSUE THREAD

**Issue by mirkokrajco** [flixlix/power-flow-card-plus#407]
Please, can you add another source, for example a power generator ???

Thank you.

   MK.

**Comment by flixlix** [comment]
Hey, this is already possible using the https://github.com/flixlix/power-flow-card-plus#power-outage config with the `entity_generator`.
This is only used when there is a power outage.
I do not plan on implementing a generator that runs in normal circumstances

**Comment by bluegumcity** [comment]
@flixlix Why not add a generator that runs in normal circumstances? I am completely off-grid and sometimes there isn't enough sun to charge the batteries, so the generator kicks in. This is not a power-outage as the PV power continues to work together with the generator.
