### ISSUE TITLE
[FEATURE REQUEST] Add water as an extra entity

### ISSUE THREAD

**Issue by Chris909090** [flixlix/power-flow-card-plus#417]
Hi,

it would be nice to have an extra place to show the usage of water. It woild be nice to look in Power Flow Card. :)

Greetings

**Comment by flixlix** [comment]
You can achieve this by simply changing the unit of your individual device

**Comment by Chris909090** [comment]
Yes thats rigth but if it was extra I will have two individiuals. If I use one individual for water there is only one free.

**Comment by flixlix** [comment]
Multiple individual devices have been requested multiple times, I am developing this, but it may take quite some time to release.

**Comment by Chris909090** [comment]
Yes I saw that. This would be really great. :)

I just thinking an extra part for water also would be nice. ;)

Thanks for coding. :)
