### ISSUE TITLE
[SUPPORT] Negative values are presenter as 0

### ISSUE THREAD

**Issue by pretori** [flixlix/power-flow-card-plus#435]
I’m using the secondary information to display my house temp and outside temp. Now when it’s -7degrees Celsius outside the card displays zero. Have I configured wrong or is it a bug.

![IMG_5498](https://github.com/flixlix/power-flow-card-plus/assets/80861039/e46b0bd4-6dd2-4f12-84ab-e6eaf4bf5aab)
![IMG_5499](https://github.com/flixlix/power-flow-card-plus/assets/80861039/a47778c0-e788-437a-8419-715788415e7d)

**Comment by langchr86** [comment]
I also have the same use case with the same problem. I assume this is a result of the "zero value" detection. Maybe we need a option flag to completelly disable this feature.

**Comment by test2a** [comment]
yeah. same thing here. i have a problem that i have solar production and home consumption but no grid. grid is to be calculated. the card assumes the other way around. it assumes solar + grid = home.

when i tried to change the labels of home and grid, the "home" showed 0 when it should have negative values like grid does.

**Comment by flixlix** [comment]
Already implemented this. Might get used in the next release.
https://github.com/flixlix/power-flow-card-plus/pull/411
