### ISSUE TITLE
[BUG] Devcontainer does not build

### ISSUE THREAD

**Issue by f-bro** [flixlix/power-flow-card-plus#436]
**Describe the bug**

When building the devcontainer I get the following error in the postCreateCommand `sudo container install`:
`ERROR: The package 'homeassistant' requires a different Python: 3.10.4 not in '>=3.11.0'`

With `container install` the latest `dev` version of Home Assistant (2024.1.0.dev0) is installed, which requires Python 3.11. The Python version in the devcontainer is 3.10.4. Python 3.10 is only supported up to Home Assistant 2023.7.x. Home Assistant 2023.8 requires Python 3.11.

I was able to use the devcontainer by setting the Home Assistant version to 2023.7.3 (`container set-version).`

As the used devcontainer `ghcr.io/ludeeus/devcontainer/generic:latest` and the `container` CLI are marked as deprecated ([ludeeus/container](https://github.com/ludeeus/container)), newer Python versions will not be support. The new proposed solution is as in [integration_blueprint](https://github.com/ludeeus/integration_blueprint).

I will try to setup a devcontainer as suggested in [integration_blueprint](https://github.com/ludeeus/integration_blueprint) and create a pull request.

**To Reproduce**
1. Clone the repo
2. Open the folder in VSCode
3. Build the devcontainer in VSCode

**Expected behavior**
I expected a functioning development environment within the devcontainer.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode: 1.84.2
 - Docker Desktop: 4.25.2
 - Docker Engine: 24.0.6

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
hey there, atm I'm only using the script `pnpm watch` as defined in the package.json.
I might remove the .devcoontainer directory to avoid further confusion. Thank you for your understanding.

Feel free to create a PR where you fix the current situation :)
