### ISSUE TITLE
[BUG] Total home consumption wrong with secondary solar

### ISSUE THREAD

**Issue by suaveolent** [flixlix/power-flow-card-plus#442]
**Describe the bug**
Power flow card plus calculates the total home consumption wrongly when two solar systems are connected:

My setup:
- Combined power meter (one entity for consumption and production)
- Two separate solar systems

In the uploaded screenshot, total home consumption should be:

(1,71+0,549)-1,44 = 0,819 kW

However, it only calculates: (1,71)-1,44 = 0,27 kW

**To Reproduce**

Configure one power meter (with positive and negative values) and two separate solar systems.

**Expected behavior**
The secondary value should be used to calculate total home consumption.

**Screenshots**
<img width="405" alt="Screenshot 2023-12-15 at 10 39 06" src="https://github.com/flixlix/power-flow-card-plus/assets/2163625/3985a7d9-f869-4f7f-b6db-c5b6587315cc">

**Browser Console Errors**
n.a.

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: any

**Smartphone (please complete the following information):**

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
Hey there, this is the expected behavior, since this card does not officially support multiple solar sources. The secondary_info is only there for display and doesn't get accounted for any calculations with other nodes. 

You could however override the home state using the `override_state` option in the home object and create your custom power sensor that implements this calculation itself.
