### ISSUE TITLE
[FEATURE REQUEST] 3-phase grid support

### ISSUE THREAD

**Issue by LeoGitGud** [flixlix/power-flow-card-plus#446]
Hello! Awesome card, good work!
Unfortunately, I have a little issue...

**Is your feature request related to a problem? Please describe.**
Our energy grid is 3-phase 230/400V. I am using a Shelly 3-EM energy meter to show my power consumption in Home Assistant. The integrated Energy Flow Card automatically adds up the energy over all phases in the bubble. For this card, I can only select one of the phases of the 3-EM to display. 

**Describe the solution you'd like**
An integrated method to add more than one entity / phase to sources (and possibly consumers) and use their sum as well as the option to see them seperately (i.e. if you have a single phase PV system so it is possible that you use power from the grid on phases 1 and two while you are pushing power into the grid on phase 3)

**Describe alternatives you've considered**
For now I have made a Helper in HA that sums up the power of the three phases and used it as the Grid entity for PFCP, which works for showing the total power drawn from / pushed to grid, but if you push power to the grid, this is only seen as decreased consumption.

**Additional context**
This is how it could look for grid (quick photoshop, hope it gets the point across)
![227789815-41f15dd4-3d24-4eb8-96ca-c7f7f01a4f46](https://github.com/flixlix/power-flow-card-plus/assets/152031847/d47cd3b5-1421-4bb9-9150-f51358868e80)

Thank you.

**Comment by flixlix** [comment]
Hey there, thank you for suggesting this!

Unfortunately I don't think there is enough space in the bubble for three phases. 
Other issues arise such as:
- what about the flows (lines & dots next to the circle)? do they use the summed up power? only the first phase?
- what about the `secondary_info` field?

I would love it if this card could fit all needs, but I only have limited time to implement things, and want to focus on things that benefit the most amount of people (I know three phase systems are not that rare, just saying I unfortunately currently don't have the time to think of or implement this)

I hope you can understand, but I don't plan on implementing this feature anytime soon.
If you have some programming knowledge, feel free to do this yourself, I will happilly review your PR :)
