### ISSUE TITLE
[FEATURE REQUEST] Parallel Energy Inputs

### ISSUE THREAD

**Issue by Borilu** [flixlix/power-flow-card-plus#449]
It would be great to display more than just "Solar".
There could be mor than one PV systems or one PV system and one combined heat and power plant.

**Comment by ChristopheVersieux** [comment]
+1 to that request
People using Ecoflow Powerstream have 2 solar inputs

**Comment by andiweli** [comment]
+1 here too
Using Zendure for "Battery" and would use on of the "Individual" for my Powerstream + Battery.
Dot moves, but amount of Watts is not subtracted in "Home" - as well as the color doesn't add up.

**Comment by NRGizzer** [comment]
+1

**Comment by ey-jo** [comment]
> +1 here too Using Zendure for "Battery" and would use on of the "Individual" for my Powerstream + Battery. Dot moves, but amount of Watts is not subtracted in "Home" - as well as the color doesn't add up. So a second battery (or solar input since EcoFlow can't divide between Solar/Battery power) would be great to have.

I set my second battery to Individual, charging is working, but discharging is not displayed or calculated. Would like to see power flow in both directions in Individual.

**Comment by Rollocko** [comment]
+1

**Comment by kevingruesser** [comment]
+1

**Comment by ChristopheVersieux** [comment]
Is thata duoplicate of this? https://github.com/flixlix/power-flow-card-plus/issues/398

**Comment by flixlix** [comment]
as @ChristopheVersieux mentioned this is a duplicate of #398
