### ISSUE TITLE
Battery Discharge dot speed

### ISSUE THREAD

**Issue by Dave-Parry** [flixlix/power-flow-card-plus#450]
I have an issue where when discharging to the grid at full power (2600 kWh) the dot speed stays slow. All other dots speed up, such as charging from the grid to the battery but not the battery to grid one. How can this be fixed?

**Comment by flixlix** [comment]
Hey, can you send me your config?

**Comment by Dave-Parry** [comment]
￼
Regards
David Parry
***@***.***

**Comment by flixlix** [comment]
Unfortunately I only see this 
![image](https://github.com/flixlix/power-flow-card-plus/assets/61006057/cb999c6a-9c2e-4859-b9bf-98ac8b5c7dac)

**Comment by Dave-Parry** [comment]
type: custom:power-flow-card-plus
entities:
  battery:
    icon: mdi:battery-50
    color_circle: true
    color_icon: true
    display_state: two_way
    invert_state: false
    entity: sensor.givtcp_sa2244g426_battery_power
    color_value: true
    state_of_charge_unit_white_space: true
    use_metadata: false
  grid:
    color_icon: true
    color_circle: true
    display_state: two_way
    color_value: true
    color:
      consumption:
        - 181
        - 26
        - 0
      production:
        - 150
        - 211
        - 95
    invert_state: true
    entity: sensor.givtcp_sa2244g426_grid_power
  solar:
    display_zero_state: true
    color_value: true
    color_icon: true
    color:
      - 255
      - 252
      - 65
    icon: mdi:solar-panel-large
    invert_state: false
    entity: sensor.givtcp_sa2244g426_pv_power
  home:
    entity: sensor.givtcp_sa2244g426_load_power
clickable_entities: true
display_zero_lines:
  mode: show
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 0.75
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000
transparency_zero_lines: 0

Is this ny better?
Regards
David Parry
***@***.***

**Comment by flixlix** [comment]
Yes, thank you.
I'll check it out

**Comment by flixlix** [comment]
Unfortunately I can't replicate this issue.
Can you send me a screen recording?


https://github.com/user-attachments/assets/66945a88-8ed8-460b-bd61-d66c37928b8e


I'll close this issue for now because I can't replicate it

**Comment by Dave-Parry** [comment]
Here is a screen recording.
￼
Regards
David Parry
