### ISSUE TITLE
[SUPPORT] Error when totaling the accumulated solar energy.

### ISSUE THREAD

**Issue by isabido** [flixlix/power-flow-card-plus#451]
I have detected that when the inverter is turned off at night the energy meter measurement is interrupted, and causes the CARD totalizer to be incorrect.

The standard energy CARD integrated into Homeassistant works correctly.

In this image you can see what is happening with the entity, and what causes a malfunction.

![image](https://github.com/flixlix/power-flow-card-plus/assets/559650/1e94d172-fa70-4820-bd5e-d17149177307)

**Comment by flixlix** [comment]
Hey there, this card is only for power, it does not support energy. Thank you for understanding
