### ISSUE TITLE
Disable moving dots

### ISSUE THREAD

**Issue by DJerike** [flixlix/power-flow-card-plus#452]
I use a samsung galaxy tab A7 ad a wall tablet for home assistant, i use fully kiosk browser to display home assisistant.
The problem i am facing is that the rendering of the moving dots takes so much cpu use load that the animation of the dots is choppy and it totally slows down the page.

I googled to resolve the problem, and found this post:
https://github.com/home-assistant/frontend/issues/13816

Is it possible to make a yaml option so i can disable the moving dots ?
It would make my tablet so more usable.

I already had to take some cards of my dashboard because when i have them on my dashboard it is totaly not working and hangs the system what fully kiosk browser detects and reboots the browser.

**Comment by The-H23** [comment]
I have the same issue here. I use a WebSlice at my KDE plasma desktop and the animation of the moving dots causing a really high load on my machine.

**Comment by flixlix** [comment]
See this issue: https://github.com/flixlix/power-flow-card-plus/issues/358
This CPU load is caused by the built in svg animations in HTML, so I can't do anything about them.

I can create a global config option to disabled them altogether, though

**Comment by DJerike** [comment]
That would be great, thanks

**Comment by flixlix** [comment]
Implemented the feature, should be available in the next release! 🥳

**Comment by Guenni9** [comment]
Hi, maybe, could this help?
[https://fjorge.com/insights/blog/can-svg-animations-use-less-cpu/#:~:text=For%20animated%20SVGs%2C%20this%20fall,up%20like%20a%20bacon%20griddle.](url)

**Comment by kivster** [comment]
I have the same issue with the dots and have had to disable them. Problem is I think the dots really complete the overall aesthetic. Is there any way to reduce the load these svg elements have on the system?

**Comment by Onepamopa** [comment]
Instead of using moving dost - just display static arrows showing the "direction of the flow" - problem solved, no high cpu usage.
That is, if the dev actually wants to address the issue.
