### ISSUE TITLE
[BUG] secondary_info displays as 0 if negative

### ISSUE THREAD

**Issue by ffrog8** [flixlix/power-flow-card-plus#466]
**Describe the bug**
secondary_info displays as 0 if entity value is negative

**To Reproduce**
add a secondary_info entity who's value is negative

**Expected behavior**
Display the negative  value

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X ] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [ X] I have the latest version of the card installed.

- [X ] I have cleared my browser cache **after** installing, updating and configuring the card.

- [ X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
Already implemented this in https://github.com/flixlix/power-flow-card-plus/pull/411
I'll try to get it working on the next release

**Comment by ffrog8** [comment]
:) excellent!

**Comment by flixlix** [comment]
Fixed in v0.2.0 :)

**Comment by ffrog8** [comment]
It sure is! Cheers!
