### ISSUE TITLE
[BUG] Individual Entities Don't Display Switch in Secondary Info

### ISSUE THREAD

**Issue by jbrownza** [flixlix/power-flow-card-plus#467]
**Describe the bug**
The secondary info on the Individual Entities are no longer able to the display the state of a switch. In my specific instance, I have water heaters with smart switches that are turned off when solar production is low. The water heaters have power monitoring smart switches which are configured as Individual Entities. I was displaying the switch on/off state as the secondary info of the Individual Entities. When testing, the "main" Grid, Solar, Battery and House Entities are able to display an on/off state on secondary info.

**To Reproduce**
1. Add on Individual entity which something such as power usage (eg: entity: sensor.geyser_kitchen_energy_power)
2. Add a switch entity in the secondary info (eg: entity: switch.geyser_kitchen)

For example:
```
  individual:
    - entity: sensor.geyser_kitchen_energy_power
      name: Kitchen
      secondary_info:
          entity: switch.geyser_kitchen
```

**Expected behavior**
The on/off state of the switch should be displayed as secondary info

**Screenshots**
This is the expected behaviour
![2024-01-17_00-03-31](https://github.com/flixlix/power-flow-card-plus/assets/95254204/1c249914-c9b3-454b-b3cd-a792f6ca55b0)

**Browser Console Errors**
None

**Desktop (please complete the following information):**
 - Windows
 - Brave
 - v1.61.116 (Chromium to 120.0.6099.217)

**Smartphone (please complete the following information):**
None

**Additional context**
None

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by xkill** [comment]
Hi, seems that the lines between the grid and home are displayed in a wrong position when two or more devices are added. See attached images.
![OK with only one device](https://github.com/flixlix/power-flow-card-plus/assets/208463/1cbfc58b-a5ab-4686-8606-271158bac1f8)
![Broken with two devices](https://github.com/flixlix/power-flow-card-plus/assets/208463/ab1d9232-9e5d-49cb-956b-96075a1d7d04)
![Broken with multiple devices](https://github.com/flixlix/power-flow-card-plus/assets/208463/34a2a878-d665-408f-a3f6-1b6d4e02d2b2)

**Comment by flixlix** [comment]
@xkill this was already fixed and will be available in the next version of the card. Please don't post unrelated issues in another issue
