### ISSUE TITLE
[BUG] display_zero_lines -> No feed into the grid

### ISSUE THREAD

**Issue by skyx3** [flixlix/power-flow-card-plus#469]
If I set "display_zero_lines" to hide. I no longer see any production into the grid.

`display_zero_lines:
  mode: hide`

![grafik](https://github.com/flixlix/power-flow-card-plus/assets/58375274/23549d39-7427-4c90-8b69-2cae929a2457)

`display_zero_lines:
  mode: show`

![grafik](https://github.com/flixlix/power-flow-card-plus/assets/58375274/ceff35b6-03f2-4999-8aa2-7606a1684b25)

**Comment by flixlix** [comment]
Hey there, can you try using a sensor with a positive state in the grid export field?
I think that is the issue

**Comment by skyx3** [comment]
That was is it. Thank you :-)
