### ISSUE TITLE
[BUG] Individuals not showing entities

### ISSUE THREAD

**Issue by ilmisu** [flixlix/power-flow-card-plus#471]
**Describe the bug**
Even if I copy from the example configuration the individuals (I'd like to instance 3) the card is showing none of them.

**To Reproduce**

`type: custom:power-flow-card-plus
entities:
  battery:
    entity: sensor.potenza_batteria_invertita
    state_of_charge: sensor.zcs_inverter_soc_batteria
  solar:
    entity: sensor.zcs_potenza_generata
    display_zero_state: true
    color_value: false
    color_icon: true
    use_metadata: false
    invert_state: false
  home:
    entity: sensor.solarman_activepower_load_sys
    icon: ''
  grid:
    entity: sensor.potenza_prelevata_ist
    name: Rete
  individual:
    - entity: sensor.potenza_elettrodomestici_ist
      icon: mdi:washing-machine
      name: Elettrodomestici
    - entity: sensor.potenza_prese_abitazione
      icon: mdi:power-plug
      name: PreseAb
    - entity: sensor.induzione_potenza_istantanea
      icon: mdi:induction
      name: Induzione
clickable_entities: true
display_zero_lines:
  mode: show
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 2
min_flow_rate: 0.75
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 10000
transparency_zero_lines: 0`

**I don't know why I couldn't paste the code properly, please help.**

**Expected behavior**
the entity below zero consumption should be shown into card.

**Screenshots**
![image](https://github.com/flixlix/power-flow-card-plus/assets/50550633/05153903-a09a-4a72-83fe-b97162864b5e)

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser Chrome
 - Version last

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
Hello there, this feature is only available in the beta 0.2.0

Forgot to write it in the readme

**Comment by ilmisu** [comment]
> Hello there, this feature is only available in the beta 0.2.0
> 
> Forgot to write it in the readme

alright, so the only way is to switch to beta or wait the release containing this feature?

**Comment by flixlix** [comment]
Yes, unfortunately.
Luckily I think it won't take too long until v.0.2.0 is released.

**Comment by souhl** [comment]
Hm.. I have v0.2.0 installed, but its still missing.

**Comment by flixlix** [comment]
Do the entities have any value, or just 0?
Please try  using your solar entity as an individual, just to check if the dot starts showing

**Comment by souhl** [comment]
Yes, that worked. So, how do I show entitites with zero value?

<img width="496" alt="Screenshot 2024-01-24 at 10 46 55" src="https://github.com/flixlix/power-flow-card-plus/assets/5879835/a0f80adf-db39-430a-a8ee-67b288c5f79d">

**Comment by flixlix** [comment]
use `display_zero: true` in the individual config.
more info here: https://github.com/flixlix/power-flow-card-plus?tab=readme-ov-file#individual-configuration

**Comment by souhl** [comment]
Ah, its set in the gui, but not shown in the config. When adding it manually to the config it works. thx

**Comment by flixlix** [comment]
yes thats expected.
I'm glad it worked out
