### ISSUE TITLE
[FEATURE REQUEST] Scaling

### ISSUE THREAD

**Issue by abbottcam** [flixlix/power-flow-card-plus#474]
Would it be possible to enlarge the card. Ive the option the make it full size. But could there be an option for a custom width and height?

Thanks

**Comment by flixlix** [comment]
Hey, you can use custom css for this
<img width="842" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/61006057/6d0a65b3-800d-44ee-a4cf-fa591226b7bb">
