### ISSUE TITLE
Energy Consumption should be shown in Wh or kWh

### ISSUE THREAD

**Issue by TheSmartGerman** [flixlix/power-flow-card-plus#475]
I just realised, all consumptions are only shown in kW. Compared to the "normal" power chart in "kWh". 

![image](https://github.com/flixlix/power-flow-card-plus/assets/9676982/18346f82-f51f-4204-9d5d-cc4c006a9dc1)

![image](https://github.com/flixlix/power-flow-card-plus/assets/9676982/93c92e4e-6aa9-4a32-aaaa-145aeeee057f)

This should be fixed. If you use current production as secondary information, you can't differ between current energy and energy consumption.

**Comment by flixlix** [comment]
This is a card for displaying power and as such the units kW and W are correct. Check the energy flow card plus for an energy card
