### ISSUE TITLE
Weird calculation one "home"

### ISSUE THREAD

**Issue by Erisvaenget27** [flixlix/power-flow-card-plus#480]
Hi guys, 

I think this is a bug - if not, please enlighten me on the reasoning behind. 

Picture 1 is showing a "hjem" consumption of 929w
Picture 2 is showing, when I click the "hjem" entity the real consumption of 480w

My battery is charging with what appears to be the difference between 929-480 = 449w in which my solar panels are producing. 

The "home" should not show anything BUT the home consumption as it per definition is perceived as such. 

Is it a fault40 or is this a bud?

![1](https://github.com/flixlix/power-flow-card-plus/assets/90946478/d66ea36e-1e37-4224-9dbc-8e0ca2efc112)
![2](https://github.com/flixlix/power-flow-card-plus/assets/90946478/97b60d4a-54aa-4569-a0e0-0bdd932791c4)
![3](https://github.com/flixlix/power-flow-card-plus/assets/90946478/53b4b448-e131-4b58-9432-9bbb2eef7239)

Thanks

**Comment by flixlix** [comment]
Seems to be working fine:

`439,9W` (grid) **-** `430W` (battery) **=** `9,9W` (rest)

`920W` (solar) **+** `9,9W` (rest) **=** `929,9W` (home)

Not sure how your home setup is showing otherwise
