### ISSUE TITLE
[BUG] Beta 2 version of power flow card not rendered on android 5.0 tablet

### ISSUE THREAD

**Issue by snigehere** [flixlix/power-flow-card-plus#487]
**Describe the bug**
I installed 0.2.0 Beta and altered the config to match the new design.  The card renders ok on all my devices except the old tablet I use as a display which runs android 5.0. and fully kiosk 

**To Reproduce**
Install 0.2.0 beta
1. clear cache in my browser and in fully kiosk 
2. card does not render. 
3. Switch to edit - the card location is shown with the menu but no content.
4. I am able to edit the card on the tablet and the configuration page displays correctly but saving the card does not change the situation
5. I have also power cycled the device
6. Reinstall 1.8.1 and display is then rendered (but individual items not displayed due to config changes
7. I have tried adding a card and just putting in power and solar but no change 

**Expected behavior**

**Screenshots**

**Browser Console Errors**
If applicable, add Errors from the browser console.

**Tablet (please complete the following information):**
 - OS: Android
 - Browser fully kiosk (chrome is default browser on the device)
 - Version 5

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by snigehere** [comment]
So a bit more digging - this seems to be an issue for the chrome browser 95.0 and fully kiosk 1.54.1-play but renders ok with firefox 122.0.1 on the device.

I am unable to upgrade chrome any further because there is no more support for android 5.  Fully kiosk is at the latest level for the android version (not sure if there are later versions for later versions of android.

Not playing well with fully kiosk is an issue for me.....

**Comment by Guenni9** [comment]
Maybe it could help @flixlix to resolve this:

Fully Kiosk Browser gives following in the web-console with Web-View 90.0.4430.91 on a Firetab 10 and only with Beta 2:

`11:10:56.841 -- [ERROR] Uncaught (in promise) ReferenceError: structuredClone is not defined -- on line 1 of http://192.168.0.30:8123/hacsfiles/power-flow-card-plus/power-flow-card-plus.js?hacstag=618081815020`

With the [v0.1.8.1] it works fine and no errors in the web-console from Fully-Kiosk. 

After updating Web-View to newer version the card is shown. But as @snigehere said, it is sometimes not possible to update..

But be aware of the high CPU-usage https://github.com/flixlix/power-flow-card-plus/issues/144 😉

**Comment by flixlix** [comment]
@Guenni9 thank you for pointing me in the right direction. Just fixed the issue, will be available in the next version

**Comment by snigehere** [comment]
@Guenni9 @flixlix Many thanks for your help with this - I will wait the new release.

**Comment by snigehere** [comment]
Hi @flixlix - do you have a plan for the next update? I am not chasing for it to be done but just to know if there is a plan so I can keep my displays working but not miss when the update goes out.

Many thanks for your help and for sharing this great card
