### ISSUE TITLE
Secondary Info for all devices?

### ISSUE THREAD

**Issue by shadow7412** [flixlix/power-flow-card-plus#49]
I was thinking it'd be nice to be able to include secondary info on the grid bubble (in my case, the current price of electricity).

Is there something specific about individual devices that makes secondary information more viable, or could this safely be extended across all of the configurations?

**Comment by paulgee31** [comment]
Yep I'd like to add secondary info to Solar, so I can display total kWh generated.

**Comment by shammond-uk** [comment]
+1 for the secondary info on all bubbles. Would be great to be able to include cumulative day generation to solar and cumulative spend to grid.

**Comment by flixlix** [comment]
Added this feature in the latest release 🥳, closing the issue

**Comment by shadow7412** [comment]
The current implementation doesn't quite work for my usecase, as the display seems to round to the nearest integer. The cost of electricity is measured in $/kWh, meaning that it (usually) is less than 1.

Is there an easy way to either do maths on this (ie, a value template?) to bring it to c/kWh, or a means to set decimal precision? 

Honestly, the former would probably be best as it would free up the space used by the "0."

**Comment by flixlix** [comment]
You can create a template sensor that simply multiplies the state of the original sensor by 100, I guess that adding a decimals option would be another feature request
