### ISSUE TITLE
[BUG] v0.2.0beta, configuration watt_threshold doesn't work

### ISSUE THREAD

**Issue by cris88** [flixlix/power-flow-card-plus#494]
Configuration of watt_threshold to 10000, but the default 1000 is applied.

Prints attached.

![image](https://github.com/flixlix/power-flow-card-plus/assets/1536899/7618a7d5-4856-4248-8acf-44d6a010f38e)

**Comment by SalvatoreITA** [comment]
same problem, I would like the value to remain in W when exceeding 1kw, I set the watt_threshold to 9999 but nothing has changed

![Screenshot_20240211-073908_Chrome](https://github.com/flixlix/power-flow-card-plus/assets/74460788/a77ce581-2c23-497f-8fab-e09013cc5dc0)

**Comment by mx-vatte** [comment]
I can confirm this bug. I want to have always kW instead of W and therefore tried to set the threshold to 0 or 1 without any influence.

**Comment by flixlix** [comment]
Tried to fix this bug in version 0.2.0.
Can you confirm it is now working?

**Comment by SalvatoreITA** [comment]
> Tried to fix this bug in version 0.2.0. Can you confirm it is now working?

With version V0.2.0 it is back to working
![Screenshot_20240414-132457_Chrome](https://github.com/flixlix/power-flow-card-plus/assets/74460788/54695dda-491c-4e31-be51-29f7457a013f)

**Comment by flixlix** [comment]
Nice! Thank you for the feedback 🦾
