### ISSUE TITLE
[FEATURE REQUEST] Secondary Info with sensor (and template) below circle

### ISSUE THREAD

**Issue by Klagio** [flixlix/power-flow-card-plus#495]
Would like to show, for example voltage and ampere values of battery, or time remaining to full discharge. Also for electric vehicles would be useful to have additional secondary info, but it should all be outside the circle for better clarity

**Comment by flixlix** [comment]
Hi there, thank you for your suggestion.

Unfortunately I don't think I'm adding this any time soon.

Feel free to open a PR, where you implement this, but for now I'm closing this
