### ISSUE TITLE
[FEATURE REQUEST] Allow/Support negative values as secondary information

### ISSUE THREAD

**Issue by Alfred99-HA** [flixlix/power-flow-card-plus#497]
First of all, I am expressing that I am quite happy with the powerful Power Flow Card Plus! And thus its my first and most import card. Thanks a lot!

I am using temperature in some of the entities. Actually Solar shows outside temperature in Celsius and Home shows inside temperature.

However temperature with negative values is not displayed, instead 0 is displayed.

I am suggesting to support displaying negative values as well. Alternative would be to convert the value to a string and display the string. Since others might also take advantage of displaying negative values I prefer to support it natively in the card.

![image](https://github.com/flixlix/power-flow-card-plus/assets/133593172/5c5068b6-c18d-4de6-b3b4-a57813f4d37c)

BTW: as seen in the picture I am splitting total Home into two "individual" devices actually heatpump and house without heatpump. I am in favor of supporting heatpump in energy board as discussed there and later on here as well.

**Comment by flixlix** [comment]
#411 does this fix your issue?
I had implemented some time ago, just didn't merge it yet, but should be available in the next version.

**Comment by Alfred99-HA** [comment]
yes, that's it!

Thanks for your fast responce and sorry for duplication
