### ISSUE TITLE
[BUG] v02.0beta no changes for entity's are possible

### ISSUE THREAD

**Issue by sahomm** [flixlix/power-flow-card-plus#498]
**Describe the bug**
I've to implement a individual by using the individual overview an all is fine:
![Bildschirmfoto 2024-02-19 um 19 27 18](https://github.com/flixlix/power-flow-card-plus/assets/11404919/5070ef0e-62d1-4aac-83f7-4ff1bcb35c04)
Now I would like to change some informations like name or display zero and it haven't a effect:
![Bildschirmfoto 2024-02-19 um 19 29 16](https://github.com/flixlix/power-flow-card-plus/assets/11404919/4f6cd5f3-8178-4ed8-9dd0-63e9afe01270)
The Code also don't have any changes from change the she setting via GUI (no change of entries or more lines) .

If I change the code direct, it haven't any change of this behavior. Also for any other entries e.g. home in this example:
![Bildschirmfoto 2024-02-19 um 19 39 27](https://github.com/flixlix/power-flow-card-plus/assets/11404919/49aa3bef-1b10-4f55-bd98-cd1c9d7c276e)

with the no beta I don't have any problems like this.

Thanks for a response 

**To Reproduce**
see above 

**Desktop (please complete the following information):**
 - OS: HA 2024.2.2 and div OS
 - Browser chrome, safari,firefox
 - Version div

**Smartphone (please complete the following information):**

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by sahomm** [comment]
Here an update from my side about manual changes via code.
There I had a mistake about the notation. But the bug to configure via GUI still exists.

wrong way:
``` 
- entity: sensor.shelly_3em_warmepumpe_total_power
- name: Wärmepumpe
- icon: mdi:heat-pump
```

right way:
``` 
- entity: sensor.shelly_3em_warmepumpe_total_power
  name: Wärmepumpe
  icon: mdi:heat-pump
```

and it do fine, THANKS!

for example:
![Bildschirmfoto 2024-02-20 um 12 33 58](https://github.com/flixlix/power-flow-card-plus/assets/11404919/3887378b-3a8d-4da2-bd2b-e08940deee81)

Sorry about that, I think the day yesterday was to hard ;)

**Comment by flixlix** [comment]
@sahomm glad you got everything sorted :)
