### ISSUE TITLE
[BUG] left bottom individual icon not colored

### ISSUE THREAD

**Issue by bbr111** [flixlix/power-flow-card-plus#499]
Color of left bottom indiviual icon missing
**Expected behavior**

**Screenshots**
![image](https://github.com/flixlix/power-flow-card-plus/assets/46243805/d5c0d92c-e3cb-4554-87ab-4a22c606eb9a)

**Browser Console Errors**
If applicable, add Errors from the browser console.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed. *BETA*

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
Please send me your config, without it I can not help you
