### ISSUE TITLE
[BUG] s.entries is not a function. (In 's.entries()', 's.entries' is undefined)

### ISSUE THREAD

**Issue by aLimp86** [flixlix/power-flow-card-plus#503]
**Describe the bug**
Sorry to bring this up again. Probably it can be closed directly but _where can I find the solution_ for this?
If I want to edit the power-flow-card-plus in the gui mode it is not possible. The error from the title occurs. It‘s still possible to edit it with yaml, but it bothers me. 

**To Reproduce**
1. Go to the dashboard where this card is added
2. Click on 'edit‘
3. gui mode is not working

**Expected behavior**
I can edit this card with yaml code and in gui mode.

**Screenshots**
![IMG_0081](https://github.com/flixlix/power-flow-card-plus/assets/130318612/4443eee9-dfcb-4ff7-8ffa-9b3f7db0976e)

**Browser Console Errors**
N/a

**Desktop (please complete the following information):**
 - OS: it does not matter. I have it on iOS and Windows
 - Browser: all my available browsers
 - Version: does not matter.

**Additional context**
I had some cards installed which where mentioned in some other forums to cause this problem. Can‘t remember which. But they are uninstalled now.

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [ ] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
Check here https://github.com/flixlix/power-flow-card-plus/issues/441.
This bug is caused by card mod.
Either uninstall it or update it, should fix the issue when adding a new card
