### ISSUE TITLE
display "individual" with smartphone is missing rather than the same wih PC

### ISSUE THREAD

**Issue by jluc2808** [flixlix/power-flow-card-plus#505]
**Describe the bug**
when i set some device inside "individual1" i could display these one with my PC , but i there is no display with my smartpone android the individual disappears 

**To Reproduce** : always 

**Screenshots**
2 added screenshots to help explain your problem.

**Desktop :**
 - OS: [Windows 11]
 - Browser [chrome, firefox]
![power-flow-pc](https://github.com/flixlix/power-flow-card-plus/assets/3936741/bc0c78a1-2839-48b5-baf3-b6290d27f901)

**Smartphone (please complete the following information):**
 - Device: [huawei POT-LX1A]
 - OS: [android 9]
 - Browser [chrome, firefox]
![power-flow-android2](https://github.com/flixlix/power-flow-card-plus/assets/3936741/25488fd9-fc2e-45d6-8cbc-9b263616141c)

I have the latest beta version of the card installed.

I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by hmax-72** [comment]
Verified it on IOS - works fine.

**Comment by GolfOWL** [comment]
Verified on Android - bug exists 😞

**Comment by GolfOWL** [comment]
![Screenshot_20240227_071208_Home Assistant](https://github.com/flixlix/power-flow-card-plus/assets/151399998/2511a805-9c8d-4abe-b002-c49ad1f4ee4f)

**Comment by brunopiras** [comment]
Strange Issue:

Configuration:

`    type: custom:power-flow-card-plus
      right_button: CHIUDI
      style_card_content: |
        background-color: trasparent;
      title: Potenza Istantanea
      clickable_entities: true
      display_zero_lines: false
      use_new_flow_rate_model: true
      w_decimals: 0
      kw_decimals: 1
      min_flow_rate: 0.75
      max_flow_rate: 6
      max_expected_power: 4000
      min_expected_power: 1
      watt_threshold: 1000
      transparency_zero_lines: 0
      entities:
        fossil_fuel_percentage:
          entity: sensor.co2_signal_grid_fossil_fuel_percentage
          icon: mdi:pine-tree
          color_icon: true
          display_zero: false
          name: Low-carbon
        home:
          entity: sensor.green_power
          color_icon: true
          name: Casa
          icon: mdi:home-city-outline
          color_value: true
          override_state: true
          secondary_info:
            color_value: false
        solar:
          entity: sensor.inverter_lcd_pv_power
          display_zero_state: false
          name: SOLARE
          color_icon: true
          color_value: true
        battery:
          entity:
            consumption: sensor.tdt_bms_discharging_power
            production: sensor.tdt_bms_charging_power
          state_of_charge: sensor.tdt_bms_state_of_charge
          name: Batteria
          icon: mdi:home-battery
          color_icon: true
        grid:
          entity: sensor.grid_power
          display_state: one_way
          name: ENEL
          color_icon: true
        individual:
          - entity: sensor.consumo_istantaneo_inverter
            icon: mdi:swap-horizontal-variant
            color: lime
            name: Inverter
            color_icon: true
          - entity: sensor.chiller_power
            icon: mdi:air-conditioner
            color: '#80b8ff'
            name: Chiller
            color_icon: true
      dashboard_link: /energy
      dashboard_link_label: Energia`

Mac OS Safari it's showing the individual;

IOS 17.4 Safari mobile it's showing the individual;

Companion App It's not show the individual.

**Comment by flixlix** [comment]
Seems like a cache issue, can you try clearing your app cache to see if it fixes the issue for you?

**Comment by brunopiras** [comment]
> Seems like a cache issue, can you try clearing your app cache to see if it fixes the issue for you?

Thanks I did and now I see the individual!

**Comment by flixlix** [comment]
Nice 👍
I'll close this issue for now, @jluc2808 if it persists after clearing your cache, feel free to reopen
