### ISSUE TITLE
Custom position for Indiviuals

### ISSUE THREAD

**Issue by hmax-72** [flixlix/power-flow-card-plus#507]
Currently the additional entities are added above than below than to the right of Home. 
It would be nice to have the possibility to switch this to above than to the right than below (to safe vertical space on the dashboard - e.g. if there is no battery)

**Comment by flixlix** [comment]
Hey there, there is a limitation in the way the lines connect the dots that would take a very long time to implement for relatively small advantages. I am currently not planning on implementing this. Thank you for your suggestion
