### ISSUE TITLE
selectable parent for Individuals

### ISSUE THREAD

**Issue by hmax-72** [flixlix/power-flow-card-plus#508]
Would be nice to define the parent object for the indiviuals. 
This would ease the handling and reduce the amount of predefined possibilities.
e.g.: Generator connected to Grid
By sure, this is little nightmare regarding the generation of the lines......

**Comment by dm82m** [comment]
I have the same wish: https://github.com/flixlix/power-flow-card-plus/issues/404#issuecomment-1925218549

**Comment by flixlix** [comment]
This seems too complex considering the small enhancement it would bring, I'm not planning on adding it...
