### ISSUE TITLE
Permanently Animation flow?

### ISSUE THREAD

**Issue by purewhitedesign** [flixlix/power-flow-card-plus#514]
Hi!

I am using Power Flow Card Plus and the older version Power Flow Card.

In the older version it works correctly:
![dd](https://github.com/flixlix/power-flow-card-plus/assets/160245115/1e3cf973-18be-49c9-a3d1-e38dc75d0e17)
The animation goes from the battery to the house.

In PFC+ there is an animation form the solar to battery and to the house, but it's at night, so the panels doesn't work:
![11](https://github.com/flixlix/power-flow-card-plus/assets/160245115/5e49a7b3-005c-45f3-82b9-c9cf9dde37a6)

So, I thought, this could be a bug only when solar is null. But today there is an animation from/to all entities:
https://www.youtube.com/shorts/Cut3mgqiqjM
There shouldn't be a flow from the battery to the house for example.

My code:
`
- type: custom:power-flow-card-plus
    entities:
      battery:
        entity:
          production: sensor.solax_battery_current_charge
          consumption: sensor.solax_battery_power_charge
        state_of_charge: sensor.solax_battery_capacity
      grid:
        entity:
          consumption: sensor.solax_grid_import
          production: sensor.solax_grid_export
        color_value: true
        invert_state: false
        use_metadata: false
      solar:
        entity: sensor.solax_pv_power_total
        display_zero_state: true
        name: PV-Anlage
        invert_state: false
        use_metadata: true
        secondary_info: {}
        display_zero_tolerance: 0
      home:
        color_icon: true
        entity: sensor.solax_house_load
        subtract_individual: false
        override_state: true
      individual1:
        entity: sensor.solax_api_charge_added
        icon: phu:bmw
        color:
          - 0
          - 0
          - 0
        name: EV-Charger
        color_icon: true
        display_zero: true
        color_value: true
        display_zero_tolerance: 0
      individual2:
        entity: sensor.altherma_daily_heat_energy_consumption
        name: Wärmepumpe
        icon: mdi:heat-pump
      fossil_fuel_percentage:
        entity: sensor.electricity_maps_anteil_fossiler_brennstoffe_im_netz
        display_zero: true
        color_icon: true
        color_value: false
    clickable_entities: true
    display_zero_lines:
      mode: show
      transparency: 50
      grey_color:
        - 189
        - 189
        - 189
    use_new_flow_rate_model: true
    w_decimals: 0
    kw_decimals: 2
    min_flow_rate: 3
    max_flow_rate: 8
    max_expected_power: 20000
    min_expected_power: 0.01
    watt_threshold: 10000
    transparency_zero_lines: 0`

    
Thank you for helping me out!

**Comment by flixlix** [comment]
I noticed you are **exporting from & importing to** the battery in the video.

This situation is physically not possible, since power can only flow in one direction at once.

I noticed from your entities that you may be trying to display energy instead of power, if this is the case, this card does not support energy. Please use the `Energy Flow Card Plus` for this use case.
