### ISSUE TITLE
[BUG] Flow stops after 10:00 am

### ISSUE THREAD

**Issue by Davvy80** [flixlix/power-flow-card-plus#515]
The card displays everything as normal in the early hours of the day, specifically from 12:00 am to 10:00 am. However, after the highlighted flow, it no longer progresses, as shown in the videos.

Is there something I need to fix?
Thanks to everyone for the collaboration.

https://github.com/flixlix/power-flow-card-plus/assets/130129774/ab8f63d9-be6f-4876-b1f7-b4191983772f

https://github.com/flixlix/power-flow-card-plus/assets/130129774/d9112a36-ede6-4a1e-b58a-16b57714b92c

My code:

type: custom:power-flow-card-plus
entities:
  grid:
    entity:
      '0': '['
      '1': o
      '2': b
      '3': j
      '4': e
      '5': c
      '6': t
      '7': ' '
      '8': O
      '9': b
      '10': j
      '11': e
      '12': c
      '13': t
      '14': ']'
      consumption: sensor.foxess_grid_consumption
      production: sensor.foxess_energy_generated
    display_zero_tolerance: 1
    display_state: two_way
    invert_state: true
    use_metadata: false
    name: Rete
    icon: ''
    secondary_info:
      entity: sensor.foxess_feedin
      unit_of_measurement: Kwh
      color_value: true
    color_value: true
    color_icon: true
  solar:
    entity: sensor.foxess_solar_power
    color_value: true
    color_icon: true
    display_zero_state: false
    display_zero_tolerance: 0.5
    invert_state: false
    use_metadata: false
    name: Produzione
    icon: mdi:solar-power-variant
  battery: {}
  fossil_fuel_percentage:
    name: Eco
    color_value: true
    color_icon: true
    display_zero: true
    display_zero_state: true
    unit_white_space: true
    use_metadata: false
    icon: mdi:pine-tree
    display_zero_tolerance: 0.5
    state_type: percentage
    entity: sensor.electricity_maps_percentuale_della_rete_di_combustibili_fossili
    secondary_info:
      entity: sensor.electricity_maps_intensita_della_co2
      color_value: true
      unit_of_measurement: W
      display_zero_tolerance: 0.5
  home:
    entity: sensor.foxess_load
    subtract_individual: true
    override_state: true
    use_metadata: true
    color_icon: true
    color_value: true
    icon: mdi:home-account
    name: Consumato
    secondary_info:
      entity: sensor.foxess_load_power
      color_value: true
      decimals: 2
      icon: ''
      template: ''
      unit_of_measurement: kwh
      display_zero: false
      display_zero_tolerance: 0.5
      unit_white_space: false
display_zero_lines:
  mode: show
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189
kw_decimals: 1
clickable_entities: true
use_new_flow_rate_model: true
w_decimals: 1
watt_threshold: 10000
min_expected_power: 1
max_expected_power: 6.6
max_flow_rate: 10
min_flow_rate: 2

**Comment by flixlix** [comment]
Hey there, I noticed your grid is exporting and importing at the same time. This is not physically possible.

I imagine you are trying to display energy, which is not supported by this card. For this, please use the `Energy Flow Card Plus`.
