### ISSUE TITLE
Zero Tolerance for grid?

### ISSUE THREAD

**Issue by shiner66** [flixlix/power-flow-card-plus#52]
Hi,
I tried to implement it myself but my coding skills suck.
It would be very handy to have the possibility to use the Zero tolerance feature also for grid sensors, as with grid-tied inverters, there is always a bit of a push and pull between the grid and the home to keep voltages in sync, but it's annoying to see those 5-10 watts pushed back and forth.
I think it would be much more pleasant to just have the choice to not display the grid energy below a certain threshold.

**Comment by flixlix** [comment]
I like this idea as this also applies to my setup, where the battery is always trying to correct for the grid's power. I'll add this to my to-do list

**Comment by shiner66** [comment]
I also compiled my own fork, but I must have screwed something up as the string doesn't have any impact on grid after editing, I'll wait for the master 😗

**Comment by flixlix** [comment]
Added this feature! Will be available in the next release 😊 #64
