### ISSUE TITLE
[FEATURE REQUEST] Battery SOC - Hide percentage

### ISSUE THREAD

**Issue by david-rapan** [flixlix/power-flow-card-plus#520]
**Is your feature request related to a problem? Please describe.**
No it's not.

**Describe the solution you'd like**
Simple switch for hiding percentage value of Battery SOC when the entity is set. (While still having "metadata", being able to click the icon, etc.)

**Comment by flixlix** [comment]
implemented in #545 
will be available in 0.2.1
