### ISSUE TITLE
[BUG] Line displaying power flowing from the solar during 0W production

### ISSUE THREAD

**Issue by david-rapan** [flixlix/power-flow-card-plus#523]
**Describe the bug**
During times with 0W from solar when there is sudden power flow back to the grid the card is displaying it as if it was from the solar (top-left line) instead of the battery (bottom-left line). It would presumably apply also to the state where the amount of power flowing back to the grid is higher than power produced from the solar.
_I understand that it's just a minor visual inconvenience but visual side of a thing is the main purpose of this addon, right?_

**To Reproduce**
_It does not happen that often so reproducing is just about catching described conditions._

**Expected behavior**
Being also able to display power flowing back to the grid from the battery.

**Screenshots**
![power_infographics_violet_error](https://github.com/flixlix/power-flow-card-plus/assets/161127373/0f443caf-04c2-4042-b190-60d2bd1541cb)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 122.0.2365.92

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**
- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).
- [X] I have the latest version of the card installed.
- [X] I have cleared my browser cache **after** installing, updating and configuring the card.
- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
Thank you for leaving a bug report!

By default on this card, if battery and solar are exporting, the solar part goes to the grid first, this is expected behaviour (in reality it is probably a mix of both)

I'm not sure one is more correct than the other, so for now I'll leave it as is.
