### ISSUE TITLE
Flow line color not showing

### ISSUE THREAD

**Issue by commandermatz** [flixlix/power-flow-card-plus#524]
**Describe the bug**
Flow line for Individual 1 is not showing properly. Stays gray, no matter what it was set to.
All other Individuals work properly.
Switching Individuals, No1 stays faulty.

![Screenshot 2024-03-25 13 42 54](https://github.com/flixlix/power-flow-card-plus/assets/100285050/2da30bb4-99b3-4804-af4f-8a7826c111b4)

Line for Haushalt shall be blue

type: custom:power-flow-card-plus
entities:
  grid:
    icon: mdi:transmission-tower
    name: Netz
    entity:
      production: sensor.haus_einspeisung_gesamt_w
      consumption: sensor.haus_entnahme_gesamt_w
    color_circle: true
    display_state: two_way
    use_metadata: false
    invert_state: false
    color_value: true
    color_icon: true
  solar:
    icon: mdi:solar-panel-large
    entity: sensor.pv_leistung_gesamt_w
    secondary_info:
      entity: sensor.pv_gesamt_max_daily_w
      template: ''
      decimals: 1
    color_value: false
    color_icon: false
  battery:
    name: Batterie
    icon: mdi:bat
    entity:
      consumption: sensor.battery_consumption
      production: sensor.battery_production
  individual:
    - entity: sensor.haus_leistung_w
      name: Haushalt
      color_icon: false
      display_zero: true
      color: '#80b8ff'
      icon: mdi:home-outline
      secondary_info:
        entity: sensor.haus_max_daily_w
        decimals: 1
    - entity: sensor.wasser_leistung_w_norm
      name: Wasser
      color_icon: false
      display_zero: true
      color: '#80b8ff'
      icon: mdi:thermometer-water
      secondary_info:
        entity: sensor.wasser_max_daily_w
        decimals: 1
    - entity: sensor.heizung_leistung_w
      icon: mdi:heating-coil
      name: Heizung
      color_icon: false
      display_zero: true
      color: '#80b8ff'
      secondary_info:
        entity: sensor.heizung_max_daily_w
        decimals: 1
  home:
    subtract_individual: false
    entity: sensor.haus_leistung_w
    name: Total
    color_icon: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 0.9
max_flow_rate: 10
watt_threshold: 1000
clickable_entities: true
display_zero_lines:
  mode: transparency
  transparency: 70
  grey_color:
    - 189
    - 189
    - 189
use_new_flow_rate_model: true
disable_dots: false

**Comment by Guenni9** [comment]
Btw, setting `color_icon: true` shows the line color, but of corse also the icon colored. 

It seems, `color_icon:` and `color_value:`
are mixed up.

**Comment by flixlix** [comment]
@commandermatz can you try with version 0.2.1?

**Comment by Guenni9** [comment]
@flixlix, FYI, I'm using 0.2.1, 

`color_icon: false`
![image](https://github.com/flixlix/power-flow-card-plus/assets/101923813/48818ef1-93d3-4a1e-a1c2-3f617d40d328)
`color_icon: true`
![image](https://github.com/flixlix/power-flow-card-plus/assets/101923813/fb1ba4f2-fa3d-499e-82d3-6a7983584137)

**Comment by commandermatz** [comment]
Issue is still existing with new 0.2.1

![Screenshot 2024-04-16 12 03 43](https://github.com/flixlix/power-flow-card-plus/assets/100285050/3e64b650-1f97-4ef4-9aae-debea6d1ba99)

**Comment by flixlix** [comment]
fixed in #593
