### ISSUE TITLE
Multiple individual devices

### ISSUE THREAD

**Issue by elax46** [flixlix/power-flow-card-plus#527]
HI! with the latest beta version the number of individual devices has increased from 2 to 4 but why not allow the inclusion of as many as the user owns? I assume that from a graphic point of view it could be a problem to manage too many devices but one could think of decreasing the size of the circles to fit more entities.

**Comment by flixlix** [comment]
Yes, that is exactly the problem.
There just isn't enough space inside a typical Lovelace card to fit all the entities. Keep in mind that the card also needs to be responsive and work on mobile.

**Comment by elax46** [comment]
Yes, I understood this but I'll give you an example of my use case, as I don't have a battery or solar panels I have several empty spaces. It could be an option for those who do not use these entities to be able to insert other individual type 2 devices in addition

**Comment by flixlix** [comment]
> Yes, I understood this but I'll give you an example of my use case, as I don't have a battery or solar panels I have several empty spaces. It could be an option for those who do not use these entities to be able to insert other individual type 2 devices in addition

I'm sorry but I'm not planning on adding this feature since the complexity of the card as well as the configuration would increase by a lot. I want to keep things relatively simple to make it more stable. Feel free to implement this yourself and submit a PR. I'll do my best to review it and merge
