### ISSUE TITLE
[FEATURE REQUEST] "home" name displayed when 2 individuals

### ISSUE THREAD

**Issue by jacippet** [flixlix/power-flow-card-plus#529]
**Is your feature request related to a problem? Please describe.**
Have two individuals car and essential load, Non essential load is the "home". When all three taking power  and have lines "home" name not displayed.

**Describe the solution you'd like**
"home" name in the above or below line to home close to circle or a central circle with everything feeding off that individually = PV at 0 degrees , battery at 180 degrees, individual 1 at 45 degrees, home 90degrees, individual 2 135 degrees

**Describe alternatives you've considered**
None

**Additional context**

**Comment by flixlix** [comment]
I'm sorry but I am not planning on rearranging the icons anytime soon, I also want to keep this relatively similar to the original HA card
