### ISSUE TITLE
[BUG] Home label does not display once second individual load added but not displayed

### ISSUE THREAD

**Issue by tathamoddie** [flixlix/power-flow-card-plus#531]
**Describe the bug**
The "Home" label only appears if there are 0 or 1 individual load entities.

Once a second individual load entity is added, it disappears.

There is deliberate logic for this, to make way for the line, but that should only apply if the individual entity is actually visible.

https://github.com/flixlix/power-flow-card-plus/blob/8f8e4408d7bcf0ce0fca4ffb2de2d432f36fc387/src/components/home.ts#L112-L114

Occurs in [v0.2.0-beta](https://github.com/flixlix/power-flow-card-plus/releases/tag/v0.2.0-beta)

**To Reproduce**
1. Add one individual entity, with value 0
2. Note that the home label still shows
3. Add a second individual entity, with value 0
4. Note that the home label disappears

**Expected behavior**
Home label should appear until two or more individual entities are _visible_, not just configured.

**Screenshots**

Working, with one:
![image](https://github.com/flixlix/power-flow-card-plus/assets/45753/287720c8-dcc4-47c8-8f90-09d565c00b8f)

Not working, with two:
![image](https://github.com/flixlix/power-flow-card-plus/assets/45753/51eae16c-a35d-4b75-b260-e9ff4ecd64df)

**Browser Console Errors**
No errors in console.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 124.0.1

**Additional context**
Present in [v0.2.0-beta](https://github.com/flixlix/power-flow-card-plus/releases/tag/v0.2.0-beta)

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
Thank you for pointing this bug out, never thought of this edge case.

Implemented a fix for this, will be available in 0.2.1

**Comment by flixlix** [comment]
Fixed in https://github.com/flixlix/power-flow-card-plus/releases/tag/v0.2.1
