### ISSUE TITLE
[BUG] Negative numbers shown as positive

### ISSUE THREAD

**Issue by Mats1717** [flixlix/power-flow-card-plus#549]
Hi
Secondary info on grid is still not showing negative numbers.
Have a sensor my total import export that is showing negative if I exported more than imported.
Right now is sensor -3,6 kWh but it show only 3,6. If I click on secondary it shows -3,6.

Regards Mats

**Comment by flixlix** [comment]
Did you enable the `accept negative` option?

**Comment by Mats1717** [comment]
Where do I find that. Must have mist that function?

**Comment by flixlix** [comment]
Should be available in you ui editor in the `grid -> secondary` subpage

**Comment by flixlix** [comment]
I kept this feature as false by default to avoid breaking current configs

**Comment by Mats1717** [comment]
I dont see that.
![Skärmbild 2024-04-14 160706](https://github.com/flixlix/power-flow-card-plus/assets/124505550/3f11e246-38aa-43c2-9b2b-9b2b7c99cd73)

**Comment by flixlix** [comment]
Can you check what version is shown in your browser console?

**Comment by Mats1717** [comment]
V0.2.0 from today. been on beta for some weeks but same there.

**Comment by Mats1717** [comment]
Alll setup here
[Power flow plus.txt](https://github.com/flixlix/power-flow-card-plus/files/14971060/Power.flow.plus.txt)

**Comment by flixlix** [comment]
> V0.2.0 from today. been on beta for some weeks but same there.

Is that the version really shown in the browsers console? Seems like some caching going on, because the v0.2.0 (no the beta) has this toggle in grid/secondary

**Comment by Mats1717** [comment]
Same om PC, iPad, iPhome. Maybe uninstall and install again?
![Skärmbild 2024-04-14 162944](https://github.com/flixlix/power-flow-card-plus/assets/124505550/4e1840e0-fb8d-4828-9984-c450ad5a1eea)

**Comment by flixlix** [comment]
https://help.planday.com/en/articles/30207-how-to-open-the-developer-console-in-your-web-browser

check if in here, you are getting this:
<img width="487" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/61006057/32e23f1c-efd1-48e6-88f9-8b97b7ebc577">

**Comment by Mats1717** [comment]
It say V0.2.0 beta for mee

**Comment by flixlix** [comment]
In that case you probably just need to clear your browser cache and refresh the page.
https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DDesktop
