### ISSUE TITLE
Individual entity's doesn't store individual fields (like name, icon)

### ISSUE THREAD

**Issue by Jeronimo1971** [flixlix/power-flow-card-plus#550]
Latest version: 0.2.0

It is possible to add individual entity's, but they don't store any of the changes.

Even when you change the name, save everything.
When you enter again the individual entity, the name is again blanco ??

All the same for the changes into the individual entity, nothing of the changes are stored?

**Comment by flixlix** [comment]
Yes this is expected, if you change the entity in the individual config, the card has no way of knowing which individual device you configured

**Comment by Jeronimo1971** [comment]
probably a miscommunication??

If i fill in the name : "Airco" it is NOT stored !!
If i exit the individual to the main and return to the individual... the name is again "blanco"?

![Scherm­afbeelding 2024-04-14 om 17 08 34](https://github.com/flixlix/power-flow-card-plus/assets/55802752/a94f92ab-09ba-496a-a63e-9a1dce99be58)

**Comment by flixlix** [comment]
Oh okay, I didn't understand that.
Is it okay for you if we continue over at #551 ?
Or is this issue different?

**Comment by Jeronimo1971** [comment]
same issue, thank you very much.

Ps great work with this card !!!

**Comment by flixlix** [comment]
> same issue, thank you very much.
> 
> Ps great work with this card !!! Love this one, one of the best cards there are 👍

Thank you very much, means a lot! ❤️
