### ISSUE TITLE
I is not possible to Setup Individual 

### ISSUE THREAD

**Issue by Timer2000** [flixlix/power-flow-card-plus#551]
Hello,

I have updated to the new v2.0 Version.

After Update the Configuration was broken beacause i have two individuell settings. So i have it disabled by # in the Code Editor. The Power Card works aigain.

My next Step was to setup the individuell Entities by the new visual Editor.

I can put some Entities in the Config, but i can not configure them. All Settings in the individuell Menü can not saved.
After close an open this Menü aigain it is all empty.
In the Code Editor i do not found the Settings for individuell Points. Also my disabled Lines are not visible.

Timer

**Comment by Jeronimo1971** [comment]
Same here

**Comment by flixlix** [comment]
I'm sorry, but I do not understand exactly what the issue here is.
Can you go step by step (with screenshots), explaining what you see vs. what you expected?

**Comment by theeye1000** [comment]
Same issue on my side. 

1. I have don ethe update
2. After the Update it was not possible to use the graphical editor, because the old individuals was in the code
3. For that i have delete in the "old" induvidual code in the code Editor.
4. now the graphical editor show the possible settings
5. when i add a individual and want to make some settings it will be only save the entity in the code but noch the settings

when i put the code manualy with the code editor it is working fine.

What i have tested:

1. reload the frontend from the repository
2. uninstall and install the frontend
3. clear cache in browser
4. adding a new card


![grafik](https://github.com/flixlix/power-flow-card-plus/assets/84576636/cb5b4b1d-fd8d-4af3-baf4-bf782bf351c5)


when i save with toggle on it will not save the config... see the code:
![grafik](https://github.com/flixlix/power-flow-card-plus/assets/84576636/76ed6ece-77be-4a71-87ba-03b75cf32f3d)

**Comment by Timer2000** [comment]
here my Power Card

![grafik](https://github.com/flixlix/power-flow-card-plus/assets/110718328/68aed85a-44b9-42da-bcb5-bb6ebd1ab3e7)

here the Menü for this

![grafik](https://github.com/flixlix/power-flow-card-plus/assets/110718328/9670f753-cbea-4be9-aa70-b5a25a3c90dd)

![grafik](https://github.com/flixlix/power-flow-card-plus/assets/110718328/906b7fc9-e66c-4e3a-a56c-93413d92f509)

the Menü with my Settings

![grafik](https://github.com/flixlix/power-flow-card-plus/assets/110718328/d1a4c0bb-a668-46ee-8a18-76fcb9536752)

but after Saving it shows this again

![grafik](https://github.com/flixlix/power-flow-card-plus/assets/110718328/35f93a57-17a3-48ca-956c-892c5f155c1e)

**Comment by Timer2000** [comment]
Where can i find the Settings for Individual?
It is possible to Setup this by CodeEditor? Maybe it ist a bug from the UI.

**Comment by theeye1000** [comment]
> Where can i find the Settings for Individual? It is possible to Setup this by CodeEditor? Maybe it ist a bug from the UI.

With the CodeEditor it ti possible. I also think that it is a bug in the UI.

**Comment by flixlix** [comment]
> Where can i find the Settings for Individual?


The settings for individual should be pretty straightforward to find:

1. In the main menu, click:
<img width="507" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/61006057/91cc4238-9218-48c1-8fdf-e05c7010bf41">

2. Then click:
<img width="504" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/61006057/770f708e-ca96-4beb-8efe-7359ba55d9dc">

3. Here are the settings:
<img width="505" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/61006057/07ba997b-31f9-4eb8-bf59-cd01cc7a4283">

**Comment by flixlix** [comment]
I can't replicate this issue

https://github.com/flixlix/power-flow-card-plus/assets/61006057/68e9a735-f37c-46a5-8173-c4b182cd9cc5

**Comment by Jeronimo1971** [comment]
> I can't replicate this issue
> 
>  Screen.Recording.2024-04-14.at.17.35.41.mov

Strange, works perfect in the "code editor" when i change something... but nothings works in the "visual editor"?
Removed the card, reinstalled it... but the same strange thing with the visual editor?

**Comment by flixlix** [comment]
hmm, very strange indeed... What browser are you using? any errors in the browser console?

**Comment by GitittomeNow** [comment]
Same issue with being unable to save the name of the individuals from the GUI.

**Comment by Jeronimo1971** [comment]
> hmm, very strange indeed... What browser are you using? any errors in the browser console?

Different browsers: Safari, Chrome: all the same. GUI nothing changes, code: works perfect!

**Comment by flixlix** [comment]
@Jeronimo1971 I also used multiple browsers (Chrome, Brave, Firefox, Safari) and don't get the error in any of those 😅 
Do you get any errors in the browser console?

**Comment by Timer2000** [comment]
> > hmm, very strange indeed... What browser are you using? any errors in the browser console?
> 
> Different browsers: Safari, Chrome: all the same. GUI nothing changes, code: works perfect! The extra strange thing: UI works fine for all others BUT for the individual settings?!

Exact the same here.
I have setup this by Code Editor, this works.
I have test the ui by different Hard- and Software. No Chance.

**Comment by Jeronimo1971** [comment]
> @Jeronimo1971 I also used multiple browsers (Chrome, Brave, Firefox, Safari) and don't get the error in any of those 😅 Do you get any errors in the browser console?

No errors: I can type in the fields (like name), but when a change to code or exit and re-enter... nothing is changed. When a change the name in the code, it's immediately displayed in the view?!

**Comment by flixlix** [comment]
this is very strange I've already tried this in two HA installations and had no issues...

**Comment by Jeronimo1971** [comment]
> this is very strange I've already tried this in two HA installations and had no issues...

it's one of the great mysteries of programming :-)
In any case, great adjustments to the card with the new individual additions (even if it is via code) 👍

**Comment by theeye1000** [comment]
> hmm, very strange indeed... What browser are you using? any errors in the browser console?

I got this error in the console
![322274923-77c9d08b-1156-4573-959c-5a05c7676ebf.png](https://github.com/flixlix/power-flow-card-plus/assets/84576636/759c9055-4e6c-44e1-abb1-e91d57ed0a41)

**Comment by joncage** [comment]
Same issue here (chrome).

Seeing a lot of this in the dev console:

![image](https://github.com/flixlix/power-flow-card-plus/assets/73681/b8c926e5-ece5-482b-9c00-a3e13d98d7d6)

![image](https://github.com/flixlix/power-flow-card-plus/assets/73681/533cd143-1570-4be5-8a93-e821e8425e30)

**Comment by Courty40** [comment]
+1, I came here to report the same behaviour. I can get the item to work and appear but it wont remember the name or icon. tried via the UI, code looks out of place compaired to your example ?

Courty

**Comment by flixlix** [comment]
To help me debug this issue, can someone who has this bug, manually install the card using this file and report back what they see in the logs, when they change the configuration of one individual device.

> [!NOTE]
> You need to have this version being logged in your browser console 0.2.0-issue#551. Otherwise you don't have the correct version installed

[power-flow-card-plus.js.zip](https://github.com/flixlix/power-flow-card-plus/files/14978634/power-flow-card-plus.js.zip)


For reference, here is what my output looks like
![image](https://github.com/flixlix/power-flow-card-plus/assets/61006057/2ffc5312-a459-48a1-84d6-65a3618edff4)

**Comment by Jeronimo1971** [comment]
> To help me debug this issue, can someone who has this bug, manually install the card using this file and report back what they see in the logs, when they change the configuration of one individual device.
> 

Hi, this is the error when i change (try) to change the name:

2024-04-15 13:58:18.397 ERROR (MainThread) [frontend.js.latest.202404042] Uncaught error from Safari 17.3.1 on Mac OS 10.15.7
TypeError: Attempted to assign to readonly property.
_configChanged (/hacsfiles/power-flow-card-plus/power-flow-card-plus.js:1:175095)
handleEvent (/hacsfiles/power-flow-card-plus/power-flow-card-plus.js:1:14546)
dispatchEvent ([native code]::)
event (src/common/dom/fire_event.ts:76:21)
addValueChangedListener (src/components/ha-form/ha-form.ts:216:16)
dispatchEvent ([native code]::)
event (src/common/dom/fire_event.ts:76:21)
addValueChangedListener (src/components/ha-form/ha-form.ts:216:16)
dispatchEvent ([native code]::)
event (src/common/dom/fire_event.ts:76:21

**Comment by flixlix** [comment]
@Jeronimo1971 thank you for the help.
I tried to place a console log in the line before the error occurs, do you not get any logs in your console before the error?

**Comment by Jeronimo1971** [comment]
Is it that what you want?

[
![Scherm­afbeelding 2024-04-15 om 16 25 51](https://github.com/flixlix/power-flow-card-plus/assets/55802752/0f3a12da-ea38-4554-bb8a-6a6a719eb8ba)
](url)

**Comment by max-t-d** [comment]
Adding onto this: as soon as I try to add the individual (in this case: my EV charger) via the code editor, the entire card breaks down and doesn't show up anymore... the up until the moment I type in "entity" under individual, everything is fine, as soon as I'm done with "entity:" everything disappears.

**Comment by flixlix** [comment]
@max-t-d seems like your browser is holding on to the old version. Can you check this in the console?

**Comment by flixlix** [comment]
@Jeronimo1971 no, it should look like this (3 objects being printed in one line)

> ![image](https://github.com/flixlix/power-flow-card-plus/assets/61006057/c05ceaed-c4f0-4563-9f53-7b2dbecb08fb)

**Comment by max-t-d** [comment]
> @max-t-d seems like your browser is holding on to the old version. Can you check this in the console?

Strange. For unrelated reason I just rebooted my HA and then proceeded to again empty cache and even opened the page in a completely naked browser install. In my case the console keeps repeating the same error (same on safari and chrome):
![image](https://github.com/flixlix/power-flow-card-plus/assets/143649859/b121b2a4-8db0-40ad-86b2-6244fc251d95)

**Comment by flixlix** [comment]
@max-t-d please send me your config. Any errors on the card? Does it show up on the dashboard

**Comment by psym88** [comment]
same issue here.

What i tried so far:
- Changing the Language of the Browser (Edge chromium newest version) to English
- Changing User Language to English
- Removing other HACS (Mushroom and Kiosk Mode)
- Cleared Browser Cache
- Removed all old PowerFlowCards
- Restarted HA
- Created new Dashboard with only PowerFlowCard

Keep up the good work.. im still hyped for v2.0

**Comment by psym88** [comment]
> To help me debug this issue, can someone who has this bug, manually install the card using this file and report back what they see in the logs, when they change the configuration of one individual device.
> 
> Note
> 
> You need to have this version being logged in your browser console 0.2.0-issue#551. Otherwise you don't have the correct version installed
> 
> [power-flow-card-plus.js.zip](https://github.com/flixlix/power-flow-card-plus/files/14978634/power-flow-card-plus.js.zip)
> 
> For reference, here is what my output looks like ![image](https://private-user-images.githubusercontent.com/61006057/322469621-2ffc5312-a459-48a1-84d6-65a3618edff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDI4MTYsIm5iZiI6MTcxMzIwMjUxNiwicGF0aCI6Ii82MTAwNjA1Ny8zMjI0Njk2MjEtMmZmYzUzMTItYTQ1OS00OGExLTg0ZDYtNjVhMzYxOGVkZmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE3MzUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YTJhNmE0YjlhMTk5ZjU5MjM3ODExYjZjZjQzMGQ1MjQwNzA0NWM5ZmZmOTFjYjVhMjk0NGQxZDM5M2Q0ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nxpObNYaCuE6pPp8j1mdc7WlpaJqAiQJ8ZzR1yu26EI)

![Screenshot 2024-04-15 194113](https://github.com/flixlix/power-flow-card-plus/assets/55204544/d7756b4b-bcc5-43c5-a129-ef8784f8aa1b)
![Screenshot 2024-04-15 194337](https://github.com/flixlix/power-flow-card-plus/assets/55204544/ea959a0c-6c21-4a78-9a27-95ab9d65ff9d)

**Comment by flixlix** [comment]
Please try this fix I've implemented.

> [!NOTE]
> You need to have this version being logged in your browser console 0.2.0-issue551. Otherwise you don't have the correct version installed

[power-flow-card-plus.js.zip](https://github.com/flixlix/power-flow-card-plus/files/14983785/power-flow-card-plus.js.zip)

**Comment by psym88** [comment]
> Please try this fix I've implemented.
> 
> Issue should be fixed now.
> 
> Note
> 
> You need to have this version being logged in your browser console 0.2.0-issue551. Otherwise you don't have the correct version installed
> 
> [power-flow-card-plus.js.zip](https://github.com/flixlix/power-flow-card-plus/files/14983785/power-flow-card-plus.js.zip)

danke dir vielmals!
quick tests shows it's fixed for me

**Comment by AminShAT** [comment]
> > I can't replicate this issue
> 
> > 
> 
> >  Screen.Recording.2024-04-14.at.17.35.41.mov
> 
> 
> 
> Strange, works perfect in the "code editor" when i change something... but nothings works in the "visual editor"?
> 
> Removed the card, reinstalled it... but the same strange thing with the visual editor?

Same here

**Comment by flixlix** [comment]
Fixed in https://github.com/flixlix/power-flow-card-plus/releases/tag/v0.2.1

**Comment by Timer2000** [comment]
Now with 0.2.1 all is perfect.

Thank you very much for your fast fix
