### ISSUE TITLE
[BUG] Showing W instead of % in the Fossil Fuel tab

### ISSUE THREAD

**Issue by ma9mwah** [flixlix/power-flow-card-plus#557]
**Describe the bug**
When selecting state of type to 'Percentage' in the fossil fuel tab the display still shows at 'W'atts

![image](https://github.com/flixlix/power-flow-card-plus/assets/21035345/81cfe8b3-007b-4d22-b41f-1e342801ea79)

**Comment by flixlix** [comment]
Fixed in #560 
Will release in v0.2.1, sorry for the inconvenience
