### ISSUE TITLE
[BUG] Watt and Kilowatt Decimal-Setting has no effect

### ISSUE THREAD

**Issue by ohkaja** [flixlix/power-flow-card-plus#558]
**Describe the bug**
When Decimals configured in the advanced section the setting is not applied.

**To Reproduce**
1. advanced
2. set Watt or Kilowatt decimals

**Expected behavior**
1.45 goes to 1.5 when decimal is set to 1 

**Screenshots**
Watt:
<img width="710" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/93218188/5214a42c-88ca-45e1-81a3-adac0eaa8401">

Kilowatt:
<img width="731" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/93218188/e99bc48f-17f3-4f17-94da-51ad9ec4ea74">

**Browser Console Errors**
If applicable, add Errors from the browser console.

**Desktop (please complete the following information):**
 - OS: Windows, iOS, Mac OS
 - chrome, edge, safari
 - latest

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro Max
 - OS: latest
 - Browser HA Browser
 
- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
Should also be fixed in #560 
Will merge for version 0.2.1 :)
