### ISSUE TITLE
[SUPPORT] Unit white space, individual entities?

### ISSUE THREAD

**Issue by xsirpreisx** [flixlix/power-flow-card-plus#568]
Hi there, 

awesome how far this thing has come. I've been using "my" version for a long time now without any changes, and only today removed that and upgraded to your latest version. Great work!

Only one thing I haven't been able to understand. Why is there no whitespace between value and unit for my individual entities?

![image](https://github.com/flixlix/power-flow-card-plus/assets/37976738/bfb61949-c577-4aca-b8be-90a80054aebe)

There are switches to add white spaces for secondary information, but not for the entity itself. What am I missing? Is that because the two entities I created are setup like this:

![image](https://github.com/flixlix/power-flow-card-plus/assets/37976738/420fe418-3bda-484f-b078-867419c6cb84)

and this:

![image](https://github.com/flixlix/power-flow-card-plus/assets/37976738/1e438b6e-e13d-4446-86e1-6bed5d6e9f8e)

Thanks in advance!

**Comment by flixlix** [comment]
Yeah, this is a feature I need to add for 0.2.2

**Comment by flixlix** [comment]
fixed in #590

**Comment by xsirpreisx** [comment]
Thanks. I updated, but I currently don't have a white space just yet. I don't see an option for that either. What am I missing?

**Comment by flixlix** [comment]
@xsirpreisx have you tried clearing your cache?

https://how-can-i.luca-felix.com/clear-cache

Which version is currently shown in your browser console?

**Comment by xsirpreisx** [comment]
Yea, I cleaned my cache, but that didn't change anything. 

I guess the option to toggle the whitespace would be found in the Individual configuration?

![image](https://github.com/flixlix/power-flow-card-plus/assets/37976738/b092331a-3b03-41b3-a470-5c58509dfd50)

Note there for me yet. 

0.2.2 seems to be installed:

![image](https://github.com/flixlix/power-flow-card-plus/assets/37976738/6fbeef16-8668-46cd-a33c-8892dd74b877)

**Comment by xsirpreisx** [comment]
Yea, using that file now it works, thanks!

![image](https://github.com/flixlix/power-flow-card-plus/assets/37976738/585fffe3-805d-498c-bfb1-52b94915e65e)

One more question: Secondary information when 0 does not seem to display the unit. Is that to be expected? See screenshot above ("Auto"). "0 kWh" would look much better. :-)
