### ISSUE TITLE
outdated configuration 

### ISSUE THREAD

**Issue by gemjack** [flixlix/power-flow-card-plus#569]
Since installing the latest version i have the error attached.  This is both on my Windows PC using Firefox, I also have the same problem with Chrome.  The Andriod app does exactly the same thing.  I have tried re downloading and re installing to no effect.
![Screenshot_20240416_131116_Home Assistant](https://github.com/flixlix/power-flow-card-plus/assets/40173695/3207c072-e491-4ec1-aa82-65db56826351)

.

**Comment by flixlix** [comment]
Please read the changelogs before updating.

This is expected. You need to remove individual1 and individual2 from your config and reconfigure it with the new type of configuration

**Comment by robi59italy** [comment]
still the same issue.
removed invidual1, restart home assistant, try to reconfigure and it doesn't work.
WIth the previous version of power card plus was working without any issue.

**Comment by robi59italy** [comment]
> Please read the changelogs before updating.
> 
> This is expected. You need to remove individual1 and individual2 from your config and reconfigure it with the new type of configuration

it looks still open..

**Comment by robi59italy** [comment]
> > Please read the changelogs before updating.
> > This is expected. You need to remove individual1 and individual2 from your config and reconfigure it with the new type of configuration
> 
> it looks still open..

solved using zero display.. never used before

**Comment by gemjack** [comment]
I just removed individual1 and it worked no restart etc.  Not sure what changes offer to a card that was functioning perfectly well. Anyway happy now.
