### ISSUE TITLE
You are using an outdated configuration. Please update your configuration to the latest version.

### ISSUE THREAD

**Issue by mcderd-coder** [flixlix/power-flow-card-plus#572]
I have updated today after running this for many months, and I get this message "You are using an outdated configuration. Please update your configuration to the latest version."

How do I update the configuration to the latest version? What does that mean?

**Comment by flixlix** [comment]
Duplicate of https://github.com/flixlix/power-flow-card-plus/issues/569

Basically you need to remove `individual1` and `individual2` from your config, because the new version uses a new schema

**Comment by FarouqDin** [comment]
I have the same issue, how do i add my car charging as separate device?
