### ISSUE TITLE
New card error with individual devices in Fully Kiosk Browser

### ISSUE THREAD

**Issue by bigfeetneedbigboots** [flixlix/power-flow-card-plus#574]
Updated (v2.0) card displays fine in Chrome but the same config does not display correctly on tablets running Fully Kiosk Browser when individual devices are used. 

**To Reproduce**
Create card with individual devices configured. Display on PC browser and on Fully Kiosk Browser

**Expected behavior**
Display in Fully Kiosk Browser with individual devices configured as it did before v2.0 update.

**Screenshots**
When card doesn't display correctly in Fully Kiosk Browser, it just shows the config.

**Browser Console Errors**
N/A

**Desktop (please complete the following information):**
 - OS: OSX 14.1.2 (23B92)
 - Browser: Chrome
 - Version: Version 123.0.6312.124 (Official Build) (arm64)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A8
 - OS: Android 14
 - Browser: Fully Kiosk Browser
 - Version: 1.54.1-emm

**Additional context**
N/A

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
You probably just need to clear your cache in your tablet, I assume the fully kiosk browser still has the old version

**Comment by bigfeetneedbigboots** [comment]
Cleared by going into Settings > Apps > Fully Kiosk Browser > Storage > Clear Cache but that doesn't fix the problem. I also rebooted the tablet afterwards but no joy there either.

**Comment by olliox** [comment]
Same Problem here with Fully Kiosk Browser on Fire HD 10. Clearind the Cache doesn't fix the problem. It says "outdated Configuration" and just shows the Code. Same Configuration on Chrome and HA Companion App (iphone) works normal.

**Comment by flixlix** [comment]
@olliox before updating, always read the release notes.
I clearly stated the breaking change for individual devices.

Remove your configuration from `individual1` and `individual2` and reconfigure your individual devices

**Comment by olliox** [comment]
Thank you, & Sorry for that. Deleted individuals and that worked.
Will try the Reconfiguration.

**Comment by bigfeetneedbigboots** [comment]
Missed the conversion of individual enties configured as individual1 & individual2 to simply individual with multiple entities in new config.
