### ISSUE TITLE
EV Charging

### ISSUE THREAD

**Issue by G8YTZ** [flixlix/power-flow-card-plus#577]
I've used the Tesla integration to provide the charger information to the Power Flow Plus card, this works fine, But when charging away from home the charge indication shows on Power Flow Plus card.

I would only like to do this for home charging.

It would be useful if there was a switch option to ignore charging when the vehicle is away from "home"

My chargers are not SMART types, so using a feed from charter is not possible.
![PowerFlowPlus](https://github.com/flixlix/power-flow-card-plus/assets/35895759/07bb9e38-2142-4e55-9cc7-4786faba73b8)

**Comment by flixlix** [comment]
Hi thank you for your feature request.
I think this would add too much complexity to the card for no benefit to most users.

What you could do is create a template sensor that reports the state of the charger, except when your car is away, then it reports always 0.

Hope this helps 😊

**Comment by G8YTZ** [comment]
I was trying to work out something like that. I’ll do a bit more thinking.I’ve noticed a lot of bugs, but most can be resolved by diving into the YAML. Still, it’s a really handy application.Justin.Sent from my Remington Rand UNIVACwww.g8ytz.com On 17 Apr 2024, at 18:19, Luca Félix ***@***.***> wrote:﻿
Hi thank you for your feature request.
I think this would add too much complexity to the card for no benefit to most users.
What you could do is create a template sensor that reports the state of the charger, except when your car is away, then it reports always 0.
Hope this helps 😊
