### ISSUE TITLE
[BUG] Home circle border "flickers" between multiple colors according the sum of the sources and full solid single color

### ISSUE THREAD

**Issue by david-rapan** [flixlix/power-flow-card-plus#579]
**Describe the bug**
Home circle border "flickers" between multiple colors according the sum of the sources and full solid single base "stock" color (blue in my case). I'm not exactly sure if that would be the same for every setup and installation or if it is related to grid color.

**To Reproduce**
Just by using the card.

**Screenshots**
OK:
![power_infographics_home_blue_error_ok](https://github.com/flixlix/power-flow-card-plus/assets/161127373/3a09456c-cb3b-4cc2-9b81-39103528bb15)
OK 2:
![power_infographics_home_blue_error_ok_2](https://github.com/flixlix/power-flow-card-plus/assets/161127373/231e4600-3215-49fb-b0b6-acf9292e0b73)
OK, where is power only from grid:
![power_infographics_home_blue_error_ok_1](https://github.com/flixlix/power-flow-card-plus/assets/161127373/c735f3a0-0660-4ac3-9c37-34f759032bd3)
OK:
![power_infographics_home_blue_error_ok_4](https://github.com/flixlix/power-flow-card-plus/assets/161127373/86f0bcf3-5973-4a02-b357-520f6255dc7e)
ERROR:
![power_infographics_home_blue_error](https://github.com/flixlix/power-flow-card-plus/assets/161127373/8b188e34-9357-45c4-b57a-445e6b5d6922)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge

**Smartphone (please complete the following information):**
 - Device: IPhone SE
 - OS: iOS 15.8.2
 - Browser: Edge

**Additional context**
It happens more frequently when the Grid source sitting around 0 W <-100,100>.

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**
- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).
- [X] I have the latest version of the card installed.
- [X] I have cleared my browser cache **after** installing, updating and configuring the card.
- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
<img width="508" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/61006057/64d355dc-91a4-48e6-b74c-8abf09986653">


I cannot replicate this issue. What I think your issue might be is that either your battery or grid sensors are reporting exports & imports simultaneously (which is not possible). This might be confusing the calculations

**Comment by david-rapan** [comment]
> <img alt="image" width="508" src="https://private-user-images.githubusercontent.com/61006057/324258682-64d355dc-91a4-48e6-b74c-8abf09986653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDg0OTYsIm5iZiI6MTcxMzk0ODE5NiwicGF0aCI6Ii82MTAwNjA1Ny8zMjQyNTg2ODItNjRkMzU1ZGMtOTFhNC00OGU2LWI3NGMtOGFiZjA5OTg2NjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA4NDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4YzRjZWYwMmJlNThjOTg0NDliOWU1MzdiNmJhMTg0MTFkNjRmYjNiYjgxNzc2NTdlZWU2ODcwNWRjMmQyMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aXIDpyhnO7gJHtdqAajcrJlOy_se-7tGwhs_MuGnjB4">
> I cannot replicate this issue. What I think your issue might be is that either your battery or grid sensors are reporting exports & imports simultaneously (which is not possible). This might be confusing the calculations

I'm using single sensor for the Grid where positive numbers are from Grid and negative to Grid so I don't think that's the case. But the sensor for the grid has higher refresh rate (every second or so), could that cause the issue?
