### ISSUE TITLE
Decimal values is not presented in individual

### ISSUE THREAD

**Issue by HayderHekmat** [flixlix/power-flow-card-plus#585]
As depicted in attached screenshot the individual value is presented without decimal values.
The decimal value has been configured to be 2 digits. 

In addition, when opened the dashboard in smartphone by using home assistant application, it is not presented individual.

**To Reproduce**
1. Go to  power card

**Expected behavior**

**Screenshots**
![image](https://github.com/flixlix/power-flow-card-plus/assets/126294075/bec32236-056b-4ee9-9da9-ef7ef96b1710)

**Browser Console Errors**
If applicable, add Errors from the browser console.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge, Chrome

**Smartphone (please complete the following information):**
 - Device: PC, iphone, Android

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [ ] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
Fixed in #587

Regarding your individual not appearing on mobile, it is probably just a caching issue, your phone is probably holding on to the old version. You just need to clear the cache and you're good to go :)
