### ISSUE TITLE
[SUPPORT]

### ISSUE THREAD

**Issue by Jack77777777** [flixlix/power-flow-card-plus#601]
Is it possible to have different colours for first and secondary Info of an individual?

For example first yellow and second blue. I would like to avoid that one is white but the two different coulours.

**Comment by flixlix** [comment]
hey there,
the only way I can think of doing this is by using card mod.

```yaml
card_mod:
  style: |
    ha-card {
      --icon-individual-left-top-color: #f00;
      --secondary-text-individual-left-top-color: #0a0;
      --text-individual-left-top-color: #00f;
    }
```

the issue with this is that it's not dynamic, meaning your top left entity will always have these colors, not matter what

**Comment by Jack77777777** [comment]
Excellent.
Tahnk you
