### ISSUE TITLE
[BUG] z-index issue when using wallpanel with black screen (screensaver)

### ISSUE THREAD

**Issue by fnxpt** [flixlix/power-flow-card-plus#603]
**Describe the bug**
When using this card with wallpanel and screensaver option the `z-index: 2` is making the card to be on top of the blackscreen.

**To Reproduce**
1. Install wallpanel
2. add card to wallpanel
3. enable screensaver
4. wait and see

**Expected behavior**
Card shouldn't overlap screensaver

**Screenshots**
<img width="682" alt="Screenshot 2024-04-23 at 18 31 46" src="https://github.com/flixlix/power-flow-card-plus/assets/1815240/f1ee814d-4508-4ef0-888c-74c8b32ecc2a">

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
hey there, unfortunately I had to revert the changes from the PR you made, because the home tap_action was not working on the new version as seen in #685.

I cannot implement a fix for this issue otherwise.
