### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by amigatommy** [flixlix/power-flow-card-plus#629]
Display of values in kW does not work with Individual1 and Individual2. The values there are always in W.
 
Normaly, like in Solar or Grid, all values greater then 999 W should shown as kW ( Watt to Kilowatt Threshold: 1000 ). 

 - OS: Debian12 on Proxmox
 - Its independent of which browser or device you use.

- [ X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [ X] I have the latest version of the card installed.

- [ X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X ] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by Wank-ster** [comment]
I can't understand that. To me it works just fine with individual entities. You just need to make sure that the underlying sensor is also in "kW".

![image](https://github.com/flixlix/power-flow-card-plus/assets/142676146/aa3f647c-5789-4b7a-a310-cf8365fff7e4)

**Comment by amigatommy** [comment]
Ok, Problem solved.
I looked in the device settings and found the error: "W" was entered in the "Unit" field, entry removed, and it works.
Sorry, my fault !
![IMG_0497](https://github.com/flixlix/power-flow-card-plus/assets/32936976/5450124e-78a8-43b1-8b2f-b65dc846e29e)
