### ISSUE TITLE
Allow secondary_info to display text

### ISSUE THREAD

**Issue by godfreym29** [flixlix/power-flow-card-plus#63]
Thank you, great card
I've added my eddi using  individual1 and would like to use secondary_info to display the eddi's status.
I've installed the latest update which allows secondary information for all circles.
Would it be possible to allow text as well as numbers?

The stae for the eddi status can be things like "Stopped", "Diverting", "Paused", etc

**Comment by flixlix** [comment]
I like this idea, I'll add it to the to-do list. I think the main challenge here will be handling States that are too large for the space available (overflow scenario)

**Comment by flixlix** [comment]
Added this feature! 🚀 #65 
Will be available in the next version of the card.
