### ISSUE TITLE
future request - wrong display secondary_info kw_decimals

### ISSUE THREAD

**Issue by Destroyer061090** [flixlix/power-flow-card-plus#66]
Very nice card, thanks you!
I recognnized below possible improvments:
- "secondary_info" below "home" is not showing with the set "kw_decimals: 2" but rounded.
- Carbon emission is different compared standard energy card, why?

![immagine](https://user-images.githubusercontent.com/126196958/231468083-4fe99957-4ff2-4dca-956d-2aabc253417c.png)

**Comment by flixlix** [comment]
Thank you for your suggestions.
This card is not meant to replace the original [Energy Distribution Card](https://www.home-assistant.io/dashboards/energy/#energy-distribution). There is a [difference between energy and power](https://www.diffen.com/difference/Energy_vs_Power). As such it should only be used with Power entities, not energy. Use Energy entities at your own risk, as this is not supported.

For the second suggestion, can you please share the code you used for the card? No secondary-info should be needed, as you already have the power state below the home icon.

**Comment by flixlix** [comment]
I'm closing this issue, since I got no response
