### ISSUE TITLE
[FEATURE REQUEST] - Support Multiple Battery Inverters

### ISSUE THREAD

**Issue by Fayrewood** [flixlix/power-flow-card-plus#674]
**Is your feature request related to a problem? Please describe.**
I have multiple battery inverters to enable me to discharge at 6kw, instead of a single inverter of 3kw.  

**Describe the solution you'd like**
Would it be possible to add the option for multiple inverters to show each inverter status.

**Describe alternatives you've considered**
Although I could sum the inverter sensors in HA, it would be nice to see each individual battery inverter and the battery SOC.

**Additional context**

**Comment by flixlix** [comment]
Hi, thank you for your suggestion. Unfortunately this is too much of a niche scenario, that I can't justify the great amount of time this would take to implement. I hope you can understand
