### ISSUE TITLE
[BUG] Units for primary information not shown correctly

### ISSUE THREAD

**Issue by Matthis** [flixlix/power-flow-card-plus#684]
Hey, first of all, great job! I really like the Integration.

Bug:
All Circles (exept for the "individual" ones) show the unit "Watt" (Power) for primary information, independently from the configured source/entity.
If I configure an entity which uses Wh (Energy) instead, e.g. for Grid: the Grid circle shows the unit as "W" not as "Wh", which is incorrect.

Since I prefer to show the used energy instead of the power, it would be nice, if also the unit for the primary information can either be configured or directly derives the unit from the configured source/entity.

This was observed in version 0.2.2 and 0.2.3.

Thank you!

**Comment by flixlix** [comment]
Hey, thank you for the kind words! 
This card does not support showing energy values, for that please use the Energy Flow Card Plus
