### ISSUE TITLE
[BUG] Click/Tap on House consumption no longer displays graph

### ISSUE THREAD

**Issue by kazzaw** [flixlix/power-flow-card-plus#685]
**Describe the bug**
After the most recent update, clicking or tapping on the home consumption no longer allows a graph/history to be displayed 

**To Reproduce**

Tap on house/consumption - nothing happens

**Expected behavior**

Previously, tapping on the house/consumption would display the history of the entity. All other entities currently work as expected. 

**Screenshots**

**Browser Console Errors**
If applicable, add Errors from the browser console.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by txtasosxt** [comment]
I was about to create an issue for that as well.
It's not only the "More info" (graph) of the Home, but no "tap action" works at all in regards to the Home circle.
![image](https://github.com/user-attachments/assets/464a8c4a-895a-4be0-8805-737c8a602619)

**Comment by ChristianTannheimer** [comment]
I have the same issue, also the second info tab action doesn't work.

**Comment by ohkaja** [comment]
Same here. All circles exept "home" works. Can that anything as typ action there, nothing works. The circle is noch clickable.


https://github.com/user-attachments/assets/c41c1bd6-136d-4c43-a671-4abe4ee59af9

**Comment by Hakari129** [comment]
I also have this problem

Power Flow Card Plus v0.2.3
HA Core version 2024.8.3
HA Supervisor 2024.08.0

**Comment by MCBrakel** [comment]
+1, Exactly same issue here.

Power Flow Card Plus 0.2.3
Core 2024.8.3
Supervisor 2024.08.0
Operating System 13.1
Frontend 20240809.0

**Comment by wepster** [comment]
Same here

**Comment by flixlix** [comment]
sorry for the inconvenience, fixed this issue on v0.2.4

**Comment by wepster** [comment]
Can confirm, thank you :)
