### ISSUE TITLE
unit of measurement [BUG]

### ISSUE THREAD

**Issue by DvdEnde** [flixlix/power-flow-card-plus#74]
**Describe the bug**
The unit of measurement for the power to car is set to Kw. However, it shows in W on the card. see image
![image](https://user-images.githubusercontent.com/114862353/231800131-477a27df-e796-4cfb-9163-9f3411f83497.png)

**To Reproduce**
set unit of measurement for power to car to Kw
include power_to_car to power-flow-card-plus. This looks like: 
```yaml
  individual1:
    entity: sensor.vw_id_4_charge_power
    icon: mdi:car-electric
    color: '#80b8ff'
    name: VW ID.4
```

**Expected behavior**
Expected that same unit_of_measurement is used in card as set on entity. see image
![image](https://user-images.githubusercontent.com/114862353/231801054-7207e87b-c116-4588-ba99-5778eb77421a.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
The current behavior of the card only looks for the state of your entity and not the `unit_of_measurement` you set it as. If you want to have it as `kW`, either set the `unit_of_measurement` in the individual configuration or change the `watt_threshold`
