### ISSUE TITLE
[BUG] Top individual device flow not showing correctly on iPhone 

### ISSUE THREAD

**Issue by luisiam** [flixlix/power-flow-card-plus#75]
**Describe the bug**
The top individual device flow is showing correctly on computer browser but not in the iOS app. 

**To Reproduce**
1. Add individual device
3. Check in iOS app

**Expected behavior**
Animation on iOS app should be the same as it is on computer browser 

**Screenshots**
![image](https://user-images.githubusercontent.com/16310467/231829496-97fd83a1-94c7-424a-a11f-feaabe9e36c3.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: latest

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 16.4.1
 - Browser: Home Assistant App
 - Version: 2023.4

**Additional context**
N/A

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
I also had this issue for a short period of time on someone else's iPhone, it ended up being a cache problem. The only way I was able to clear the cache was to delete the home assistant app and install it again. In that case, no login was necessary after installing...
Can you try it in a browser on your iPhone?

**Comment by flixlix** [comment]
fixed in #78, will be implemented in the next release
