### ISSUE TITLE
Feature Request: Home configuration entity to be displayed

### ISSUE THREAD

**Issue by e10kstarfire** [flixlix/power-flow-card-plus#85]
At the moment I guess the watts value displayed inside the Home bubble is calculated automatically.

I would like the ability to display the value from the home entity you can optionally define.

Why? Well, there are losses with the inverter and battery in converting back and forth and currently these are effectively accounted for under the Home display.

The value I get for home is around 100W higher than what I am actually using, where as the value I define in the entity is my true house consumption. Yes, with this change if you looked at the dashboard and added the values together they would not match but I would rather see the true consumption of my house (so I can alert if its higher than expected etc).

Thanks!

**Comment by flixlix** [comment]
Created this PR: #86 
This feature will be available in the next version of the card

**Comment by e10kstarfire** [comment]
Thank you!
