### ISSUE TITLE
[OTHER] 

### ISSUE THREAD

**Issue by xsirpreisx** [flixlix/power-flow-card-plus#91]
Hi,

your latest code (not the released JS file) seems to produce unit_of_measurement text where the first letter is in upper case, I believe. Only for secondary_info. Or maybe I did something wrong.

Didn't have much time and wasn't able to find the problem right away, so maybe you have an idea?

![image](https://user-images.githubusercontent.com/37976738/232424268-2c0cf124-fb11-4dac-b90c-0eae295379ab.png)

**Comment by flixlix** [comment]
Added a quick-fix for now in the `feat-hide-inactive-lines` branch

**Comment by flixlix** [comment]
Keep in mind, that if your `secondary_info` is a string, the text will also not be capitalized anymore
